
SELECT DISTINCT
	FCFO.CODCFO,
	FCFO.NOMEFANTASIA,
	FCFO.CGCCFO
FROM FLAN (NOLOCK)
	INNER JOIN FCFO (NOLOCK) ON
		FCFO.CODCFO = FLAN.CODCFO
	INNER JOIN FTDO (NOLOCK) ON
		FTDO.CODTDO = FLAN.CODTDO
WHERE 
	FLAN.PAGREC = 2
	AND ((FLAN.STATUSLAN = 0) OR (FLAN.STATUSLAN = 1 AND FLAN.DATABAIXA >= FLAN.DATAVENCIMENTO))
	AND FLAN.DATAVENCIMENTO BETWEEN :DATAINICIAL AND :DATAFINAL
	AND UPPER(FCFO.NOMEFANTASIA) NOT IN ('PREFEITURA DE JUAZEIRO DO NORTE', 'SECRETARIA DA RECEITA FEDERAL','SECRETARIA DE PREVIDENCIA SOCIAL', 'FACULDADE PARAÍSO DO CEARÁ')