-- 1- Lista de matrículas.

SELECT RA
FROM SALUNO

-- 2- Lista de matrículas de alunos matriculados em 2021.2.

SELECT 
	SMATRICPL.RA		[MATRICULA],
	SPLETIVO.CODPERLET	[PERIODO_LETIVO]

FROM SPLETIVO
	INNER JOIN SMATRICPL (NOLOCK) ON SMATRICPL.IDPERLET = SPLETIVO.IDPERLET

WHERE SPLETIVO.CODPERLET IN ('2021.2')

-- 3- Matriculados com onúmero de matrícula e nome.

SELECT 
	SMATRICPL.RA		[MATRICULA],
	SPLETIVO.CODPERLET	[PERIODO_LETIVO],
	UPPER(PPESSOA.NOME)	[NOME]

FROM SPLETIVO
	INNER JOIN SMATRICPL (NOLOCK) ON SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SALUNO (NOLOCK) ON SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA (NOLOCK) ON PPESSOA.CODIGO = SALUNO.CODPESSOA

WHERE SPLETIVO.CODPERLET IN ('2021.2')

-- 4- Matriculados com onúmero de matrícula, nome e curso.

SELECT 
	SMATRICPL.RA			[MATRICULA],
	UPPER(PPESSOA.NOME)		[NOME],
	SPLETIVO.CODPERLET		[PERIODO_LETIVO],
	SCURSO.NOME				[CURSO]

FROM SPLETIVO
	INNER JOIN SMATRICPL (NOLOCK) ON SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SALUNO (NOLOCK) ON SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA (NOLOCK) ON PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO

WHERE SPLETIVO.CODPERLET IN ('2021.2')

-- 5- Matriculados com onúmero de matrícula, nome, curso, disciplina e status cursando.

SELECT 
	SMATRICPL.RA			[MATRICULA],
	UPPER(PPESSOA.NOME)		[NOME],
	SPLETIVO.CODPERLET		[PERIODO_LETIVO],
	SCURSO.NOME				[CURSO],
	SDISCIPLINA.NOME		[DISCIPLINA],
	SSTATUS.DESCRICAO		[STATUS]

FROM SPLETIVO
	INNER JOIN SMATRICPL (NOLOCK) ON SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
    INNER JOIN SMATRICULA (NOLOCK) ON SMATRICULA.RA = SMATRICPL.RA
	INNER JOIN SALUNO (NOLOCK) ON SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA (NOLOCK) ON PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STURMADISC (NOLOCK) ON STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SDISCIPLINA (NOLOCK) ON SDISCIPLINA.CODDISC = STURMADISC.CODDISC
    INNER JOIN SSTATUS (NOLOCK) ON SSTATUS.CODSTATUS = SMATRICULA.CODSTATUS

WHERE SPLETIVO.CODPERLET IN ('2021.2') AND SSTATUS.DESCRICAO IN ('cursando')
