-- SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SPSAREAOFERTADA';

SELECT DISTINCT
	SPSPROCESSOSELETIVO.NOME  AS 'PROCESSO SELETIVO',
	SPSUSUARIO.NOME           AS 'NOME DO CANDITADO',
	SPSUSUARIO.EMAIL          AS 'EMAIL DO CANDITADO',
	SPSUSUARIO.TELEFONE2      AS 'TELEFONE',
	SPSAREAINTERESSE.NOME     AS 'CURSO',

	CASE
	WHEN SPSOPCAOINSCRITO.STATUS = 0 THEN 'INSCRITO PARA SELEÇÃO'
	--WHEN SPSOPCAOINSCRITO.STATUS = 3 THEN 'DESCLASSIFICADO POR INSUFICIÊNCIA DE NOTA'
	WHEN SPSOPCAOINSCRITO.STATUS = 5 THEN 'EM CHAMADA'
	WHEN SPSOPCAOINSCRITO.STATUS = 7 THEN 'COMPARECEU À CHAMADA'
	--WHEN SPSOPCAOINSCRITO.STATUS = 9 THEN 'NÃO COMPARECEU À CHAMADA'
	ELSE 'INSCRI��O CANCELADA'
END AS 'STATUS DE INSCRI��O',

	CASE
	WHEN SPSOPCAOINSCRITO.STATUS = 7 THEN  
		CASE 
		WHEN SMATRICPL.CODSTATUS = 125 THEN 'PRÉ-MATRICULADO - PS'
		WHEN SMATRICPL.CODSTATUS = 101 THEN 'MATRICULA WEB'
    END
END AS 'STATUS DO ALUNO',

	SBOLSAALUNO.DESCONTO AS  'DESCONTO DA BOLSA'

FROM SPSINSCRICAOAREAOFERTADA
	INNER JOIN SPSUSUARIO (NOLOCK) ON	
		SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
	INNER JOIN SPSAREAOFERTADA (NOLOCK) ON	
		SPSAREAOFERTADA.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
	INNER JOIN SPSPROCESSOSELETIVO (NOLOCK) ON	
		SPSAREAOFERTADA.IDPS = SPSPROCESSOSELETIVO.IDPS
	INNER JOIN SPSAREAINTERESSE ON
		SPSAREAINTERESSE.IDAREAINTERESSE = SPSAREAOFERTADA.IDAREAINTERESSE
	INNER JOIN SPSOPCAOINSCRITO ON
		SPSOPCAOINSCRITO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
		AND SPSOPCAOINSCRITO.NUMEROINSCRICAO = SPSINSCRICAOAREAOFERTADA.NUMEROINSCRICAO
		AND SPSOPCAOINSCRITO.IDAREAINTERESSE = SPSAREAOFERTADA.IDAREAINTERESSE
	LEFT JOIN SMATRICPL (NOLOCK) ON 
		SMATRICPL.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
		AND SMATRICPL.NUMEROINSCRICAO = SPSINSCRICAOAREAOFERTADA.NUMEROINSCRICAO
	LEFT JOIN SCONTRATO  (NOLOCK) ON
		SCONTRATO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SCONTRATO.IDPERLET = SMATRICPL.IDPERLET
		AND SCONTRATO.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
		AND SCONTRATO.RA = SMATRICPL.RA
	LEFT JOIN SBOLSAALUNO (NOLOCK) ON
		SBOLSAALUNO.CODCONTRATO = SCONTRATO.CODCONTRATO
		AND SBOLSAALUNO.IDPERLET = SCONTRATO.IDPERLET
		AND SBOLSAALUNO.RA = SCONTRATO.RA
		AND SBOLSAALUNO.CODCOLIGADA = SCONTRATO.CODCOLIGADA

WHERE	
	SPSINSCRICAOAREAOFERTADA.IDPS IN (209,210,211,212,213,214,215,217,218)
	AND SPSOPCAOINSCRITO.STATUS IN (5,0,7)
