-- SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SPSAREAOFERTADA';

SELECT DISTINCT
SPSINSCRICAOAREAOFERTADA.IDPS,
SPSUSUARIO.TELEFONE2,
SPLETIVO.CODPERLET

FROM SPSINSCRICAOAREAOFERTADA
    INNER JOIN SPSUSUARIO (NOLOCK) ON	
		SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
    INNER JOIN SPSOPCAOINSCRITO ON
		SPSOPCAOINSCRITO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
        AND SPSOPCAOINSCRITO.NUMEROINSCRICAO = SPSINSCRICAOAREAOFERTADA.NUMEROINSCRICAO
	LEFT JOIN SMATRICPL (NOLOCK) ON 
		SMATRICPL.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
		AND SMATRICPL.NUMEROINSCRICAO = SPSINSCRICAOAREAOFERTADA.NUMEROINSCRICAO
	INNER JOIN SHABILITACAOALUNO (NOLOCK) ON
			SMATRICPL.RA = SHABILITACAOALUNO.RA
		AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
    INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.RA = SHABILITACAOALUNO.RA
	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.IDPERLET = SMATRICPL.IDPERLET

WHERE	
	SPSINSCRICAOAREAOFERTADA.IDPS IN (187,189,191,193,195,197,198,199,200,201,204,205,206,208,209,210,211,212,213,214,215,217,218,219,220,222,223,224)
	AND SMATRICPL.CODSTATUS  NOT IN (125,101)
	
