-- SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SPSAREAOFERTADA';

SELECT
    FLAN.IDLAN,
    FBOLETO.IDBOLETO,
    FBOLETO.IPTE,
    FBOLETO.NOSSONUMERO


FROM
    SPSINSCRICAOAREAOFERTADA
    INNER JOIN SPSUSUARIO (NOLOCK) ON
			SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
    INNER JOIN FLAN (NOLOCK) ON 
			FLAN.IDLAN = SPSINSCRICAOAREAOFERTADA.IDLAN
    INNER JOIN FLANBOLETO (NOLOCK) ON
			FLANBOLETO.IDLAN = FLAN.IDLAN
    INNER JOIN FBOLETO (NOLOCK) ON
			FBOLETO.IDBOLETO = FLANBOLETO.IDBOLETO

WHERE
	FBOLETO.STATUS = 0
    AND SPSINSCRICAOAREAOFERTADA.IDPS IN (225, 229)
  --AND :SPSINSCRICAOAREAOFERTADA.IDPS LIKE '%' 

/*
FBOLETO.IPTE
FBOLETO.IDBOLETO
FBOLETO.NOSSONUMERO
FBOLETO.STATUS = 0 (Em Aberto)
FLAN.IDLAN
SPSINSCRICAOAREAOFERTADA.IDLAN
SPSINSCRICAOAREAOFERTADA.IDPS
*/