
/*
Todos os candidatos TOP50
Idade
Bairro
Media de idade
Cursos mais procurados
Os dias mais procurados
*/


--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SPSUSUARIO';

SELECT 

    SPSUSUARIO.NOME                                                                 AS 'NOME',
    CONVERT(VARCHAR(12), SPSUSUARIO.DTNASCIMENTO, 103)                              AS 'DATA DE NASCIMENTO',
    YEAR(GETDATE()) - YEAR( SPSUSUARIO.DTNASCIMENTO)                                AS 'IDADE',
    (SELECT AVG(YEAR(GETDATE())-YEAR(SPSUSUARIO.DTNASCIMENTO)) FROM SPSUSUARIO)     AS 'MEDIA_IDADE',
    SPSUSUARIO.BAIRRO                                                               AS 'BAIRRO',
    CONVERT(VARCHAR(12), SPSINSCRICAOAREAOFERTADA.DATAINSCRICAO, 103)               AS 'DATA DE INSCRIÇÃO',
    SPSPROCESSOSELETIVO.NOME                                                        AS 'PROCESSO LETIVO',
    SPSAREAINTERESSE.NOME                                                           AS 'ÀREA DE INTERESSE'


FROM SPSUSUARIO

    INNER JOIN SPSINSCRICAOAREAOFERTADA ON
        SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
    INNER JOIN SPSPROCESSOSELETIVO ON 
        SPSPROCESSOSELETIVO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
	INNER JOIN SPSAREAOFERTADA ON
		SPSPROCESSOSELETIVO.IDPS = SPSAREAOFERTADA.IDPS
	AND SPSPROCESSOSELETIVO.CODCOLIGADA = SPSAREAOFERTADA.CODCOLIGADA
	INNER JOIN SPSAREAINTERESSE ON
		SPSAREAINTERESSE.IDAREAINTERESSE = SPSAREAOFERTADA.IDAREAINTERESSE
	INNER JOIN SPSOPCAOINSCRITO ON
		SPSAREAOFERTADA.IDAREAINTERESSE = SPSOPCAOINSCRITO.IDAREAINTERESSE
	AND SPSOPCAOINSCRITO.CODUSUARIOPS = SPSUSUARIO.CODUSUARIOPS
	


WHERE
    SPSPROCESSOSELETIVO.IDPS IN (222,223,224)
    
GROUP BY   
    SPSUSUARIO.DTNASCIMENTO,  SPSUSUARIO.BAIRRO, SPSINSCRICAOAREAOFERTADA.DATAINSCRICAO,SPSPROCESSOSELETIVO.NOME,
    SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS,SPSUSUARIO.CODUSUARIOPS,SPSUSUARIO.NOME,  SPSINSCRICAOAREAOFERTADA.IDPS, SPSAREAINTERESSE.NOME

ORDER BY 
    SPSINSCRICAOAREAOFERTADA.DATAINSCRICAO,SPSUSUARIO.NOME, SPSPROCESSOSELETIVO.NOME

SELECT * FROM SPSAREAOFERTADA