
SELECT DISTINCT 
	SPLETIVO.CODPERLET, 
	STURMADISC.CODTURMA, 
	STURMADISC.CODDISC, 
	SDISCIPLINA.NOME, 
	SDISCIPLINA.NUMCREDITOS, 
	(SDISCGRADE.NUMCREDITOSCOB/6) AS CREDFIN, 
	SSTATUS.DESCRICAO, 

	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA		=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA					=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC			=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=1) AS AP1,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA		=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA					=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=			SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=2) AS AP2,

	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA		=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA					=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC			=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=3) AS TDE1,

	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=		SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=					SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=			SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=4) AS TDE2,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=5) AS TDE3,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=6) AS TDE4,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=7) AS TDE5,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=8) AS TDE6,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=9) AS TDE7,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=10) AS TDE8,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=11) [Média Parcial],
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=12) [Avaliação Final],
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='N' AND CODETAPA=13) [Média Final],
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='F' AND CODETAPA=1) AS F1,

	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='F' AND CODETAPA=2) AS F2,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='F' AND CODETAPA=3) AS F3,

	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='F' AND CODETAPA=4) AS F4,

	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='F' AND CODETAPA=5) AS F5,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='F' AND CODETAPA=6) AS F6,
	
	(SELECT 
		NOTAFALTA 
	FROM SNOTAETAPA (NOLOCK)
	WHERE SNOTAETAPA.CODCOLIGADA=SMATRICULA.CODCOLIGADA
	AND SNOTAETAPA.RA=SMATRICULA.RA
	AND SNOTAETAPA.IDTURMADISC=SMATRICULA.IDTURMADISC
	AND TIPOETAPA='F' AND CODETAPA=7) AS F7

FROM SPLETIVO (NOLOCK)
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SMATRICULA (NOLOCK) ON
			SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
		AND SMATRICULA.RA = SMATRICPL.RA
	INNER JOIN STURMADISC (NOLOCK) ON
			STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
	INNER JOIN SDISCIPLINA (NOLOCK) ON
			SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SDISCGRADE (NOLOCK) ON
			SDISCGRADE.CODCOLIGADA = SDISCIPLINA.CODCOLIGADA
		AND SDISCGRADE.CODDISC = SDISCIPLINA.CODDISC

		/*AND SDISCGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO*/
	INNER JOIN SSTATUS (NOLOCK) ON
			SSTATUS.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND SSTATUS.CODSTATUS = SMATRICULA.CODSTATUS
WHERE SMATRICULA.CODCOLIGADA = :CODCOLIGADA
AND SMATRICULA.RA = :RA
AND SPLETIVO.CODPERLET='2022.1'
AND SDISCGRADE.NUMCREDITOSCOB IS NOT NULL
/*AND SMATRICULA.CODSTATUS = 19*/