
--FINREL0027.1.1 - Cópia de Contas a pagar - Fornecedor - Em Aberto
--             ##### CONSULTA #####
--FIN.000010.1.1 - Fornecedores com lançamento em aberto
SELECT DISTINCT
	FCFO.CODCFO,
	FCFO.NOMEFANTASIA, 
	FCFO.CGCCFO
FROM FLAN (NOLOCK)
	INNER JOIN FCFO (NOLOCK) ON
			FCFO.CODCFO = FLAN.CODCFO
	INNER JOIN FTDO (NOLOCK) ON
			FTDO.CODTDO = FLAN.CODTDO
WHERE FLAN.PAGREC = 2 
AND ((FLAN.STATUSLAN = 0) OR (FLAN.STATUSLAN = 1 AND FLAN.DATABAIXA >= FLAN.DATAVENCIMENTO))
AND FLAN.DATAVENCIMENTO BETWEEN :DATAINICIAL AND :DATAFINAL
AND UPPER(FCFO.NOMEFANTASIA) NOT IN ('PREFEITURA DE JUAZEIRO DO NORTE')

--FIN.000010.2 - Lançamentos em Aberto

SELECT
FLAN.IDLAN,
FLAN.NUMERODOCUMENTO,
FTDO.DESCRICAO TIPODOC,
FCFO.NOMEFANTASIA,
FLAN.DATAVENCIMENTO VENCIMENTO1,
FLAN.DATABAIXA,
CONVERT(VARCHAR(12), FLAN.DATAVENCIMENTO, 103) DATAVENCIMENTO,
FORMAT(FLAN.VALORORIGINAL, 'C', 'PT-BR'),
CONVERT(DECIMAL(10,2), FLAN.VALORORIGINAL) VALORAPAGAR,
CONVERT(VARCHAR(12), FLAN.DATACRIACAO, 103) DATACRIACAO,
FLAN.CODCXA
FROM FLAN (NOLOCK)
INNER JOIN FCFO (NOLOCK) ON
FCFO.CODCFO = FLAN.CODCFO
INNER JOIN FTDO (NOLOCK) ON
FTDO.CODTDO = FLAN.CODTDO

WHERE FLAN.PAGREC = 2
AND FLAN.CODCFO = :CODCFO1
AND FLAN.DATAVENCIMENTO BETWEEN :DATAINICIAL AND :DATAFINAL
AND ((FLAN.STATUSLAN = 0) OR (FLAN.STATUSLAN = 1 AND FLAN.DATABAIXA >= FLAN.DATAVENCIMENTO))


--##########################################################################################################################################--

--FINREL0018.2 - Cópia de Contas a pagar - Fornecedor - Em Aberto