 SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'STURMADISC';
 SELECT * FROM GCAMPOS WHERE TABELA = 'SMATRICULA';


/*  1 - Lista de matriculas   */

 SELECT RA FROM SALUNO;

/*  2 - Lista de matriculas de alunos matriculados em 2021.2 */

 SELECT 
 
 SALUNO.RA AS 'MATRICULA',
 SPLETIVO.CODPERLET  AS 'PERIODO LETIVO'
 
 FROM SALUNO 

 INNER JOIN SMATRICPL  ON
			SALUNO.RA = SMATRICPL.RA
 INNER JOIN SPLETIVO   ON
	        SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
 
 WHERE 
 SPLETIVO.CODPERLET IN ('2021.2');

/*  3 - matriculados com n�meros de matricula e nome em 2021.2 */

SELECT 

	UPPER(PPESSOA.NOME) AS 'NOME DO ALUNO', 
	SALUNO.RA           AS 'MATRICULA',   
	SPLETIVO.CODPERLET  AS 'PERIODO LETIVO'

FROM SALUNO 

	INNER JOIN PPESSOA   ON 
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SMATRICPL ON 
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN SPLETIVO  ON 
			SMATRICPL.IDPERLET = SPLETIVO.IDPERLET

WHERE
SPLETIVO.CODPERLET IN ('2021.2');
 


/* 4 - Matriculados com n�meros de matriculas, nome e curso em 2021.2. 
   5 - Matriculados com n�mero de matricula, nome, curso e disciplinas que est�o cursando em 2021.2*/

SELECT

	SMATRICPL.RA        AS 'Matricula',
	UPPER(PPESSOA.NOME) AS 'Nome',
	SCURSO.NOME         AS 'Curso',
	SPLETIVO.CODPERLET  AS 'Periodo letivo',
	SDISCIPLINA.NOME    AS 'Disciplinas',
	SSTATUS.DESCRICAO   AS 'Status_Disciplinas'

FROM SPLETIVO

	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SMATRICULA (NOLOCK) ON
			SMATRICULA.RA = SMATRICPL.RA
	INNER JOIN STURMADISC (NOLOCK) ON
			STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SDISCIPLINA (NOLOCK) ON 
		    SDISCIPLINA.CODDISC = STURMADISC.CODDISC
    INNER JOIN SSTATUS  (NOLOCK) ON
	        SSTATUS.CODSTATUS = SMATRICULA.CODSTATUS

WHERE
	SSTATUS.DESCRICAO = 'Cursando'
	AND SPLETIVO.CODPERLET IN ('2021.2');

