SELECT  
 AVG(YEAR(GETDATE()) - YEAR(SPSUSUARIO.DTNASCIMENTO)) [MEDIA DE IDADE], 
 SPSAREAINTERESSE.NOME  
 
FROM SPSUSUARIO 
 INNER JOIN SPSINSCRICAOAREAOFERTADA ON 
        SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS 
    INNER JOIN SPSPROCESSOSELETIVO ON  
        SPSPROCESSOSELETIVO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS 
 INNER JOIN SPSAREAOFERTADA ON 
  SPSPROCESSOSELETIVO.IDPS = SPSAREAOFERTADA.IDPS 
 AND SPSPROCESSOSELETIVO.CODCOLIGADA = SPSAREAOFERTADA.CODCOLIGADA 
 INNER JOIN SPSAREAINTERESSE ON 
  SPSAREAINTERESSE.IDAREAINTERESSE = SPSAREAOFERTADA.IDAREAINTERESSE 
 INNER JOIN SPSOPCAOINSCRITO ON 
  SPSAREAOFERTADA.IDAREAINTERESSE = SPSOPCAOINSCRITO.IDAREAINTERESSE 
 AND SPSAREAOFERTADA.IDPS = SPSOPCAOINSCRITO.IDPS 
 AND SPSOPCAOINSCRITO.CODUSUARIOPS = SPSUSUARIO.CODUSUARIOPS 
 
 WHERE SPSPROCESSOSELETIVO.IDPS = 224
  
 
 GROUP BY SPSAREAINTERESSE.NOME