-- SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SPSAREAOFERTADA';

SELECT DISTINCT

CASE
	    
		/*REMOVE NÚMEROS FIXOS DA CONSULTA*/
		WHEN 
				(LEN(TELEFONE2) = 8  AND SUBSTRING(TELEFONE2, 1, 1) BETWEEN 2 AND 5) 
			OR  (LEN(TELEFONE2) = 9  AND SUBSTRING(TELEFONE2, 2, 1) BETWEEN 2 AND 5) 
			OR  (LEN(TELEFONE2) = 10 AND SUBSTRING(TELEFONE2, 3, 1) BETWEEN 2 AND 5)
			OR  (LEN(TELEFONE2) = 11 AND SUBSTRING(TELEFONE2, 4, 1) BETWEEN 2 AND 5) 
		THEN NULL
		
		/*ADICIONA 9 APÓS O DDD*/
		WHEN 
				LEN(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', '')) = 10 
			OR LEN(TELEFONE2) = 10 
		THEN SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', ''), 1, 2) 
			 + '9' 
			 + SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 8)
		
		/*PROVAVELMENTE JÁ TEM O 9 APÓS O DDD ENTÃO RETORNA O PRÓPRIO NÚMERO*/
		WHEN 
				LEN(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', '')) > 10 
		THEN SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', ''), 1, 11)
		
		/*REMOVE NÚMEROS SEM DDD*/
		WHEN LEN(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', '')) < 10 
		  OR LEN(TELEFONE2) < 10 
		THEN NULL		

	END TELEFONE2,
	SPSINSCRICAOAREAOFERTADA.IDPS,
SMATRICPL.RA AS 'MATRICULA',
CASE 
		WHEN SMATRICPL.CODSTATUS = 125 THEN 'PRÉ-MATRICULADO - PS'
		WHEN SMATRICPL.CODSTATUS = 101 THEN 'MATRICULA WEB'
END AS 'STATUS' 

FROM SPSINSCRICAOAREAOFERTADA
    INNER JOIN SPSUSUARIO (NOLOCK) ON	
		SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
    INNER JOIN SPSOPCAOINSCRITO (NOLOCK) ON
		SPSOPCAOINSCRITO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
        AND SPSOPCAOINSCRITO.NUMEROINSCRICAO = SPSINSCRICAOAREAOFERTADA.NUMEROINSCRICAO
	LEFT JOIN SMATRICPL (NOLOCK) ON 
		SMATRICPL.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
		AND SMATRICPL.NUMEROINSCRICAO = SPSINSCRICAOAREAOFERTADA.NUMEROINSCRICAO
	

WHERE	
	SPSINSCRICAOAREAOFERTADA.IDPS IN (187,189,191,193,195,197,198,199,200,201,204,205,206,208,209,210,211,212,213,214,215,217,218,219,220,222,223,224)
	

