CASE
	    
		/*REMOVE NÚMEROS FIXOS DA CONSULTA*/
		WHEN 
				(LEN(TELEFONE2) = 8  AND SUBSTRING(TELEFONE2, 1, 1) BETWEEN 2 AND 5) 
			OR  (LEN(TELEFONE2) = 9  AND SUBSTRING(TELEFONE2, 2, 1) BETWEEN 2 AND 5) 
			OR  (LEN(TELEFONE2) = 10 AND SUBSTRING(TELEFONE2, 3, 1) BETWEEN 2 AND 5)
			OR  (LEN(TELEFONE2) = 11 AND SUBSTRING(TELEFONE2, 4, 1) BETWEEN 2 AND 5) 
		THEN NULL
		
		/*ADICIONA 9 APÓS O DDD*/
		WHEN 
				LEN(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', '')) = 10 
			OR LEN(TELEFONE2) = 10 
		THEN SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', ''), 1, 2) 
			 + '9' 
			 + SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 8)
		
		/*PROVAVELMENTE JÁ TEM O 9 APÓS O DDD ENTÃO RETORNA O PRÓPRIO NÚMERO*/
		WHEN 
				LEN(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', '')) > 10 
		THEN SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', ''), 1, 11)
		
		/*REMOVE NÚMEROS SEM DDD*/
		WHEN LEN(REPLACE(REPLACE(REPLACE(REPLACE(TELEFONE2, '(', ''), ')', ''), ' ', ''), '-', '')) < 10 
		  OR LEN(TELEFONE2) < 10 
		THEN NULL		

	END TELEFONE2,