SELECT 
	SALUNO.RA																[MATRICULA], 
	PPESSOA.NOME															[ALUNO], 
	SCURSO.NOME																[CURSO],
	CONVERT(INTEGER, SUM(SHISTORICO.CH))									[CH_CUMPRIDA], 
	CONVERT(INTEGER, SGRADE.CARGAHORARIA)									[CH_CURSO], 
	CONVERT(DECIMAL(10,2), (SUM(SHISTORICO.CH)/SGRADE.CARGAHORARIA)*100)	[PERCENTUAL_CONCLUIDO]
FROM SPLETIVO (NOLOCK)
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SHABILITACAOFILIAL.CODFILIAL = SMATRICPL.CODFILIAL
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SGRADE (NOLOCK) ON
			SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
		AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
		AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SHISTHABILITACAOALUNO (NOLOCK) ON
			SHISTHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SHISTHABILITACAOALUNO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
		AND SHISTHABILITACAOALUNO.RA = SMATRICPL.RA
		AND SHISTHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
	INNER JOIN SHISTORICO (NOLOCK) ON
			SHISTORICO.IDHABILITACAOFILIAL = SHISTHABILITACAOALUNO.IDHABILITACAOFILIAL
		AND SHISTORICO.RA = SHISTHABILITACAOALUNO.RA
	INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.RA = SHISTORICO.RA
		AND SALUNO.CODCOLIGADA = SHISTORICO.CODCOLIGADA
	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
WHERE SPLETIVO.CODCOLIGADA = 1
AND SPLETIVO.CODFILIAL = 1
AND SPLETIVO.CODPERLET = '2022.1'
AND SMATRICPL.CODSTATUS IN (110,111)
AND SCURSO.CODCURSO = '7'
AND SHISTORICO.CODSTATUS IN (2,20,108)
GROUP BY SALUNO.RA, PPESSOA.NOME, SGRADE.CARGAHORARIA