SELECT 

COUNT(RA)

FROM SPLETIVO (NOLOCK)
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET


 WHERE
 SMATRICPL.CODSTATUS IN (101)
 AND SPLETIVO.CODPERLET IN ('2022.1')