SELECT DISTINCT
	SCURSO.NOME	[CURSO], 
	SPERIODO.CODPERIODO,
	STURNO.NOME,
	--STURMADISC.CODTURMA, 
	SMODALIDADECURSO.DESCRICAO	[MODALIDADE],
	COUNT(SMATRICULA.RA)/(SELECT COUNT(TDISC.CODDISC) FROM STURMADISC TDISC WHERE TDISC.CODTURMA = STURMADISC.CODTURMA AND TDISC.IDPERLET = STURMADISC.IDPERLET)	[MÉDIA DE ALUNOS]
FROM SPLETIVO (NOLOCK)
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SMATRICULA (NOLOCK) ON
			SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
		AND SMATRICULA.RA = SMATRICPL.RA
	INNER JOIN STURMADISC (NOLOCK) ON
			STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
		AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SMODALIDADECURSO (NOLOCK) ON
			SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA
		AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO
	INNER JOIN SGRADE ON
			SGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
		AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
		AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
	INNER JOIN SDISCGRADE ON
			SDISCGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SDISCGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
		AND SDISCGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
		AND SDISCGRADE.CODDISC = STURMADISC.CODDISC
	INNER JOIN SPERIODO ON
			SPERIODO.CODCOLIGADA = SDISCGRADE.CODCOLIGADA
		AND SPERIODO.CODCURSO = SDISCGRADE.CODCURSO
		AND SPERIODO.CODGRADE = SDISCGRADE.CODGRADE
		AND SPERIODO.CODHABILITACAO = SDISCGRADE.CODHABILITACAO
		AND SPERIODO.CODPERIODO = SDISCGRADE.CODPERIODO
	INNER JOIN STURNO ON
			STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO
WHERE SPLETIVO.CODPERLET = '2022.1'
AND SMATRICULA.CODSTATUS IN (2,3,4,19,110)
AND SPERIODO.CODPERIODO <> 0
GROUP BY SCURSO.NOME, STURMADISC.CODTURMA, STURNO.NOME, SPERIODO.CODPERIODO, STURMADISC.IDPERLET, SMODALIDADECURSO.DESCRICAO
ORDER BY SCURSO.NOME, SMODALIDADECURSO.DESCRICAO