SELECT
	GFILIAL.NOMEFANTASIA,
	CONCAT('CNPJ:', GFILIAL.CGC)	CNPJ,
	CONCAT(DTIPORUA.DESCRICAO, ' ', GFILIAL.RUA, ' - ', GFILIAL.NUMERO, ' - ', GFILIAL.BAIRRO, ' - ', GFILIAL.CEP, ' - ', GFILIAL.CIDADE, '-', GFILIAL.ESTADO) ENDERECO,
	GIMAGEM.IMAGEM,
	CONCAT(
	CASE
		WHEN TIPOAUTORIZ = 0 THEN 'Decreto'		
		WHEN TIPOAUTORIZ = 1 THEN 'Portaria'
		WHEN TIPOAUTORIZ = 2 THEN 'Resolução'
		WHEN TIPOAUTORIZ = 3 THEN 'Ata'
	END, ' Ministerial de ',
	CASE
		WHEN ATOREGULATORIO = 1 THEN 'Credenciamento'
		WHEN ATOREGULATORIO = 2 THEN 'Recredenciamento'
	END, ' Nº ', NRAUTORIZ, ' de ', CONVERT(VARCHAR(12), DTAUTORIZ, 103), ', ', LOCALAUTORIZ, ' Nº ', NUMPUBLICACAO, ' Seção ', SECAOPUBLICACAO, ', p. ', PAGINAPUBLICACAO, ' de ', CONVERT(VARCHAR(12), DTPUBLICACAO, 103)) CREDENCIAMENTO,
	CONCAT(CASE 
				WHEN GFILIAL.CODFILIAL = 1 THEN 'Site: unifapce.edu.br '
				WHEN GFILIAL.CODFILIAL = 4 THEN 'Site: fapce.edu.br/medicinaararipina '
		   END, 'Telefone: (', GFILIAL.DDD, ') ', GFILIAL.TELEFONE)	TELEFONE,
	CASE
		WHEN GFILIAL.CODFILIAL = 1 THEN 'Juazeiro do Norte - CE'
		WHEN GFILIAL.CODFILIAL = 4 THEN 'Araripina - PE'
		WHEN GFILIAL.CODFILIAL = 2 THEN 'Fortaleza - CE'
	END	[CIDADE]
	
FROM GFILIAL (NOLOCK)
	INNER JOIN GIMAGEM (NOLOCK) ON
			GIMAGEM.ID = GFILIAL.IDIMAGEM
	INNER JOIN SAUTORIZACAOFILIAL (NOLOCK) ON
			SAUTORIZACAOFILIAL.CODFILIAL = GFILIAL.CODFILIAL
	INNER JOIN DTIPORUA (NOLOCK) ON
			DTIPORUA.CODIGO = GFILIAL.TIPORUA
WHERE GFILIAL.CODFILIAL = :CODFILIAL1