
SELECT DISTINCT
	SALUNO.RA						[MATRICULA], 
	PPESSOA.NOME					[ALUNO],
	PPESSOA.EMAIL                   [EMAIL],
	PPESSOA.TELEFONE2               [TELEFONE],
	SCURSO.NOME						[CURSO], 
	SMODALIDADECURSO.DESCRICAO		[MODALIDADE CURSO],
	SHISTORICO.CODDISC				[CÓDIGO DISCIPLINA], 
	SHISTORICO.CODPERLET            [PERIODO LETIVO],
	SHISTORICO.NOMEDISC         	[DISCIPLINA],
	SDISCGRADE.CODPERIODO			[PERIODO],
	SHISTORICO.STATUS               [STATUS]

FROM SHABILITACAOALUNO (NOLOCK)
	INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
		AND SALUNO.RA = SHABILITACAOALUNO.RA
	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.RA = SHABILITACAOALUNO.RA
		AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
	INNER JOIN SPLETIVO (NOLOCK) ON
				SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
			AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
			AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SHISTORICO (NOLOCK) ON
			SHISTORICO.RA = SHABILITACAOALUNO.RA
		AND SHISTORICO.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
	INNER JOIN SMODALIDADECURSO (NOLOCK) ON
			SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA
		AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO
	INNER JOIN SGRADE (NOLOCK) ON
			SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
		AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
		AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
	INNER JOIN SPERIODO (NOLOCK) ON
			SPERIODO.CODCOLIGADA = SGRADE.CODCOLIGADA
		AND SPERIODO.CODGRADE = SGRADE.CODGRADE
		AND SPERIODO.CODCURSO = SGRADE.CODCURSO
		AND SPERIODO.CODHABILITACAO = SGRADE.CODHABILITACAO
	INNER JOIN SDISCGRADE (NOLOCK) ON
			SDISCGRADE.CODCOLIGADA = SPERIODO.CODCOLIGADA
		AND SDISCGRADE.CODGRADE = SPERIODO.CODGRADE
		AND SDISCGRADE.CODCURSO = SPERIODO.CODCURSO
		AND SDISCGRADE.CODHABILITACAO = SPERIODO.CODHABILITACAO
		AND SDISCGRADE.CODPERIODO = SPERIODO.CODPERIODO
		AND SDISCGRADE.CODDISC = SHISTORICO.CODDISC
			
WHERE
		 SHABILITACAOALUNO.CODSTATUS = 19 /*STATUS NO CURSO CURSANDO*/
	AND  SMATRICPL.CODSTATUS IN (12, 101, 111)
	AND  SPLETIVO.CODPERLET = '2022.1'
ORDER BY SCURSO.NOME, SMODALIDADECURSO.DESCRICAO, PPESSOA.NOME, SHISTORICO.NOMEDISC