
SELECT DISTINCT
	FCFO.CODCFO,
	FCFO.NOMEFANTASIA, 
	FCFO.CGCCFO
FROM FLAN (NOLOCK)
	INNER JOIN FCFO (NOLOCK) ON
			FCFO.CODCFO = FLAN.CODCFO
	INNER JOIN FTDO (NOLOCK) ON
			FTDO.CODTDO = FLAN.CODTDO
WHERE FLAN.PAGREC = 2 
AND STATUSLAN = 0
AND FLAN.DATAVENCIMENTO BETWEEN :DATAINICIAL AND :DATAFINAL
AND UPPER(FCFO.NOMEFANTASIA) NOT IN ('PREFEITURA DE JUAZEIRO DO NORTE')