
SELECT 
	FLAN.IDLAN, 
	FLAN.NUMERODOCUMENTO,
	FTDO.DESCRICAO TIPODOC,
	FCFO.NOMEFANTASIA, 
	FLAN.DATAVENCIMENTO VENCIMENTO1,
	CONVERT(VARCHAR(12), FLAN.DATAVENCIMENTO, 103) DATAVENCIMENTO, 
	CONVERT(DECIMAL(10,2), FLAN.VALORORIGINAL - FLAN.VALORBAIXADO) VALORAPAGAR,
	CONVERT(VARCHAR(12), FLAN.DATACRIACAO, 103) DATACRIACAO,
	FLAN.CODCXA
FROM FLAN (NOLOCK)
	INNER JOIN FCFO (NOLOCK) ON
			FCFO.CODCFO = FLAN.CODCFO
	INNER JOIN FTDO (NOLOCK) ON
			FTDO.CODTDO = FLAN.CODTDO
WHERE FLAN.PAGREC = 2 
AND FLAN.STATUSLAN = 0
AND FLAN.CODCFO = :CODCFO1
AND FLAN.DATAVENCIMENTO BETWEEN :DATAINICIAL AND :DATAFINAL