IF(:HIST_COMPLETO_S = 'S')

/**********DISCIPLINAS DA GRADE NORMAL CONCLUIDAS*******/

SELECT
	DISTINCT
	/*SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL,*/
	SHISTDISCCONCLUIDAS.RA,
	SHISTDISCCONCLUIDAS.PLETIVO																						[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SHISTDISCCONCLUIDAS.CODDISC																						[CODDISC],
	SHISTDISCCONCLUIDAS.DISCIPLINA																					[NOMEDISC],
	CONVERT(INTEGER, SHISTDISCCONCLUIDAS.CH)																		[CH],
	/*CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)																			[AV1],
	CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)																			[AV2],
	CONVERT(DECIMAL(10,2), ((CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)) + (CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)))/2) [M],
	CONVERT(DECIMAL(10,2), AVF.NOTAFALTA)																			[AVF],*/
	CONVERT(DECIMAL(10,2), MF.NOTAFALTA)																			[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SHISTDISCCONCLUIDAS.CH) - CONVERT(NUMERIC(15), FALTA.NOTAFALTA))*100 / 
    CONVERT(NUMERIC(15),SHISTDISCCONCLUIDAS.CH)),100)																[FREQUENCIA], 
	SHISTDISCCONCLUIDAS.STATUS																						[STATUS],
	SHISTDISCCONCLUIDAS.GREQUIV
FROM SHISTDISCCONCLUIDAS (NOLOCK)
	/******AVP1**********/
	/*INNER JOIN SNOTAETAPA AVP1 (NOLOCK) ON
			AVP1.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND AVP1.RA = SHISTDISCCONCLUIDAS.RA
		AND AVP1.TIPOETAPA = 'N'
		AND AVP1.CODETAPA = 1*/
	/******AVP2**********/
	/*INNER JOIN SNOTAETAPA AVP2 (NOLOCK) ON
			AVP2.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND AVP2.RA = SHISTDISCCONCLUIDAS.RA
		AND AVP2.TIPOETAPA = 'N'
		AND AVP2.CODETAPA = 2*/
	/******AVF**********/
	/*FULL OUTER JOIN SNOTAETAPA AVF (NOLOCK) ON
			AVF.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND AVF.RA = SHISTDISCCONCLUIDAS.RA
		AND AVF.TIPOETAPA = 'N'
		AND AVF.CODETAPA = 4*/
	/******MF**********/
	FULL OUTER JOIN SETAPAS ETAPAFALTA (NOLOCK) ON
			ETAPAFALTA.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND ETAPAFALTA.ETAPAFINAL = 'S'
		AND ETAPAFALTA.TIPOETAPA = 'F'
		
	FULL OUTER JOIN SETAPAS ETAPANOTA (NOLOCK) ON
			ETAPANOTA.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND ETAPANOTA.ETAPAFINAL = 'S'
		AND ETAPANOTA.TIPOETAPA = 'N'
		
	FULL OUTER JOIN SNOTAETAPA MF (NOLOCK) ON
			MF.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND MF.RA = SHISTDISCCONCLUIDAS.RA
		AND MF.TIPOETAPA = 'N'
		AND MF.CODETAPA = ETAPANOTA.CODETAPA
		/*AND MF.CODETAPA = 5*/
	/******FALTAS**********/
	FULL OUTER JOIN SNOTAETAPA FALTA (NOLOCK) ON
			FALTA.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND FALTA.RA = SHISTDISCCONCLUIDAS.RA
		AND FALTA.TIPOETAPA = 'F'
		AND FALTA.CODETAPA = ETAPAFALTA.CODETAPA
		/*AND FALTA.CODETAPA = 7*/
	
WHERE SHISTDISCCONCLUIDAS.RA = :P_RA
AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL
AND SHISTDISCCONCLUIDAS.CODCOLIGADA = :P_CODCOLIGADA
AND SHISTDISCCONCLUIDAS.IDPERLET IS NOT NULL
AND SHISTDISCCONCLUIDAS.CODSTATUS <> 20

UNION ALL

/*********DISCIPLINAS EQUIVALENTES A DISCIPLINAS DA GRADE NORMAL CONCLUIDAS****/
SELECT
	DISTINCT
	SHISTDISCEQUIVCONCLUIDAS.RA,
	SHISTDISCEQUIVCONCLUIDAS.PLETIVO																				[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SHISTDISCEQUIVCONCLUIDAS.CODDISC																				[CODDISC],
	SHISTDISCEQUIVCONCLUIDAS.DISCIPLINA																				[NOMEDISC],
	CONVERT(INTEGER, SHISTDISCEQUIVCONCLUIDAS.CH)																	[CH],
	CONVERT(DECIMAL(10,2), SHISTDISCEQUIVCONCLUIDAS.NOTA)															[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SHISTDISCCONCLUIDAS.CH) - CONVERT(NUMERIC(15), SHISTDISCEQUIVCONCLUIDAS.FALTAS))*100 / 
    CONVERT(NUMERIC(15),SHISTDISCCONCLUIDAS.CH)),100)																[FREQUENCIA], 
	SHISTDISCEQUIVCONCLUIDAS.STATUS																					[STATUS],
	SHISTDISCEQUIVCONCLUIDAS.GREQUIV
FROM SHISTDISCEQUIVCONCLUIDAS (NOLOCK)
	
	INNER JOIN SHISTDISCCONCLUIDAS (NOLOCK) ON
			SHISTDISCCONCLUIDAS.RA = SHISTDISCEQUIVCONCLUIDAS.RA
		AND SHISTDISCCONCLUIDAS.GREQUIV = SHISTDISCEQUIVCONCLUIDAS.GREQUIV
		AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL

WHERE SHISTDISCEQUIVCONCLUIDAS.RA = :P_RA
AND SHISTDISCCONCLUIDAS.CODCOLIGADA = :P_CODCOLIGADA
AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL IN (SELECT IDHABILITACAOFILIAL FROM SHABILITACAOALUNO WHERE SHABILITACAOALUNO.RA = :P_RA)/*= :P_IDHABILITACAOFILIAL*/

UNION ALL

/**********DISCIPLINAS APROVEITADAS*******/
SELECT DISTINCT
	/*SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL,*/
	SHISTDISCCONCLUIDAS.RA,
	SHISTDISCCONCLUIDAS.PLETIVO																						[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SHISTDISCCONCLUIDAS.CODDISC																						[CODDISC],
	SHISTDISCCONCLUIDAS.DISCIPLINA																					[NOMEDISC],
	CONVERT(INTEGER, SHISTDISCCONCLUIDAS.CH)																		[CH],
	/*NULL																											[AV1],
	NULL																											[AV2],
	NULL																											[M],
	NULL																											[AVF],*/
	NULL																											[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SHISTDISCCONCLUIDAS.CH) - CONVERT(NUMERIC(15), FALTA.NOTAFALTA))*100 / 
    CONVERT(NUMERIC(15),SHISTDISCCONCLUIDAS.CH)),100)																[FREQUENCIA], 
	SHISTDISCCONCLUIDAS.STATUS																						[STATUS],
	SHISTDISCCONCLUIDAS.GREQUIV
FROM SHISTDISCCONCLUIDAS (NOLOCK)
	/******FALTAS**********/
	FULL OUTER JOIN SETAPAS ETAPAFALTA (NOLOCK) ON
			ETAPAFALTA.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND ETAPAFALTA.ETAPAFINAL = 'S'
		AND ETAPAFALTA.TIPOETAPA = 'F'
		
	FULL OUTER JOIN SNOTAETAPA FALTA (NOLOCK) ON
			FALTA.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND FALTA.RA = SHISTDISCCONCLUIDAS.RA
		AND FALTA.TIPOETAPA = 'F'
		AND FALTA.CODETAPA = ETAPAFALTA.CODETAPA
WHERE SHISTDISCCONCLUIDAS.RA = :P_RA
AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL
AND SHISTDISCCONCLUIDAS.CODCOLIGADA = :P_CODCOLIGADA
AND SHISTDISCCONCLUIDAS.CODSTATUS = 20

UNION ALL

/**DISCIPLINAS REPROVADAS**/
SELECT DISTINCT
	/*SHISTORICO.IDHABILITACAOFILIAL,*/
	SHISTORICO.RA,
	SPLETIVO.CODPERLET																									[CODPERLET],
	NULL																												[STATUS_PLETIVO],
	SHISTORICO.CODDISC																									[CODDISC],
	SHISTORICO.NOMEDISC																									[NOMEDISC],
	CONVERT(INTEGER, SHISTORICO.CH)																						[CH],
	/*CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)																				[AV1],
	CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)																				[AV2],
	CONVERT(DECIMAL(10,2), ((CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)) + (CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)))/2)		[M],
	CONVERT(DECIMAL(10,2), AVF.NOTAFALTA)																				[AVF],*/
	CONVERT(DECIMAL(10,2), MF.NOTAFALTA)																				[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SHISTORICO.CH) - CONVERT(NUMERIC(15), SHISTORICO.FALTAFINAL))*100 / 
    CONVERT(NUMERIC(15),SHISTORICO.CH)),100)																			[FREQUENCIA], 
	SHISTORICO.STATUS																									[STATUS],
	NULL																												[GREQUIV]
FROM SHISTORICO (NOLOCK)
	INNER JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.CODCOLIGADA = SHISTORICO.CODCOLIGADA
		AND SPLETIVO.IDPERLET = SHISTORICO.IDPERLET
	/******AVP1**********/
	/*INNER JOIN SNOTAETAPA AVP1 (NOLOCK) ON
			AVP1.IDTURMADISC = SHISTORICO.IDTURMADISC
		AND AVP1.RA = SHISTORICO.RA
		AND AVP1.TIPOETAPA = 'N'
		AND AVP1.CODETAPA = 1*/
	/******AVP2**********/
	/*INNER JOIN SNOTAETAPA AVP2 (NOLOCK) ON
			AVP2.IDTURMADISC = SHISTORICO.IDTURMADISC
		AND AVP2.RA = SHISTORICO.RA
		AND AVP2.TIPOETAPA = 'N'
		AND AVP2.CODETAPA = 2*/
	/******AVF**********/
	/*FULL OUTER JOIN SNOTAETAPA AVF (NOLOCK) ON
			AVF.IDTURMADISC = SHISTORICO.IDTURMADISC
		AND AVF.RA = SHISTORICO.RA
		AND AVF.TIPOETAPA = 'N'
		AND AVF.CODETAPA = 4*/
	/******MF**********/
		
	FULL OUTER JOIN SETAPAS ETAPANOTA (NOLOCK) ON
			ETAPANOTA.IDTURMADISC = SHISTORICO.IDTURMADISC
		AND ETAPANOTA.ETAPAFINAL = 'S'
		AND ETAPANOTA.TIPOETAPA = 'N'
	
	FULL OUTER JOIN SNOTAETAPA MF (NOLOCK) ON
			MF.IDTURMADISC = SHISTORICO.IDTURMADISC
		AND MF.RA = SHISTORICO.RA
		AND MF.TIPOETAPA = 'N'
		AND MF.CODETAPA = ETAPANOTA.CODETAPA
WHERE SHISTORICO.RA = :P_RA
AND SHISTORICO.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL
AND SHISTORICO.CODCOLIGADA = :P_CODCOLIGADA
AND SHISTORICO.CODSTATUS IN (3,4)

UNION ALL

/*DISCIPLINAS EM CURSO*/
SELECT
	/*SMATRICULA.IDHABILITACAOFILIAL,*/
	SMATRICULA.RA,
	SPLETIVO.CODPERLET																								[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SDISCIPLINA.CODDISC																								[CODDISC],
	SDISCIPLINA.NOME																								[NOMEDISC],
	CONVERT(INTEGER, SDISCIPLINA.CH)																				[CH],
	/*CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)																			[AV1],
	CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)																			[AV2],
	CONVERT(DECIMAL(10,2), ((CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)) + (CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)))/2) [M],
	CONVERT(DECIMAL(10,2), AVF.NOTAFALTA)																			[AVF],*/
	CONVERT(DECIMAL(10,2), MF.NOTAFALTA)																			[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SDISCIPLINA.CH) - CONVERT(NUMERIC(15), FALTA.NOTAFALTA))*100 / 
    CONVERT(NUMERIC(15),SDISCIPLINA.CH)),100)																		[FREQUENCIA], 
	SSTATUS.DESCRICAO																								[STATUS],
	NULL																											[GREQUIV]
FROM SMATRICULA 
	/******AVP1**********/
	/*FULL OUTER JOIN SNOTAETAPA AVP1 (NOLOCK) ON
			AVP1.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND AVP1.RA = SMATRICULA.RA
		AND AVP1.TIPOETAPA = 'N'
		AND AVP1.CODETAPA = 1*/
	/******AVP2**********/
	/*FULL OUTER JOIN SNOTAETAPA AVP2 (NOLOCK) ON
			AVP2.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND AVP2.RA = SMATRICULA.RA
		AND AVP2.TIPOETAPA = 'N'
		AND AVP2.CODETAPA = 2*/
	/******AVF**********/
	/*FULL OUTER JOIN SNOTAETAPA AVF (NOLOCK) ON
			AVF.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND AVF.RA = SMATRICULA.RA
		AND AVF.TIPOETAPA = 'N'
		AND AVF.CODETAPA = 4*/
	/******MF**********/
	FULL OUTER JOIN SETAPAS ETAPAFALTA (NOLOCK) ON
			ETAPAFALTA.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND ETAPAFALTA.ETAPAFINAL = 'S'
		AND ETAPAFALTA.TIPOETAPA = 'F'
		
	FULL OUTER JOIN SETAPAS ETAPANOTA (NOLOCK) ON
			ETAPANOTA.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND ETAPANOTA.ETAPAFINAL = 'S'
		AND ETAPANOTA.TIPOETAPA = 'N'
	
	FULL OUTER JOIN SNOTAETAPA MF (NOLOCK) ON
			MF.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND MF.RA = SMATRICULA.RA
		AND MF.TIPOETAPA = 'N'
		AND MF.CODETAPA = ETAPANOTA.CODETAPA
	/******FALTAS**********/
	FULL OUTER JOIN SNOTAETAPA FALTA (NOLOCK) ON
			FALTA.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND FALTA.RA = SMATRICULA.RA
		AND FALTA.TIPOETAPA = 'F'
		AND FALTA.CODETAPA = ETAPAFALTA.CODETAPA
	INNER JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND SPLETIVO.IDPERLET = SMATRICULA.IDPERLET
	INNER JOIN STURMADISC (NOLOCK) ON
			STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
	INNER JOIN SDISCIPLINA (NOLOCK) ON
			SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	INNER JOIN SSTATUS (NOLOCK) ON
			SSTATUS.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND SSTATUS.CODSTATUS = SMATRICULA.CODSTATUS
WHERE SMATRICULA.RA = :P_RA
AND SMATRICULA.CODSTATUS  = 19
AND SMATRICULA.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL

UNION ALL

/****DISCIPLINAS TRANCADAS****/
SELECT
	/*SMATRICULA.IDHABILITACAOFILIAL,*/
	SMATRICULA.RA,
	SPLETIVO.CODPERLET																								[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SDISCIPLINA.CODDISC																								[CODDISC],
	SDISCIPLINA.NOME																								[NOMEDISC],
	CONVERT(INTEGER, SDISCIPLINA.CH)																				[CH],
	/*null [AV1],
	null [AV2],
	null [M],
	null [AVF],*/
	null [MF],
    null [FREQUENCIA], 
	SSTATUS.DESCRICAO																								[STATUS],
	NULL																											[GREQUIV]
FROM SMATRICULA 
	/******AVP1**********/
	/*FULL OUTER JOIN SNOTAETAPA AVP1 (NOLOCK) ON
			AVP1.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND AVP1.RA = SMATRICULA.RA
		AND AVP1.TIPOETAPA = 'N'
		AND AVP1.CODETAPA = 1*/
	/******AVP2**********/
	/*FULL OUTER JOIN SNOTAETAPA AVP2 (NOLOCK) ON
			AVP2.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND AVP2.RA = SMATRICULA.RA
		AND AVP2.TIPOETAPA = 'N'
		AND AVP2.CODETAPA = 2*/
	/******AVF**********/
	/*FULL OUTER JOIN SNOTAETAPA AVF (NOLOCK) ON
			AVF.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND AVF.RA = SMATRICULA.RA
		AND AVF.TIPOETAPA = 'N'
		AND AVF.CODETAPA = 4*/
	/******MF**********/
	FULL OUTER JOIN SETAPAS ETAPAFALTA (NOLOCK) ON
			ETAPAFALTA.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND ETAPAFALTA.ETAPAFINAL = 'S'
		AND ETAPAFALTA.TIPOETAPA = 'F'
		
	FULL OUTER JOIN SETAPAS ETAPANOTA (NOLOCK) ON
			ETAPANOTA.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND ETAPANOTA.ETAPAFINAL = 'S'
		AND ETAPANOTA.TIPOETAPA = 'N'
	
	FULL OUTER JOIN SNOTAETAPA MF (NOLOCK) ON
			MF.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND MF.RA = SMATRICULA.RA
		AND MF.TIPOETAPA = 'N'
		AND MF.CODETAPA = ETAPANOTA.CODETAPA
	/******FALTAS**********/
	FULL OUTER JOIN SNOTAETAPA FALTA (NOLOCK) ON
			FALTA.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND FALTA.RA = SMATRICULA.RA
		AND FALTA.TIPOETAPA = 'F'
		AND FALTA.CODETAPA = ETAPAFALTA.CODETAPA
	INNER JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND SPLETIVO.IDPERLET = SMATRICULA.IDPERLET
	INNER JOIN STURMADISC (NOLOCK) ON
			STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
	INNER JOIN SDISCIPLINA (NOLOCK) ON
			SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	INNER JOIN SSTATUS (NOLOCK) ON
			SSTATUS.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND SSTATUS.CODSTATUS = SMATRICULA.CODSTATUS
WHERE SMATRICULA.RA = :P_RA
AND SMATRICULA.CODSTATUS  = 14
AND SMATRICULA.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL

UNION ALL

/**DISCIPLINAS OPTATIVAS ELETIVAS**/
SELECT
	DISTINCT
	/*SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL,*/
	SHISTDISCOPTELETIVAS.RA,
	SHISTDISCOPTELETIVAS.PLETIVO																						[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SHISTDISCOPTELETIVAS.CODDISC																						[CODDISC],
	SHISTDISCOPTELETIVAS.DISCIPLINA																					[NOMEDISC],
	CONVERT(INTEGER, SHISTDISCOPTELETIVAS.CH)																		[CH],
	/*CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)																			[AV1],
	CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)																			[AV2],
	CONVERT(DECIMAL(10,2), ((CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)) + (CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)))/2) [M],
	CONVERT(DECIMAL(10,2), AVF.NOTAFALTA)																			[AVF],*/
	CONVERT(DECIMAL(10,2), MF.NOTAFALTA)																			[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SHISTDISCOPTELETIVAS.CH) - CONVERT(NUMERIC(15), FALTA.NOTAFALTA))*100 / 
    CONVERT(NUMERIC(15),SHISTDISCOPTELETIVAS.CH)),100)																[FREQUENCIA], 
	SHISTDISCOPTELETIVAS.STATUS																						[STATUS],
	SHISTDISCOPTELETIVAS.GREQUIV
FROM SHISTDISCOPTELETIVAS (NOLOCK)
	/******AVP1**********/
	/*INNER JOIN SNOTAETAPA AVP1 (NOLOCK) ON
			AVP1.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND AVP1.RA = SHISTDISCOPTELETIVAS.RA
		AND AVP1.TIPOETAPA = 'N'
		AND AVP1.CODETAPA = 1*/
	/******AVP2**********/
	/*INNER JOIN SNOTAETAPA AVP2 (NOLOCK) ON
			AVP2.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND AVP2.RA = SHISTDISCOPTELETIVAS.RA
		AND AVP2.TIPOETAPA = 'N'
		AND AVP2.CODETAPA = 2*/
	/******AVF**********/
	/*FULL OUTER JOIN SNOTAETAPA AVF (NOLOCK) ON
			AVF.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND AVF.RA = SHISTDISCOPTELETIVAS.RA
		AND AVF.TIPOETAPA = 'N'
		AND AVF.CODETAPA = 4*/
	/******MF**********/
	FULL OUTER JOIN SETAPAS ETAPAFALTA (NOLOCK) ON
			ETAPAFALTA.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND ETAPAFALTA.ETAPAFINAL = 'S'
		AND ETAPAFALTA.TIPOETAPA = 'F'
		
	FULL OUTER JOIN SETAPAS ETAPANOTA (NOLOCK) ON
			ETAPANOTA.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND ETAPANOTA.ETAPAFINAL = 'S'
		AND ETAPANOTA.TIPOETAPA = 'N'
	
	FULL OUTER JOIN SNOTAETAPA MF (NOLOCK) ON
			MF.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND MF.RA = SHISTDISCOPTELETIVAS.RA
		AND MF.TIPOETAPA = 'N'
		AND MF.CODETAPA = ETAPANOTA.CODETAPA
	/******FALTAS**********/
	FULL OUTER JOIN SNOTAETAPA FALTA (NOLOCK) ON
			FALTA.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND FALTA.RA = SHISTDISCOPTELETIVAS.RA
		AND FALTA.TIPOETAPA = 'F'
		AND FALTA.CODETAPA = ETAPAFALTA.CODETAPA
WHERE SHISTDISCOPTELETIVAS.RA = :P_RA
AND SHISTDISCOPTELETIVAS.STATUS <> 'Cursando'
AND SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL
AND SHISTDISCOPTELETIVAS.CODCOLIGADA = :P_CODCOLIGADA

UNION ALL

/**********PERÍODOS LETIVOS*******/
SELECT 
	DISTINCT
	/*NULL							[IDHABILITACAOFILIAL],*/
	NULL							[RA],
	SPLETIVO.CODPERLET				[CODPERLET],
	CASE
		WHEN SSTATUS.DESCRICAO IS NULL THEN 'Cursado'
		ELSE SSTATUS.DESCRICAO
	END 							[STATUS_PLETIVO],
	NULL							[CODDISC],
	NULL							[NOMEDISC],
	NULL							[CH],
	/*NULL							[AV1],
	NULL							[AV2],
	NULL							[M],
	NULL							[AVF],*/
	NULL							[MF],
	NULL							[FALTAFINAL],
	NULL							[STATUS],
	NULL							[GREQUIV]
FROM SHABILITACAOALUNO (NOLOCK)
	FULL OUTER JOIN SHISTDISCCONCLUIDAS (NOLOCK) ON
			SHISTDISCCONCLUIDAS.RA = SHABILITACAOALUNO.RA
		AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
	FULL OUTER JOIN SHISTDISCEQUIVCONCLUIDAS (NOLOCK) ON
			SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
		AND SHISTDISCEQUIVCONCLUIDAS.RA = SHISTDISCCONCLUIDAS.RA
		AND SHISTDISCEQUIVCONCLUIDAS.GREQUIV = SHISTDISCCONCLUIDAS.GREQUIV
	INNER JOIN SHISTORICO (NOLOCK) ON
			SHISTORICO.RA = SHABILITACAOALUNO.RA
		AND SHISTORICO.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.RA = SHABILITACAOALUNO.RA
			/*ESTAVA COMENTADO ABAIXO*/
		AND (SMATRICPL.IDPERLET = (CASE 
								  	WHEN 
								  		SHISTDISCCONCLUIDAS.GREQUIV IS NOT NULL THEN SHISTDISCEQUIVCONCLUIDAS.IDPERLET
									ELSE SHISTORICO.IDPERLET 
								END) 
		OR SMATRICPL.IDPERLET IN (SELECT IDPERLET FROM SMATRICPL WHERE RA = :P_RA AND IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL))
		AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
	INNER JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
	INNER JOIN SSTATUS (NOLOCK) ON
			SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
WHERE SHABILITACAOALUNO.RA = :P_RA
AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL
AND SHABILITACAOALUNO.CODCOLIGADA = :P_CODCOLIGADA
AND SMATRICPL.CODSTATUS NOT IN (17,105,106)
ORDER BY CODPERLET, STATUS_PLETIVO DESC

ELSE IF(:HIST_COMPLETO_S = 'N')

/**********DISCIPLINAS DA GRADE NORMAL CONCLUIDAS*******/
SELECT
	DISTINCT
	/*SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL,*/
	SHISTDISCCONCLUIDAS.RA,
	SHISTDISCCONCLUIDAS.PLETIVO																						[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SHISTDISCCONCLUIDAS.CODDISC																						[CODDISC],
	SHISTDISCCONCLUIDAS.DISCIPLINA																					[NOMEDISC],
	CONVERT(INTEGER, SHISTDISCCONCLUIDAS.CH)																		[CH],
	/*CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)																			[AV1],
	CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)																			[AV2],
	CONVERT(DECIMAL(10,2), ((CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)) + (CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)))/2) [M],
	CONVERT(DECIMAL(10,2), AVF.NOTAFALTA)																			[AVF],*/
	CONVERT(DECIMAL(10,2), MF.NOTAFALTA)																			[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SHISTDISCCONCLUIDAS.CH) - CONVERT(NUMERIC(15), FALTA.NOTAFALTA))*100 / 
    CONVERT(NUMERIC(15),SHISTDISCCONCLUIDAS.CH)),100)																[FREQUENCIA], 
	SHISTDISCCONCLUIDAS.STATUS																						[STATUS],
	SHISTDISCCONCLUIDAS.GREQUIV
FROM SHISTDISCCONCLUIDAS (NOLOCK)
	/******AVP1**********/
	/*INNER JOIN SNOTAETAPA AVP1 (NOLOCK) ON
			AVP1.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND AVP1.RA = SHISTDISCCONCLUIDAS.RA
		AND AVP1.TIPOETAPA = 'N'
		AND AVP1.CODETAPA = 1*/
	/******AVP2**********/
	/*INNER JOIN SNOTAETAPA AVP2 (NOLOCK) ON
			AVP2.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND AVP2.RA = SHISTDISCCONCLUIDAS.RA
		AND AVP2.TIPOETAPA = 'N'
		AND AVP2.CODETAPA = 2*/
	/******AVF**********/
	/*FULL OUTER JOIN SNOTAETAPA AVF (NOLOCK) ON
			AVF.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND AVF.RA = SHISTDISCCONCLUIDAS.RA
		AND AVF.TIPOETAPA = 'N'
		AND AVF.CODETAPA = 4*/
	/******MF**********/
	FULL OUTER JOIN SETAPAS ETAPAFALTA (NOLOCK) ON
			ETAPAFALTA.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND ETAPAFALTA.ETAPAFINAL = 'S'
		AND ETAPAFALTA.TIPOETAPA = 'F'
		
	FULL OUTER JOIN SETAPAS ETAPANOTA (NOLOCK) ON
			ETAPANOTA.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND ETAPANOTA.ETAPAFINAL = 'S'
		AND ETAPANOTA.TIPOETAPA = 'N'
	
	INNER JOIN SNOTAETAPA MF (NOLOCK) ON
			MF.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND MF.RA = SHISTDISCCONCLUIDAS.RA
		AND MF.TIPOETAPA = 'N'
		AND MF.CODETAPA = ETAPANOTA.CODETAPA
	/******FALTAS**********/
	FULL OUTER JOIN SNOTAETAPA FALTA (NOLOCK) ON
			FALTA.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND FALTA.RA = SHISTDISCCONCLUIDAS.RA
		AND FALTA.TIPOETAPA = 'F'
		AND FALTA.CODETAPA = ETAPAFALTA.CODETAPA
WHERE SHISTDISCCONCLUIDAS.RA = :P_RA
AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL
AND SHISTDISCCONCLUIDAS.CODCOLIGADA = :P_CODCOLIGADA
AND SHISTDISCCONCLUIDAS.IDPERLET IS NOT NULL
AND SHISTDISCCONCLUIDAS.CODSTATUS <> 20
AND SHISTDISCCONCLUIDAS.CODDISC NOT IN (SELECT CODDISC FROM SHISTDISCEQUIVCONCLUIDAS WHERE RA = :P_RA AND IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL)

UNION ALL

/*********DISCIPLINAS EQUIVALENTES A DISCIPLINAS DA GRADE NORMAL CONCLUIDAS****/
SELECT
	DISTINCT
	SHISTDISCEQUIVCONCLUIDAS.RA,
	SHISTDISCEQUIVCONCLUIDAS.PLETIVO																				[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SHISTDISCEQUIVCONCLUIDAS.CODDISC																				[CODDISC],
	SHISTDISCEQUIVCONCLUIDAS.DISCIPLINA																				[NOMEDISC],
	CONVERT(INTEGER, SHISTDISCEQUIVCONCLUIDAS.CH)																	[CH],
	CONVERT(DECIMAL(10,2), SHISTDISCEQUIVCONCLUIDAS.NOTA)															[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SHISTDISCCONCLUIDAS.CH) - CONVERT(NUMERIC(15), SHISTDISCEQUIVCONCLUIDAS.FALTAS))*100 / 
    CONVERT(NUMERIC(15),SHISTDISCCONCLUIDAS.CH)),100)																[FREQUENCIA], 
	SHISTDISCEQUIVCONCLUIDAS.STATUS																					[STATUS],
	SHISTDISCEQUIVCONCLUIDAS.GREQUIV
FROM SHISTDISCEQUIVCONCLUIDAS (NOLOCK)
	
	INNER JOIN SHISTDISCCONCLUIDAS (NOLOCK) ON
			SHISTDISCCONCLUIDAS.RA = SHISTDISCEQUIVCONCLUIDAS.RA
		AND SHISTDISCCONCLUIDAS.GREQUIV = SHISTDISCEQUIVCONCLUIDAS.GREQUIV
		AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL

WHERE SHISTDISCEQUIVCONCLUIDAS.RA = :P_RA
AND SHISTDISCCONCLUIDAS.CODCOLIGADA = :P_CODCOLIGADA
AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL IN (SELECT DISTINCT IDHABILITACAOFILIAL FROM SHABILITACAOALUNO WHERE SHABILITACAOALUNO.RA = :P_RA)/*= :P_IDHABILITACAOFILIAL*/

UNION ALL

/**********DISCIPLINAS APROVEITADAS*******/
SELECT DISTINCT
	/*SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL,*/
	SHISTDISCCONCLUIDAS.RA,
	SHISTDISCCONCLUIDAS.PLETIVO																						[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SHISTDISCCONCLUIDAS.CODDISC																						[CODDISC],
	SHISTDISCCONCLUIDAS.DISCIPLINA																					[NOMEDISC],
	CONVERT(INTEGER, SHISTDISCCONCLUIDAS.CH)																		[CH],
	/*NULL																											[AV1],
	NULL																											[AV2],
	NULL																											[M],
	NULL																											[AVF],*/
	NULL																											[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SHISTDISCCONCLUIDAS.CH) - CONVERT(NUMERIC(15), FALTA.NOTAFALTA))*100 / 
    CONVERT(NUMERIC(15),SHISTDISCCONCLUIDAS.CH)),100)																[FREQUENCIA], 
	SHISTDISCCONCLUIDAS.STATUS																						[STATUS],
	SHISTDISCCONCLUIDAS.GREQUIV
FROM SHISTDISCCONCLUIDAS (NOLOCK)
	/******FALTAS**********/
	FULL OUTER JOIN SETAPAS ETAPAFALTA (NOLOCK) ON
			ETAPAFALTA.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND ETAPAFALTA.ETAPAFINAL = 'S'
		AND ETAPAFALTA.TIPOETAPA = 'F'
	
	FULL OUTER JOIN SNOTAETAPA FALTA (NOLOCK) ON
			FALTA.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
		AND FALTA.RA = SHISTDISCCONCLUIDAS.RA
		AND FALTA.TIPOETAPA = 'F'
		AND FALTA.CODETAPA = ETAPAFALTA.CODETAPA
WHERE SHISTDISCCONCLUIDAS.RA = :P_RA
AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL
AND SHISTDISCCONCLUIDAS.CODCOLIGADA = :P_CODCOLIGADA
AND SHISTDISCCONCLUIDAS.CODSTATUS = 20

UNION ALL

/*DISCIPLINAS EM CURSO*/
SELECT DISTINCT
	/*SMATRICULA.IDHABILITACAOFILIAL,*/
	SMATRICULA.RA,
	SPLETIVO.CODPERLET																								[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SDISCIPLINA.CODDISC																								[CODDISC],
	SDISCIPLINA.NOME																								[NOMEDISC],
	CONVERT(INTEGER, SDISCIPLINA.CH)																				[CH],
	/*CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)																			[AV1],
	CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)																			[AV2],
	CONVERT(DECIMAL(10,2), ((CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)) + (CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)))/2) [M],
	CONVERT(DECIMAL(10,2), AVF.NOTAFALTA)																			[AVF],*/
	CONVERT(DECIMAL(10,2), MF.NOTAFALTA)																			[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SDISCIPLINA.CH) - CONVERT(NUMERIC(15), FALTA.NOTAFALTA))*100 / 
    CONVERT(NUMERIC(15),SDISCIPLINA.CH)),100)																		[FREQUENCIA], 
	SSTATUS.DESCRICAO																								[STATUS],
	NULL																											[GREQUIV]
FROM SMATRICULA 
	/******AVP1**********/
	/*FULL OUTER JOIN SNOTAETAPA AVP1 (NOLOCK) ON
			AVP1.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND AVP1.RA = SMATRICULA.RA
		AND AVP1.TIPOETAPA = 'N'
		AND AVP1.CODETAPA = 1*/
	/******AVP2**********/
	/*FULL OUTER JOIN SNOTAETAPA AVP2 (NOLOCK) ON
			AVP2.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND AVP2.RA = SMATRICULA.RA
		AND AVP2.TIPOETAPA = 'N'
		AND AVP2.CODETAPA = 2*/
	/******AVF**********/
	/*FULL OUTER JOIN SNOTAETAPA AVF (NOLOCK) ON
			AVF.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND AVF.RA = SMATRICULA.RA
		AND AVF.TIPOETAPA = 'N'
		AND AVF.CODETAPA = 4*/
	/******MF**********/
	FULL OUTER JOIN SETAPAS ETAPAFALTA (NOLOCK) ON
			ETAPAFALTA.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND ETAPAFALTA.ETAPAFINAL = 'S'
		AND ETAPAFALTA.TIPOETAPA = 'F'
		
	FULL OUTER JOIN SETAPAS ETAPANOTA (NOLOCK) ON
			ETAPANOTA.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND ETAPANOTA.ETAPAFINAL = 'S'
		AND ETAPANOTA.TIPOETAPA = 'N'
	
	FULL OUTER JOIN SNOTAETAPA MF (NOLOCK) ON
			MF.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND MF.RA = SMATRICULA.RA
		AND MF.TIPOETAPA = 'N'
		AND MF.CODETAPA = ETAPANOTA.CODETAPA
	/******FALTAS**********/
	FULL OUTER JOIN SNOTAETAPA FALTA (NOLOCK) ON
			FALTA.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND FALTA.RA = SMATRICULA.RA
		AND FALTA.TIPOETAPA = 'F'
		AND FALTA.CODETAPA = ETAPAFALTA.CODETAPA
	INNER JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND SPLETIVO.IDPERLET = SMATRICULA.IDPERLET
	INNER JOIN STURMADISC (NOLOCK) ON
			STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
		AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
	INNER JOIN SDISCIPLINA (NOLOCK) ON
			SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	INNER JOIN SSTATUS (NOLOCK) ON
			SSTATUS.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND SSTATUS.CODSTATUS = SMATRICULA.CODSTATUS
WHERE SMATRICULA.RA = :P_RA
AND SMATRICULA.CODSTATUS  = 19
AND SMATRICULA.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL

UNION ALL

/**DISCIPLINAS OPTATIVAS ELETIVAS**/
SELECT
	DISTINCT
	/*SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL,*/
	SHISTDISCOPTELETIVAS.RA,
	SHISTDISCOPTELETIVAS.PLETIVO																					[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SHISTDISCOPTELETIVAS.CODDISC																					[CODDISC],
	SHISTDISCOPTELETIVAS.DISCIPLINA																					[NOMEDISC],
	CONVERT(INTEGER, SHISTDISCOPTELETIVAS.CH)																		[CH],
	/*CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)																			[AV1],
	CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)																			[AV2],
	CONVERT(DECIMAL(10,2), ((CONVERT(DECIMAL(10,2), AVP1.NOTAFALTA)) + (CONVERT(DECIMAL(10,2), AVP2.NOTAFALTA)))/2) [M],
	CONVERT(DECIMAL(10,2), AVF.NOTAFALTA)																			[AVF],*/
	CONVERT(DECIMAL(10,2), MF.NOTAFALTA)																			[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SHISTDISCOPTELETIVAS.CH) - CONVERT(NUMERIC(15), FALTA.NOTAFALTA))*100 / 
    CONVERT(NUMERIC(15),SHISTDISCOPTELETIVAS.CH)),100)																[FREQUENCIA], 
	SHISTDISCOPTELETIVAS.STATUS																						[STATUS],
	SHISTDISCOPTELETIVAS.GREQUIV
FROM SHISTDISCOPTELETIVAS (NOLOCK)
	/******AVP1**********/
	/*INNER JOIN SNOTAETAPA AVP1 (NOLOCK) ON
			AVP1.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND AVP1.RA = SHISTDISCOPTELETIVAS.RA
		AND AVP1.TIPOETAPA = 'N'
		AND AVP1.CODETAPA = 1*/
	/******AVP2**********/
	/*INNER JOIN SNOTAETAPA AVP2 (NOLOCK) ON
			AVP2.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND AVP2.RA = SHISTDISCOPTELETIVAS.RA
		AND AVP2.TIPOETAPA = 'N'
		AND AVP2.CODETAPA = 2*/
	/******AVF**********/
	/*FULL OUTER JOIN SNOTAETAPA AVF (NOLOCK) ON
			AVF.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND AVF.RA = SHISTDISCOPTELETIVAS.RA
		AND AVF.TIPOETAPA = 'N'
		AND AVF.CODETAPA = 4*/
	/******MF**********/
	FULL OUTER JOIN SETAPAS ETAPAFALTA (NOLOCK) ON
			ETAPAFALTA.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND ETAPAFALTA.ETAPAFINAL = 'S'
		AND ETAPAFALTA.TIPOETAPA = 'F'
		
	FULL OUTER JOIN SETAPAS ETAPANOTA (NOLOCK) ON
			ETAPANOTA.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND ETAPANOTA.ETAPAFINAL = 'S'
		AND ETAPANOTA.TIPOETAPA = 'N'
	
	FULL OUTER JOIN SNOTAETAPA MF (NOLOCK) ON
			MF.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND MF.RA = SHISTDISCOPTELETIVAS.RA
		AND MF.TIPOETAPA = 'N'
		AND MF.CODETAPA = ETAPANOTA.CODETAPA
	/******FALTAS**********/
	FULL OUTER JOIN SNOTAETAPA FALTA (NOLOCK) ON
			FALTA.IDTURMADISC = SHISTDISCOPTELETIVAS.IDTURMADISC
		AND FALTA.RA = SHISTDISCOPTELETIVAS.RA
		AND FALTA.TIPOETAPA = 'F'
		AND FALTA.CODETAPA = ETAPAFALTA.CODETAPA
WHERE SHISTDISCOPTELETIVAS.RA = :P_RA
AND SHISTDISCOPTELETIVAS.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL
AND SHISTDISCOPTELETIVAS.STATUS IS NOT NULL
AND SHISTDISCOPTELETIVAS.CODCOLIGADA = :P_CODCOLIGADA
AND SHISTDISCOPTELETIVAS.CODSTATUSRES = 2

UNION ALL

/**********PERÍODOS LETIVOS*******/
SELECT 
	DISTINCT
	/*NULL							[IDHABILITACAOFILIAL],*/
	NULL							[RA],
	SPLETIVO.CODPERLET				[CODPERLET],
	CASE
		WHEN SSTATUS.DESCRICAO IS NULL THEN 'Cursado'
		ELSE SSTATUS.DESCRICAO
	END 							[STATUS_PLETIVO],
	NULL							[CODDISC],
	NULL							[NOMEDISC],
	NULL							[CH],
	/*NULL							[AV1],
	NULL							[AV2],
	NULL							[M],
	NULL							[AVF],*/
	NULL							[MF],
	NULL							[FALTAFINAL],
	NULL							[STATUS],
	NULL							[GREQUIV]
FROM SHABILITACAOALUNO (NOLOCK)
	FULL OUTER JOIN SHISTDISCCONCLUIDAS (NOLOCK) ON
			SHISTDISCCONCLUIDAS.RA = SHABILITACAOALUNO.RA
		AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
	/*FULL OUTER JOIN SHISTDISCEQUIVCONCLUIDAS (NOLOCK) ON
			SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
		AND SHISTDISCEQUIVCONCLUIDAS.RA = SHISTDISCCONCLUIDAS.RA
		AND SHISTDISCEQUIVCONCLUIDAS.GREQUIV = SHISTDISCCONCLUIDAS.GREQUIV*/
	INNER JOIN SHISTORICO (NOLOCK) ON
			SHISTORICO.RA = SHABILITACAOALUNO.RA
		AND SHISTORICO.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.RA = SHABILITACAOALUNO.RA
		AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
		/*AND (SMATRICPL.IDPERLET = (CASE 
								  	WHEN 
								  		SHISTDISCCONCLUIDAS.GREQUIV IS NOT NULL THEN SHISTDISCEQUIVCONCLUIDAS.IDPERLET
									ELSE SHISTORICO.IDPERLET 
								END)
		OR SMATRICPL.IDPERLET IN (SELECT IDPERLET FROM SMATRICPL WHERE RA = :P_RA AND IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL))*/
	INNER JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
	INNER JOIN SSTATUS (NOLOCK) ON
			SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
WHERE SHABILITACAOALUNO.RA = :P_RA
AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = :P_IDHABILITACAOFILIAL
AND SHABILITACAOALUNO.CODCOLIGADA = :P_CODCOLIGADA
AND SHISTORICO.CODSTATUS IN (2,19)
/*AND SMATRICPL.CODSTATUS NOT IN (17,105,106)*/
ORDER BY CODPERLET, STATUS_PLETIVO DESC