 
SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SHISTHABILITACAOALUNO';

select  * from SHISTDISCCONCLUIDAS;
SELECT TOP 50 * FROM SHABILITACAOALUNO;
SELECT  * FROM SHISTDISCEQUIVCONCLUIDAS;
SHOSTORICO.STATUS

SHISTDISCPENDENTES
SHISTHABILITACAOALUNO
CODCOLIGADA,IDHABILITACAOFILIAL,RA
CODCOLIGADA,IDHABILITACAOFILIAL,RA

SELECT * FROM SHISTORICO WHERE SHISTORICO.RA = 2018210116

SELECT * FROM SHISTDISCEQUIVCONCLUIDAS WHERE SHISTDISCEQUIVCONCLUIDAS.RA = 2018210116

