
/*********DISCIPLINAS EQUIVALENTES A DISCIPLINAS DA GRADE NORMAL CONCLUIDAS****/
SELECT
	DISTINCT
	SHISTDISCEQUIVCONCLUIDAS.RA,
	SHISTDISCEQUIVCONCLUIDAS.PLETIVO																				[CODPERLET],
	NULL																											[STATUS_PLETIVO],
	SHISTDISCEQUIVCONCLUIDAS.CODDISC																				[CODDISC],
	SHISTDISCEQUIVCONCLUIDAS.DISCIPLINA																				[NOMEDISC],
	CONVERT(INTEGER, SHISTDISCEQUIVCONCLUIDAS.CH)																	[CH],
	CONVERT(DECIMAL(10,2), SHISTDISCEQUIVCONCLUIDAS.NOTA)															[MF],
	ISNULL(CONVERT(NUMERIC(15),(CONVERT(NUMERIC(15), SHISTDISCCONCLUIDAS.CH) - CONVERT(NUMERIC(15), SHISTDISCEQUIVCONCLUIDAS.FALTAS))*100 / 
    CONVERT(NUMERIC(15),SHISTDISCCONCLUIDAS.CH)),100)																[FREQUENCIA], 
	SHISTDISCEQUIVCONCLUIDAS.STATUS																					[STATUS],
	SHISTDISCEQUIVCONCLUIDAS.GREQUIV
FROM SHISTDISCEQUIVCONCLUIDAS (NOLOCK)
	
	INNER JOIN SHISTDISCCONCLUIDAS (NOLOCK) ON
			SHISTDISCCONCLUIDAS.RA = SHISTDISCEQUIVCONCLUIDAS.RA
		AND SHISTDISCCONCLUIDAS.GREQUIV = SHISTDISCEQUIVCONCLUIDAS.GREQUIV
		AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL

WHERE SHISTDISCEQUIVCONCLUIDAS.RA = 2018210116
AND SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL IN (SELECT DISTINCT IDHABILITACAOFILIAL FROM SHABILITACAOALUNO WHERE SHABILITACAOALUNO.RA = 2018210116)/*= :P_IDHABILITACAOFILIAL*/
