
SELECT
	UPPER(PPESSOA.NOME)			[ALUNO],
	SMATRICPL.RA				[MATRICULA],
	SCURSO.NOME					[CURSO],
	SPLETIVO.CODPERLET			[PERIODO_LETIVO],
	SMATRICPL.CODSTATUS			[STATUS],
	PPESSOA.EMAIL				[EMAIL],
	PPESSOA.TELEFONE2			[TELEFONE]

FROM
	SMATRICPL
	FULL OUTER JOIN SMATRICULA ON
			SMATRICULA.RA = SMATRICPL.RA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
	INNER JOIN SPLETIVO ON
			SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO

WHERE 
		SMATRICPL.IDPERLET = 168
	AND SMATRICPL.CODSTATUS = 101
	AND SMATRICULA.IDTURMADISC IS NULL