SELECT DISTINCT
	SMATRICPL.RA				[MATRICULA],
	UPPER(PPESSOA.NOME)			[ALUNO],
	SCURSO.NOME					[CURSO],
	SCONTRATO.CODCONTRATO		[CONTRATO],
	FLAN.IDLAN					[IDLAN],
	SPARCELA.PARCELA			[PARCELA],
	FLAN.VALORBAIXADO			[VALORBAIXADO]


FROM SMATRICPL
	INNER JOIN SCONTRATO ON
			SCONTRATO.RA = SMATRICPL.RA
		AND SCONTRATO.IDPERLET = SMATRICPL.IDPERLET
		AND SCONTRATO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		AND SCONTRATO.TIPOCONTRATO = 'P'
		AND SCONTRATO.IDPERLET = 167
	INNER JOIN SPARCELA ON
			SPARCELA.CODCONTRATO = SCONTRATO.CODCONTRATO
	INNER JOIN SLAN ON
			SLAN.IDPARCELA = SPARCELA.IDPARCELA
	INNER JOIN FLAN ON
			FLAN.IDLAN = SLAN.IDLAN
		AND FLAN.STATUSLAN = 1
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
			

WHERE
		SMATRICPL.CODSTATUS = 15


ORDER BY	
	[ALUNO]
