SELECT 
	SALUNO.RA,
	UPPER(PPESSOA.NOME)									[ALUNO], 
	SCURSO.NOME											[CURSO],
	STURNO.NOME											[TURNO],
	SSTATUS.DESCRICAO									[STATUS],
	SPLETIVO.CODPERLET									[PERIODO_LETIVO],
	CONVERT(VARCHAR(12), SMATRICPL.DTMATRICULA, 103)	[DATA_MATRICULA],
	LOWER(PPESSOA.EMAIL)								[EMAIL],
	PPESSOA.TELEFONE1,
	PPESSOA.TELEFONE2
	/*
	-- Tratamento da saída de números de telefone
	CASE
		WHEN PPESSOA.TELEFONE1 IS NULL THEN 'N/A'
		WHEN PPESSOA.TELEFONE1 = ' ' THEN 'N/A'
	END AS												[TELEFONE1],
	CASE
		WHEN PPESSOA.TELEFONE2 LIKE '[0-9]%' THEN '(' + SUBSTRING(PPESSOA.TELEFONE2, 1, 2)+ ') ' + SUBSTRING(PPESSOA.TELEFONE2, 3, 9) 
			ELSE PPESSOA.TELEFONE2
	END AS												[TELEFONE2] */

FROM SPLETIVO (NOLOCK)
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SSTATUS (NOLOCK) ON
			SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN STURNO (NOLOCK) ON
			STURNO.CODTURNO=SHABILITACAOFILIAL.CODTURNO

WHERE
		SMATRICPL.PERIODO = 1											-- Alunos Ingressantes 
	AND SMATRICPL.CODTIPOMAT NOT IN (35, 43)							-- 35 = Rematricula ; 43 = Mudança de matriz
	and SPLETIVO.CODPERLET = '2021.1'									
	--AND SMATRICPL.DTMATRICULA = CONVERT(VARCHAR(12), getdate(), 103)	-- Apenas data de hoje

ORDER BY
	[ALUNO]
	-- CONVERT(DATETIME, SMATRICPL.DTMATRICULA, 103) 