SELECT
	PPESSOA.CIDADE,
	COUNT(PPESSOA.CIDADE) AS TOTAL

FROM SHABILITACAOALUNO
	INNER JOIN SHABILITACAOFILIAL ON
		SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
	INNER JOIN SALUNO ON
		SALUNO.RA = SHABILITACAOALUNO.RA
	INNER JOIN PPESSOA ON
		PPESSOA.CODIGO = SALUNO.CODPESSOA

WHERE 
		SHABILITACAOALUNO.CODSTATUS = 19
	AND SHABILITACAOFILIAL.CODFILIAL = 1

GROUP BY
	PPESSOA.CIDADE

ORDER BY 
	PPESSOA.CIDADE