SELECT
	SMATRICULA.RA       AS  'MATRICULA',
	UPPER(PPESSOA.NOME)	AS	'ALUNO',
	SPLETIVO.CODPERLET  AS  'PERIODO LETIVO',
	SDISCIPLINA.CODDISC AS  'CODIGO',
	SDISCIPLINA.NOME	AS	'DISCIPLINA',
	S1.DESCRICAO		AS	'STATUS'

FROM SMATRICULA
	INNER JOIN SPLETIVO ON
			SPLETIVO.IDPERLET = SMATRICULA.IDPERLET
	INNER JOIN SSTATUS S1 ON
			S1.CODSTATUS = SMATRICULA.CODSTATUS
	INNER JOIN SMATRICPL ON
			SMATRICPL.RA = SMATRICULA.RA
		AND SMATRICPL.IDPERLET = SMATRICULA.IDPERLET
		AND SMATRICPL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
	INNER JOIN SSTATUS S2 ON
			S2.CODSTATUS = SMATRICPL.CODSTATUS
	INNER JOIN STURMADISC ON
			STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SDISCIPLINA ON
			SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA

WHERE
		SPLETIVO.CODPERLET = '2021.1'
	AND SMATRICPL.CODSTATUS IN (12, 101, 111)

ORDER BY
	[ALUNO]