SELECT DISTINCT

	SALUNO.RA,
	UPPER(PPESSOA.NOME) AS 'ALUNO',
	SSTATUS.DESCRICAO AS 'STATUS',
	SPLETIVO.CODPERLET


FROM SMATRICPL
	INNER JOIN SPLETIVO ON
			SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SSTATUS ON
			SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS

WHERE
		SMATRICPL.CODFILIAL = 4
	AND SPLETIVO.CODPERLET = '2021.2'

ORDER BY UPPER(PPESSOA.NOME), SALUNO.RA, SPLETIVO.CODPERLET, SSTATUS.DESCRICAO
