SELECT DISTINCT
	SMATRICPL.RA		 as	'MATRICULA',
	UPPER(PPESSOA.NOME)	 as	'ALUNO',
	spletivo.CODPERLET		[PERIODO_LETIVO],
	sstatus.DESCRICAO		[STATUS],
	SCURSO.NOME				[CURSO],
	SGRADE.DESCRICAO		[GRADE],
	STURMADISC.CODTURMA		[TURMA],
	sturmadisc.CODDISC		[COD_DISCIPLINA],
	SDISCIPLINA.NOME		[DISCIPLINA],
	LOWER(PPESSOA.EMAIL)	[EMAIL],
	PPESSOA.TELEFONE1		[TELEFONE1],
	PPESSOA.TELEFONE2		[TELEFONE2]

FROM
	SPLETIVO
	INNER JOIN SMATRICPL ON
			SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SMATRICULA ON
			SMATRICULA.RA = SMATRICPL.RA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SGRADE ON
			SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
		AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
		AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
	INNER JOIN STURMADISC ON
			STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SDISCIPLINA ON
			SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	INNER JOIN SSTATUS ON
			SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA

WHERE 
		STURMADISC.CODDISC LIKE 'ead214'
	AND SPLETIVO.CODPERLET = '2021.1'
	AND SSTATUS.CODSTATUS IN (12, 101, 111)

ORDER BY 
	[ALUNO];