select DISTINCT
	FLAN.IDLAN,
	FBOLETO.IDBOLETO,
	FBOLETO.VALOR,
	FBOLETO.NOSSONUMERO

FROM
	SPSINSCRICAOAREAOFERTADA
	INNER JOIN FLAN ON 
			FLAN.IDLAN = SPSINSCRICAOAREAOFERTADA.IDLAN
	INNER JOIN FLANBOLETO ON
			FLANBOLETO.IDLAN = FLAN.IDLAN
	INNER JOIN FBOLETO ON
			FBOLETO.IDBOLETO = FLANBOLETO.IDBOLETO

WHERE 
		SPSINSCRICAOAREAOFERTADA.STATUS = 0 -- INSCRITO (PENDENTE DE PAGAMENTO)
	AND FLAN.STATUSLAN = 0 -- EM ABERTO
	AND FBOLETO.STATUS = 0 -- EM ABERTO 
	AND SPSINSCRICAOAREAOFERTADA.IDPS IN (184, 186) -- 184: TRADICIONAL , 186: BOLSAS
