/*
Status Lançamento:
1: Quitado
0: Em aberto
2: Cancelado
*/

SELECT
	SPSINSCRICAOAREAOFERTADA.NUMEROINSCRICAO,
	SPSUSUARIO.NOME,
	SPSUSUARIO.CPF, 
	FBOLETO.VALOR,
	TFORMAPAGTO.CODFORMAPAGTO,
	TFFORMAPAGTO.DESCFORMAPAGTO,
	FLANBAIXA.VALORBAIXA

FROM
	SPSINSCRICAOAREAOFERTADA
	INNER JOIN SPSUSUARIO ON
			SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
	INNER JOIN FLAN ON 
			FLAN.IDLAN = SPSINSCRICAOAREAOFERTADA.IDLAN
	INNER JOIN FLANBOLETO ON
			FLANBOLETO.IDLAN = FLAN.IDLAN
	INNER JOIN FBOLETO ON
			FBOLETO.IDBOLETO = FLANBOLETO.IDBOLETO
	INNER JOIN FLANBAIXA ON
			FLANBAIXA.IDLAN = FLAN.IDLAN
		AND FLANBAIXA.DATACANCELBAIXA IS NULL
	INNER JOIN TFORMAPAGTO ON
			TFORMAPAGTO.IDFORMAPAGTO = FLANBAIXA.IDFORMAPAGTO
	INNER JOIN TFFORMAPAGTO ON
			TFFORMAPAGTO.CODFORMAPAGTO = TFORMAPAGTO.CODFORMAPAGTO

WHERE
	SPSINSCRICAOAREAOFERTADA.STATUS IN (0, 1)
	AND FLAN.STATUSLAN = 1
	AND FBOLETO.STATUS = 1
	AND SPSINSCRICAOAREAOFERTADA.IDPS IN (184, 185, 186)
	AND FBOLETO.VALOR IN (300, 200)
	AND (FLANBAIXA.VALORBAIXA > 0 OR TFFORMAPAGTO.IDFORMAPAGTO = 26)

ORDER BY
	SPSUSUARIO.NOME
