SELECT 
	SMATRICPL.RA										[MATRICULA],
	UPPER(PPESSOA.NOME)									[ALUNO],
	SCURSO.NOME											[CURSO],
	SBOLSAALUNO.CODCONTRATO								[CONTRATO],
	SBOLSA.NOME											[BOLSA],
	CONVERT(DECIMAL(10,2), SBOLSAALUNO.DESCONTO)		[PERCENTUAL],
	CASE
		WHEN SBOLSAALUNO.DTINICIO IS NULL THEN
			CONVERT(VARCHAR(2), SBOLSAALUNO.PARCELAINICIAL) ELSE 
			CONVERT(VARCHAR(12), SBOLSAALUNO.DTINICIO, 103)
		END	AS					[INICIAL],
	CASE
		WHEN SBOLSAALUNO.DTFIM IS NULL THEN
		CONVERT(VARCHAR(2), SBOLSAALUNO.PARCELAFINAL) ELSE
		CONVERT(VARCHAR(12), SBOLSAALUNO.DTFIM, 103)
		END	AS					[FINAL]
		-- contrato assinado + tipo P
FROM SPLETIVO
	INNER JOIN SMATRICPL ON
			SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SBOLSAALUNO ON
			SBOLSAALUNO.RA = SMATRICPL.RA
		AND SBOLSAALUNO.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SBOLSA ON
			SBOLSA.CODBOLSA = SBOLSAALUNO.CODBOLSA

WHERE 
	SPLETIVO.IDPERLET = 167

ORDER BY
	[ALUNO],
	[CONTRATO]
