SELECT
	SPSUSUARIO.NOME,
	SPSINSCRICAOAREAOFERTADA.IDPS,
	SPSINSCRICAOAREAOFERTADA.NUMEROINSCRICAO,
	SPSINSCRICAOAREAOFERTADA.ENEMNUMINSCRICAO,
	SPSINSCRICAOAREAOFERTADA.ENEMANOREFERENCIA,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTAHUMANAS,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTALINGUAGEM,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTAMATEMATICA,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTANATUREZA,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTAREDACAO,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTAOBJETIVA

FROM SPSINSCRICAOAREAOFERTADA
	INNER JOIN SPSUSUARIO ON
			SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS

WHERE
		((SPSINSCRICAOAREAOFERTADA.ENEMNUMINSCRICAO IS NULL OR SPSINSCRICAOAREAOFERTADA.ENEMNUMINSCRICAO = '')
	OR SPSINSCRICAOAREAOFERTADA.ENEMANOREFERENCIA IS NULL
	OR SPSINSCRICAOAREAOFERTADA.ENEMNOTAHUMANAS IS NULL
	OR SPSINSCRICAOAREAOFERTADA.ENEMNOTALINGUAGEM IS NULL
	OR SPSINSCRICAOAREAOFERTADA.ENEMNOTAMATEMATICA IS NULL
	OR SPSINSCRICAOAREAOFERTADA.ENEMNOTANATUREZA IS NULL
	OR SPSINSCRICAOAREAOFERTADA.ENEMNOTAREDACAO IS NULL
	OR SPSINSCRICAOAREAOFERTADA.ENEMNOTAOBJETIVA IS NULL)
	AND SPSINSCRICAOAREAOFERTADA.IDPS IN (189, 198, 206)