/*
Dados da Empresa:
	- Nome (SEMPRESA.NOME ou SEMPRESA.NOMEFANTASIA)
	- Endereço (SEMPRESA.RUA, NUMERO, COMPLEMENTO, BAIRRO, GMUNICIPIO.NOMEMUNICIPIO, GMUNICIPIO.CODETDMUNICIPIO)
	- CNPJ (SEMPRESA.CNPJ)
	- Responsável Legal (SEMPRESAFUNCIONARIO.NOME)

*/

SELECT
	SEMPRESA.CATEGORIA,
	SEMPRESA.NOME,
	SEMPRESA.NOMEFANTASIA,
	SEMPRESA.RUA,
	SEMPRESA.NUMERO,
	SEMPRESA.BAIRRO,
	GMUNICIPIO.NOMEMUNICIPIO	[MUNICIPIO],
	GMUNICIPIO.CODETDMUNICIPIO	[ESTADO],
	SEMPRESA.CNPJ,
	SUPERVISOR.NOME				[SUPERVISOR],
	FUNCIONARIOS.NOME			[RESPONSAVEL],
	SUPERVISOR.CPF				[CPF_SUPERVISOR],
	SUPERVISOR.TELEFONE			[TEL_SUPERVISOR],
	SUPERVISOR.EMAIL			[EMAIL_SUPERVISOR],
	SUPERVISOR.CARGO			[CARGO_SUPERVISOR]

FROM
	SESTAGIOCONTRATO
	INNER JOIN SPLETIVO ON
			SPLETIVO.IDPERLET = SESTAGIOCONTRATO.IDPERLET
	INNER JOIN SEMPRESA ON
			SEMPRESA.IDEMPRESA = SESTAGIOCONTRATO.IDEMPRESA
	INNER JOIN SEMPRESAFUNCIONARIO SUPERVISOR ON
			SUPERVISOR.IDFUNCIONARIO = SESTAGIOCONTRATO.IDFUNCIONARIO
	LEFT JOIN SEMPRESAFUNCIONARIO FUNCIONARIOS ON
			FUNCIONARIOS.IDEMPRESA = SUPERVISOR.IDEMPRESA
		AND FUNCIONARIOS.FUNCAO IN (3, 4)
	INNER JOIN GMUNICIPIO ON
			GMUNICIPIO.CODMUNICIPIO = SEMPRESA.CODMUNICIPIO
		AND GMUNICIPIO.CODETDMUNICIPIO = SEMPRESA.ESTADO


