/*
Dados do Estágio
	- Carga horária Semanal
		SESTAGIOCONTRATO(CHSEMANAL)
	- Hora Inicial
		SESTAGIOCONTRATO(HRINICIALEXPEDIENTE)
	- Hora Final 
		SESTAGIOCONTRATO(HRFINALEXPEDIENTE)
	- Nome do Supervisor
		SESTAGIOCONTRATO(IDFUNCIONARIO) -> SEMPRESAFUNCIONARIO(NOME)
	- Atividades a serem realizadas
		SESTAGIOCONTRATO(OBJETIVO)
	- Datas de Inicio e Fim do estágio
		SESTAGIOCONTRATO(DTINICIOESTAGIO) e SESTAGIOCONTRATO(DTFINALESTAGIO)

*/

SELECT 
	PPESSOA.NOME	[ORIENTADOR],
	CONVERT(INT, SESTAGIOCONTRATO.CHSEMANAL)	[CHSEMANAL],
	SESTAGIOCONTRATO.HRINICIALEXPEDIENTE [HRINICIO],
	SESTAGIOCONTRATO.HRFINALEXPEDIENTE	 [HRFIM],
	CONVERT(VARCHAR(12), SESTAGIOCONTRATO.DTINICIOESTAGIO, 103)		[DTINICIOESTAGIO],
	CONVERT(VARCHAR(12), SESTAGIOCONTRATO.DTFINALESTAGIO, 103)		[DTFINALESTAGIO],
	DATEDIFF(HOUR, CAST(SESTAGIOCONTRATO.HRINICIALEXPEDIENTE AS TIME), CAST(SESTAGIOCONTRATO.HRFINALEXPEDIENTE AS TIME)) AS [CHDIARIO],
	SESTAGIOCONTRATO.OBJETIVO,
	SESTAGIOCONTRATO.VLRBOLSA,
	SESTAGIOCONTRATO.VLRBENEFICIOS,
	SESTAGIOAPOLICE.NOMECIASEGUROS,
	SESTAGIOAPOLICE.NRAPOLICE

FROM
	SESTAGIOCONTRATO
	LEFT JOIN SPROFESSOR ON
			SPROFESSOR.CODPROF = SESTAGIOCONTRATO.CODPROFORIENTADOR
	LEFT JOIN PPESSOA ON
			PPESSOA.CODIGO = 
			CASE 
				WHEN SPROFESSOR.CODPESSOA IS NULL THEN SESTAGIOCONTRATO.CODPESSOAORIENTADOR
				ELSE SPROFESSOR.CODPESSOA
			END
	LEFT JOIN SESTAGIOAPOLICE ON
			SESTAGIOAPOLICE.IDESTAGIOCONTRATO = SESTAGIOCONTRATO.IDESTAGIOCONTRATO
		AND SESTAGIOAPOLICE.RA = SESTAGIOCONTRATO.RA
