-- Cursando: 19
-- Alunos matriculados: 12, 101, 111
-- Pré matriculado: 125, 110
-- Talvez, omitir informações de disciplinas e retornar apenas a lista de alunos.

SELECT
	SMATRICPL.RA				[MATRICULA],
	PPESSOA.NOME				[ALUNO],
	SPLETIVO.CODPERLET			[PERIODO_LETIVO],
	SCURSO.NOME					[CURSO],
	S1.CODSTATUS				[CODSTATUS_PL],
	S1.DESCRICAO				[STATUS_PL],
	SDISCIPLINA.NOME			[DISCIPLINA],
	S2.CODSTATUS				[CODSTATUS_DISC],
	S2.DESCRICAO				[STATUS_DISC],
	PPESSOA.EMAIL				[EMAIL],
	PPESSOA.TELEFONE2			[TELEFONE]

FROM
	SPLETIVO
	INNER JOIN SMATRICPL ON
			SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SSTATUS S1 ON
			S1.CODSTATUS = SMATRICPL.CODSTATUS
	INNER JOIN SMATRICULA ON
			SMATRICULA.RA = SMATRICPL.RA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
		AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STURMADISC ON
			STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SDISCIPLINA ON
			SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	INNER JOIN SSTATUS S2 ON
		    S2.CODSTATUS = SMATRICULA.CODSTATUS
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA

WHERE
		SPLETIVO.IDPERLET = 167
	AND S1.CODSTATUS IN (12, 101, 111)
	AND S2.CODSTATUS IN (110, 125)

ORDER BY 
	PPESSOA.NOME
