-- Ingressantes por período letivo e curso

-- Modalidade = SMODALIDADE.CODMODALIDADECURSO

SELECT 
	SPLETIVO.CODPERLET				[PERIODO_LETIVO],
	SCURSO.NOME						[CURSO],
	SMODALIDADECURSO.DESCRICAO		[MODALIDADE],
	COUNT(*)						[TOTAL]

FROM
	SPLETIVO
	INNER JOIN SMATRICPL ON
			SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SMODALIDADECURSO ON
			SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO

WHERE 
		SMATRICPL.PERIODO = 1
	AND SMATRICPL.CODTIPOMAT NOT IN (35, 43)
GROUP BY
	SPLETIVO.CODPERLET, SCURSO.NOME, SMODALIDADECURSO.DESCRICAO

ORDER BY 
	SPLETIVO.CODPERLET,
	SCURSO.NOME;
