SELECT
	SMATRICPL.RA				[MATRICULA],
	UPPER(PPESSOA.NOME)			[ALUNO],
	SCONTRATO.CODCONTRATO		[CONTRATO]

FROM SMATRICPL
	INNER JOIN SCONTRATO ON
			SCONTRATO.RA = SMATRICPL.RA
		AND SCONTRATO.IDPERLET = SMATRICPL.IDPERLET
		AND SCONTRATO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		AND SCONTRATO.TIPOCONTRATO = 'P'
		AND SCONTRATO.IDPERLET = 167
	INNER JOIN SPARCELA ON
			SPARCELA.CODCONTRATO = SCONTRATO.CODCONTRATO
		AND SPARCELA.PARCELA = 6
	INNER JOIN SLAN ON
			SLAN.IDPARCELA = SPARCELA.IDPARCELA
	INNER JOIN FLAN ON
			FLAN.IDLAN = SLAN.IDLAN
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA

WHERE
		SMATRICPL.CODSTATUS IN (12, 101, 111)
	AND FLAN.STATUSLAN = 0
	AND SPARCELA.COTA = 1
	AND SPARCELA.DTVENCIMENTO > CONVERT(DATETIME, '2021-30-06')

ORDER BY	
	[ALUNO]
