/*
Listar os pagamentos realizados com cartão, para que Viviane confira o recebimento dos valores com o banco.
Informações: IDLAN, VALOR, Nº DA OPERAÇÃO.
*/

SELECT
	SALUNO.RA												[MATRICULA],
	UPPER(PPESSOA.NOME)										[ALUNO],
	FLAN.IDLAN,
	FBOLETO.NOSSONUMERO,
	convert(varchar, FINTEGRACAOCARTAO.DATAHORA, 103)		[DATA],
	CONVERT(decimal(10, 2), FINTEGRACAOCARTAO.VALORPAGO)	[VALORPAGO],
	TFORMAPAGTO.DESCFORMAPAGTO								[FORMAPAGTO],
	FINTEGRACAOCARTAO.CODAUTORIZACAO,
	FINTEGRACAOCARTAO.NSU,
	FINTEGRACAOCARTAO.IDTRANSACAO,
	FINTEGRACAOCARTAO.IDPROCESSO,
	FINTEGRACAOCARTAO.RECCREATEDBY

FROM
	FINTEGRACAOCARTAO 
	INNER JOIN FBOLETO ON
			FBOLETO.IDBOLETO = FINTEGRACAOCARTAO.IDBOLETO
	INNER JOIN FLANBOLETO ON
			FLANBOLETO.IDBOLETO = FBOLETO.IDBOLETO
	INNER JOIN FLAN ON
			FLAN.IDLAN = FLANBOLETO.IDLAN
	INNER JOIN FLANBAIXA ON
			FLANBAIXA.IDLAN = FLAN.IDLAN
	INNER JOIN TFORMAPAGTO ON
			TFORMAPAGTO.IDFORMAPAGTO = FLANBAIXA.IDFORMAPAGTO
	INNER JOIN SLAN ON
			SLAN.IDLAN = FLAN.IDLAN
	INNER JOIN SPARCELA ON
			SPARCELA.IDPARCELA = SLAN.IDPARCELA
	INNER JOIN SCONTRATO ON
			SCONTRATO.CODCONTRATO = SPARCELA.CODCONTRATO
		AND SCONTRATO.IDPERLET = SPARCELA.IDPERLET
		AND SCONTRATO.RA = SPARCELA.RA
	INNER JOIN SALUNO ON
			SALUNO.RA = SCONTRATO.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
WHERE
		FINTEGRACAOCARTAO.CODAUTORIZACAO IS NOT NULL
	AND FINTEGRACAOCARTAO.DATAHORA > CONVERT(DATETIME, '2021-29-04')
	-- última vez enviado: 09/07/2021
ORDER BY
	PPESSOA.NOME
			