	-- 2014210139 /DOIS CURSOS
	
	SELECT DISTINCT
		SMATRICPL.RA,
		PPESSOA.NOME														[ALUNO],
		SCURSO.NOME															[CURSO],
		--SMATRICPL.IDHABILITACAOFILIAL,
		/*CASE
			WHEN SPLETIVO.CODPERLET	IS NULL THEN 'Não foi solicitado'
			ELSE SPLETIVO.CODPERLET
		END																	[SOLICITADO EM], */
		SDOCUMENTO.DESCRICAO		DOCUMENTO,
		SDOCEXIGIDOS.QUANTIDADE		QTD_EXIGIDA,
		CASE
			WHEN SDOCALUNO.QUANTIDADE IS NULL THEN 0
			ELSE SDOCALUNO.QUANTIDADE
		END																	[QTD_ENTREGUE],
		PPESSOA.TELEFONE2													[TELEFONE],
		LOWER(PPESSOA.EMAIL)														[EMAIL]
	FROM
		SMATRICPL
		INNER JOIN SHABILITACAOFILIAL ON
				SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		INNER JOIN SCURSO ON
				SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
		INNER JOIN SDOCEXIGIDOS ON
				SDOCEXIGIDOS.IDPERLET = SMATRICPL.IDPERLET
			AND SDOCEXIGIDOS.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		LEFT JOIN SDOCALUNO ON
				SDOCALUNO.RA = SMATRICPL.RA
			AND SDOCALUNO.CODDOCUMENTO = SDOCEXIGIDOS.CODDOCUMENTO
		LEFT JOIN SPLETIVO ON
				SPLETIVO.IDPERLET = SDOCALUNO.IDPERLET
		INNER JOIN SDOCUMENTO ON
				SDOCUMENTO.CODDOCUMENTO = SDOCEXIGIDOS.CODDOCUMENTO
			OR SDOCUMENTO.CODDOCUMENTO = SDOCALUNO.CODDOCUMENTO
		INNER JOIN SALUNO ON
				SALUNO.RA = SMATRICPL.RA
		INNER JOIN PPESSOA ON
				PPESSOA.CODIGO = SALUNO.CODPESSOA
	WHERE
			SMATRICPL.IDPERLET = 167
		AND SDOCALUNO.IDPERLET = 167
		--AND SMATRICPL.RA = '2021141181'
		AND (SDOCALUNO.QUANTIDADE < SDOCEXIGIDOS.QUANTIDADE OR SDOCALUNO.QUANTIDADE IS NULL)
		AND SMATRICPL.CODSTATUS IN (12, 101, 111)

	ORDER BY
		SMATRICPL.RA