SELECT 
	SMATRICPL.RA,
	CONVERT(VARCHAR, SMATRICPL.DTMATRICULA, 103) [DTMATRICULA],
	CONVERT(VARCHAR, SHABILITACAOALUNO.DTINGRESSO, 103) [DTINGRESSO],
	SHABILITACAOFILIAL.CODCURSO

FROM SMATRICPL
	INNER JOIN SHABILITACAOALUNO ON
			SHABILITACAOALUNO.RA = SMATRICPL.RA
		AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	
WHERE
		SMATRICPL.IDHABILITACAOFILIAL IN (81, 82, 122, 123, 167)
	AND SMATRICPL.IDPERLET = 168
	AND SMATRICPL.CODSTATUS = 101

ORDER BY
	SHABILITACAOALUNO.DTINGRESSO

/*select * from SHABILITACAOALUNO
INNER JOIN SCONTRATO ON
			SCONTRATO.RA = SMATRICPL.RA
		AND SCONTRATO.IDPERLET = SMATRICPL.IDPERLET
		AND SCONTRATO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SPARCELA ON
			SPARCELA.CODCONTRATO = SCONTRATO.CODCONTRATO
		AND SPARCELA.PARCELA = 1
	INNER JOIN SLAN ON
			SLAN.IDPARCELA = SPARCELA.IDPARCELA
	INNER JOIN FLANBAIXA ON
			FLANBAIXA.IDLAN = SLAN.IDLAN */