SELECT
	PPESSOA.CODIGO,
	PPESSOA.DTNASCIMENTO,
	YEAR(GETDATE()) - YEAR(PPESSOA.DTNASCIMENTO) AS IDADE,
	PPESSOA.ESTADOCIVIL,
	PPESSOA.SEXO,
	PPESSOA.BAIRRO,
	PPESSOA.ESTADO,
	PPESSOA.CIDADE,
	PPESSOA.NATURALIDADE,
	PPESSOA.ESTADONATAL,
	PPESSOA.CORRACA,
	PCORRACA.DESCRICAO RACA,
	PPESSOA.DEFICIENTEFISICO,
	PPESSOA.DEFICIENTEAUDITIVO,
	PPESSOA.DEFICIENTEMOBREDUZIDA,
	PPESSOA.DEFICIENTEVISUAL,
	SMATRICPL.PERIODO,
	SMATRICPL.DTMATRICULA,
	SCURSO.NOME CURSO,
	SPLETIVO.CODPERLET,
	SMATRICPL.CODSTATUS,
	SSTATUS.DESCRICAO STATUS,
	SBOLSAALUNO.DESCONTO,
	SBOLSA.NOME BOLSA

FROM SPLETIVO
	INNER JOIN SMATRICPL ON
			SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SSTATUS ON
			SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	LEFT JOIN PCORRACA ON
			PCORRACA.CODCLIENTE = PPESSOA.CORRACA
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	LEFT JOIN SBOLSAALUNO ON
			SBOLSAALUNO.RA = SMATRICPL.RA
		AND SBOLSAALUNO.IDPERLET = SPLETIVO.IDPERLET
	LEFT JOIN SBOLSA ON
			SBOLSA.CODBOLSA = SBOLSAALUNO.CODBOLSA

WHERE
		SMATRICPL.CODSTATUS IN (5, 25, 31, 91, 85, 12, 101, 111)
	--AND SPLETIVO.IDPERLET = 167


