SELECT 
	SMATRICPL.RA,
	SMATRICPL.IDPERLET,
	SMATRICPL.IDHABILITACAOFILIAL,
	SMATRICPL.CODTURMA,
	SMATRICPL.CODSTATUS,
	SCONTRATO.CODCONTRATO,
	SPARCELA.IDPARCELA,
	FLAN.IDBOLETO,
	SPARCELA.PARCELA,
	FLAN.IDLAN,
	FLAN.STATUSLAN,
	FLAN.VALORORIGINAL,
	FLAN.VALORBAIXADO

FROM
	SMATRICPL
	INNER JOIN SCONTRATO ON
			SCONTRATO.RA = SMATRICPL.RA
		AND SCONTRATO.IDPERLET = SMATRICPL.IDPERLET
		AND SCONTRATO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SPARCELA ON
			SPARCELA.RA = SCONTRATO.RA
		AND SPARCELA.IDPERLET = SCONTRATO.IDPERLET
		AND SPARCELA.CODCONTRATO = SCONTRATO.CODCONTRATO
	INNER JOIN SLAN ON
			SLAN.IDPARCELA = SPARCELA.IDPARCELA
	INNER JOIN FLAN ON
			FLAN.IDLAN = SLAN.IDLAN

WHERE
	SMATRICPL.CODSTATUS IN (21, 41, 61, 81, 110, 124, 125)
	AND FLAN.STATUSLAN = 1
