SELECT
	CASE
		WHEN LTIPOPUBLIC.DESCRICAO <> 'Livro' THEN 'Outros Materiais' ELSE LTIPOPUBLIC.DESCRICAO
	END										[TIPO],
	COUNT(DISTINCT LPUBLIC.CODIGO)			[QTD_PUBLIC],
	COUNT(DISTINCT LEXEMPLAR.CODEXEMPLAR)	[QTD_EXEMPLARES]

FROM
	LPUBLIC
	INNER JOIN LTIPOPUBLIC ON
			LTIPOPUBLIC.CODIGO = LPUBLIC.TIPOPUBLIC
	INNER JOIN LEXEMPLAR ON
			LEXEMPLAR.CODPUBLIC = LPUBLIC.CODIGO

GROUP BY
	CASE
		WHEN LTIPOPUBLIC.DESCRICAO <> 'Livro' THEN 'Outros Materiais' ELSE LTIPOPUBLIC.DESCRICAO
	END

ORDER BY
	[QTD_PUBLIC] DESC