SELECT
	LTIPOPUBLIC.DESCRICAO					[TIPO],
	COUNT(DISTINCT LEMPRESTIMOS.CODIGO)		[QTD_EMPRESTIMOS]

FROM
	LEMPRESTIMOS
	INNER JOIN LPUBLIC ON
			LPUBLIC.CODIGO = LEMPRESTIMOS.CODPUBLIC
	INNER JOIN LTIPOPUBLIC ON
			LTIPOPUBLIC.CODIGO = LPUBLIC.TIPOPUBLIC

WHERE
	YEAR(LEMPRESTIMOS.DTHREMPRESTIMO) = 2020

GROUP BY
	LTIPOPUBLIC.DESCRICAO

ORDER BY
	[QTD_EMPRESTIMOS] DESC
