SELECT 
	SALUNO.RA,
	PPESSOA.CODUSUARIO

FROM
	SALUNO
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SMATRICPL ON
			SMATRICPL.RA = SALUNO.RA
WHERE
		SMATRICPL.RA <> PPESSOA.CODUSUARIO
	AND PPESSOA.CODUSUARIO IS NOT NULL
	AND SMATRICPL.RA LIKE '2021%'