-- STATUS
-- 3: Desclassificado por insuficiência de nota
-- 5: Em chamada
-- 8: Inscrição cancelada
-- 7: Compareceu à chamada

-- NOME, TELEFONE, EMAIL, CURSO, EAD/PRESENCIAL, STATUS, SE É ALUNO MATRICULADO

select DISTINCT
	SPSOPCAOINSCRITO.IDPS,
	CASE
		WHEN BEXECPROVA.CODPROVA = 260 THEN 'N'
		ELSE 'S'
	END AS																[FEZ PROVA],
	CASE
		WHEN SMATRICPL.RA IS NULL THEN 'N'
		WHEN (SMATRICPL.RA IS NOT NULL) AND (SMATRICPL.CODSTATUS = 125) THEN 'Pré-Matriculado PS'
		WHEN (SMATRICPL.RA IS NOT NULL) AND (SMATRICPL.CODSTATUS IN (12, 101, 111)) THEN 'S'
	END AS																[É ALUNO],
	CASE
		WHEN SPSOPCAOINSCRITO.STATUS = 3 THEN 'Desclassificado'
		WHEN SPSOPCAOINSCRITO.STATUS = 5 THEN 'Em Chamada'
		WHEN SPSOPCAOINSCRITO.STATUS = 7 THEN 'Compareceu à chamada'
		WHEN SPSOPCAOINSCRITO.STATUS = 8 THEN 'Inscrição cancelada'
	END AS																[STATUS TOP50],
	SPSUSUARIO.NOME														[CANDIDATO],
	SPSUSUARIO.TELEFONE2												[TELEFONE],
	LOWER(SPSUSUARIO.EMAIL)												[EMAIL],
	CASE
		WHEN SPSOPCAOINSCRITO.IDPS = 187 THEN 'TOP50 EAD'
		WHEN SPSOPCAOINSCRITO.IDPS = 197 THEN 'TOP50 Presencial'
	END AS																[PROCESSO SELETIVO],
	SPSAREAINTERESSE.NOME												[CURSO]

FROM
	SPSOPCAOINSCRITO
	INNER JOIN SPSUSUARIO ON
			SPSUSUARIO.CODUSUARIOPS = SPSOPCAOINSCRITO.CODUSUARIOPS
	INNER JOIN SPSPROCESSOSELETIVO ON
			SPSPROCESSOSELETIVO.IDPS = SPSOPCAOINSCRITO.IDPS
	INNER JOIN SPSAREAINTERESSE ON
			SPSAREAINTERESSE.IDAREAINTERESSE = SPSOPCAOINSCRITO.IDAREAINTERESSE
	INNER JOIN SPSCONTROLEDISTRIBUICAOPROVA ON
			SPSCONTROLEDISTRIBUICAOPROVA.IDPS = SPSOPCAOINSCRITO.IDPS
		AND SPSCONTROLEDISTRIBUICAOPROVA.CODUSUARIOPS = SPSOPCAOINSCRITO.CODUSUARIOPS  
	LEFT JOIN BEXECPROVA ON
			BEXECPROVA.CODUSUARIOPS = SPSOPCAOINSCRITO.CODUSUARIOPS
		AND BEXECPROVA.CODPROVA = 260
		AND BEXECPROVA.ID = SPSCONTROLEDISTRIBUICAOPROVA.IDPROVA
	LEFT JOIN PPESSOA ON
			PPESSOA.CPF = SPSUSUARIO.CPF
	LEFT JOIN SALUNO ON
			SALUNO.CODPESSOA = PPESSOA.CODIGO
	LEFT JOIN SMATRICPL ON
			SMATRICPL.RA = SALUNO.RA
		AND SMATRICPL.IDPERLET IN (167, 168)
		AND SMATRICPL.CODSTATUS IN (12, 101, 111, 125) 

WHERE
		SPSOPCAOINSCRITO.IDPS IN (187, 197)

ORDER BY
	[FEZ PROVA],
	[É ALUNO],
	[CANDIDATO]


	SELECT * FROM BEXECPROVA WHERE CODPROVA = 260
	SELECT * FROM SPSSTATUSOPCAO

	SELECT CODUSUARIOPS, COUNT(*) FROM SPSOPCAOINSCRITO WHERE IDPS IN (187, 197)
	GROUP BY CODUSUARIOPS
	HAVING COUNT(*) > 1
	ORDER BY CODUSUARIOPS


	select * from BHISTORICO where codprova = 260
	select * from bexecprova where codprova = 260
	select * from glinksrel where mastertable = 'bhistorico'
	select * from SPSCONTROLEDISTRIBUICAOPROVA INNER JOIN BEXECPROVA ON BEXECPROVA.ID = SPSCONTROLEDISTRIBUICAOPROVA.IDPROVA where SPSCONTROLEDISTRIBUICAOPROVA.codprova = 260