UPDATE 
	SPSINSCRICAOAREAOFERTADA 
SET DATAINSCRICAO = GETDATE(), RECMODIFIEDBY = 'ERASMO.NETO', RECMODIFIEDON = GETDATE() 
WHERE IDPS = 165 /*ID PROCESSO SELETIVO*/
AND NUMEROINSCRICAO = 691 /*NUM. INSCRIÇÃO*/