select DISTINCT

CASE
	WHEN SMATRICPL.CODFILIAL = 1 THEN 'MATRIZ - JUAZEIRO'
	WHEN SMATRICPL.CODFILIAL = 4 THEN 'FILIAL - ARARIPINA'
END	[FILIAL],
SALUNO.RA,
PPESSOA.NOME [ALUNO],
SPLETIVO.CODPERLET,


SCURSO.NOME [Curso],
SMODALIDADECURSO.DESCRICAO AS 'MODALIDADE',
(SELECT TOP 1 CONVERT(varchar,slogpletivo.DTALTERACAO , 103)
		FROM slogpletivo 
					INNER JOIN SMATRICPL (NOLOCK) ON 
					SMATRICPL.RA = slogpletivo.RA
			where SMATRICPL.RA = SCONTRATO.RA
				AND SMATRICPL.IDPERLET = SCONTRATO.IDPERLET
		ORDER BY slogpletivo.DTALTERACAO DESC) 'ÚLTIMA DATA ALTERAÇÃO',

(SELECT FLOOR(SUM(SMATRICULA.NUMCREDITOSCOB) / 6)
          FROM SMATRICULA (NOLOCK)
               INNER JOIN STURMADISC  (NOLOCK)
         	           ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA 
			          AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
         WHERE SMATRICULA.CODCOLIGADA = SCONTRATO.CODCOLIGADA
           AND SMATRICULA.RA          = SCONTRATO.RA
           AND SMATRICULA.IDPERLET    = SCONTRATO.IDPERLET
		   AND SMATRICULA.CODSTATUS in ('19','2')) as 'TOTALCREDITOS_FIN',

(SELECT top 1 CONVERT(DECIMAL(10,2),SDISCGRADE.VALORCREDITO) FROM SMATRICPL
	INNER JOIN SMATRICULA ON
			SMATRICULA.RA = SMATRICPL.RA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
	INNER JOIN STURMADISC ON
			STURMADISC.IDPERLET = SMATRICULA.IDPERLET
		AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SDISCIPLINA (NOLOCK) ON
			SDISCIPLINA.CODDISC = STURMADISC.CODDISC	
	INNER JOIN SDISCGRADE (NOLOCK) ON
			SDISCGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO	
		AND SDISCGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
		AND SDISCGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
WHERE SMATRICULA.CODCOLIGADA = SCONTRATO.CODCOLIGADA
  AND SMATRICULA.RA          = SCONTRATO.RA
  AND SMATRICULA.IDPERLET    = SCONTRATO.IDPERLET
  AND SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
  AND SMATRICPL.CODSTATUS IN (12,101,111)
  AND SMATRICULA.CODSTATUS = 19) 'Valor Credito'


from FLAN (nolock) 
	
		inner join SLAN (nolock) on
				   slan.CODCOLIGADA = flan.CODCOLIGADA
			   and slan.IDLAN       = flan.IDLAN
			   
		inner join SPARCELA (nolock) on
		           SPARCELA.CODCOLIGADA = slan.CODCOLIGADA and
		           SPARCELA.IDPARCELA   = slan.IDPARCELA
		           
		           
		inner join SALUNO (nolock) on
			       SALUNO.CODCOLIGADA = SPARCELA.CODCOLIGADA
			   and SALUNO.RA          = SPARCELA.RA
			   
		inner join PPESSOA (nolock) on
		           PPESSOA.CODIGO = SALUNO.CODPESSOA
		           
		inner join FCFO (nolock) on
			       fcfo.CODCOLIGADA = flan.CODCOLCFO
			   and FCFO.CODCFO      = flan.CODCFO
			   
		inner join SSERVICO (nolock) on
				   SSERVICO.CODCOLIGADA = SPARCELA.CODCOLIGADA
			   and SSERVICO.CODSERVICO  = SPARCELA.CODSERVICO
			   
		inner join SCONTRATO (nolock) on
				   SCONTRATO.CODCOLIGADA = SPARCELA.CODCOLIGADA
			   and SCONTRATO.RA          = SPARCELA.RA
			   and SCONTRATO.CODCONTRATO = SPARCELA.CODCONTRATO
			   and SCONTRATO.IDPERLET    = SPARCELA.IDPERLET
				
		INNER JOIN SPLETIVO (NOLOCK)
				ON SCONTRATO.CODCOLIGADA = SPLETIVO.CODCOLIGADA
				AND SCONTRATO.IDPERLET = SPLETIVO.IDPERLET
   
		inner join SHABILITACAOFILIAL (nolock)
			INNER JOIN STURNO (NOLOCK)
				ON SHABILITACAOFILIAL.CODCOLIGADA = STURNO.CODCOLIGADA
				AND SHABILITACAOFILIAL.CODTURNO = STURNO.CODTURNO
			    on  SHABILITACAOFILIAL.CODCOLIGADA = SCONTRATO.CODCOLIGADA 
			   and SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
			   
		inner join SCURSO (nolock) on
		           SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		       and SCURSO.CODCURSO    = SHABILITACAOFILIAL.CODCURSO

		INNER JOIN SMODALIDADECURSO (NOLOCK) ON
				SCURSO.CODMODALIDADECURSO = SMODALIDADECURSO.CODMODALIDADECURSO
		
		INNER JOIN SMATRICPL (NOLOCK) ON
		           SMATRICPL.CODCOLIGADA = SCONTRATO.CODCOLIGADA
		       AND SMATRICPL.RA          = SCONTRATO.RA
		       AND SMATRICPL.IDPERLET    = SCONTRATO.IDPERLET
		       AND SMATRICPL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
		
		INNER JOIN SSTATUS (NOLOCK) ON
		           SSTATUS.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		       AND SSTATUS.CODSTATUS   = SMATRICPL.CODSTATUS
		
		inner join FLANCOMPL (nolock) on           
		        FLANCOMPL.CODCOLIGADA = FLAN.CODCOLIGADA
		    AND FLANCOMPL.IDLAN = FLAN.IDLAN

		left JOIN SBOLSAALUNO (NOLOCK) ON
				SCONTRATO.IDPERLET = SBOLSAALUNO.IDPERLET AND
				SALUNO.RA = SBOLSAALUNO.RA



WHERE SSERVICO.NOME <> 'ACORDO' and flan.STATUSLAN <> 2  AND FLAN.MESDECOMPETENCIA >= '01-08-2021' AND FLAN.MESDECOMPETENCIA <= '26-08-2021'
and SMATRICPL.CODSTATUS <> '125'  

/* UNICA ALTERAÇÃO 09/08 */
/*AND SCONTRATO.DTASSINATURA BETWEEN :Data_Inicial AND :Data_Final*/
/* FIM DA UNICA ALTER~ÇÃO*/
and SCURSO.CODCURSO in ('1','10','101','102','103','104','105','106','107','108','11','12','13','14','15','16','17','18','19','2','20','201','2011','2013113','2013211',
'2013212','2013222','2015100','2015101','2015102','2015103','2017101','2017102','21','212011','22','23','24','25','26','27','28','29','3','30','31','32','33','34',
'35','36','37','38','39','4','40','41','42','43','44','45','46','47','48','5','6','7','8','9','EAD-01','EAD-02','EAD-03','EAD-04')
