SELECT
	SALUNO.RA,
	PPESSOA.NOME	[ALUNO],
	SCURSO.NOME		[CURSO],
	SMODALIDADECURSO.DESCRICAO	[MODALIDADE],
	SPLETIVO.CODPERLET	[PERIODO_LETIVO],
	STATUSPL.DESCRICAO	[STATUS_PL],
	STURMADISC.CODTURMA,
	SDISCIPLINA.NOME	[DISCIPLINA],
	PROFESSOR.NOME		[PROFESSOR],
	STATUSDISC.DESCRICAO	[STATUS_DISCIPLINA]
FROM SPLETIVO (NOLOCK)
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SMATRICULA (NOLOCK) ON
			SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
		AND SMATRICULA.RA  = SMATRICPL.RA
	INNER JOIN STURMADISC (NOLOCK) ON
			STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
		AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SDISCIPLINA (NOLOCK) ON
			SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STURNO (NOLOCK) ON
			STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO
	INNER JOIN SMODALIDADECURSO (NOLOCK) ON
			SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA
		AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO
	INNER JOIN SSTATUS STATUSPL (NOLOCK) ON
			STATUSPL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND STATUSPL.CODSTATUS = SMATRICPL.CODSTATUS
	INNER JOIN SSTATUS STATUSDISC (NOLOCK) ON
			STATUSDISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
		AND STATUSDISC.CODSTATUS = SMATRICULA.CODSTATUS
	INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SPROFESSORTURMA (NOLOCK) ON
			SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
	INNER JOIN SPROFESSOR (NOLOCK) ON
			SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
		AND SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	INNER JOIN PPESSOA PROFESSOR (NOLOCK) ON
			PROFESSOR.CODIGO = SPROFESSOR.CODPESSOA
WHERE SMATRICPL.CODCOLIGADA = 1
	AND SMATRICPL.CODFILIAL = 1
	AND SMATRICPL.CODSTATUS IN (12, 101, 111)
	AND SPLETIVO.CODPERLET IN ('2021.2')
	AND SCURSO.CODTIPOCURSO = 1
	AND SCURSO.CODCURSO = 9
	AND SDISCIPLINA.NOME LIKE '%EST�GIO PROFISSIONAL%'