SELECT DISTINCT

	SALUNO.RA AS 'MATRICULA',
	PPESSOA.NOME 'NOME DO ALUNO',
	SCURSO.NOME AS 'CURSO DO ALUNO',
	CONVERT(DECIMAL(10,2),SHISTHABILITACAOALUNO.CR) AS 'CR'

FROM 

	SHISTHABILITACAOALUNO (NOLOCK)
		INNER JOIN SALUNO (NOLOCK) ON
				SALUNO.CODCOLIGADA = SHISTHABILITACAOALUNO.CODCOLIGADA
			AND	SALUNO.RA = SHISTHABILITACAOALUNO.RA
		INNER JOIN PPESSOA (NOLOCK) ON
				PPESSOA.CODIGO = SALUNO.CODPESSOA
		INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
				SHABILITACAOFILIAL.CODCOLIGADA = SHISTHABILITACAOALUNO.CODCOLIGADA
			AND	SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHISTHABILITACAOALUNO.IDHABILITACAOFILIAL
		INNER JOIN SCURSO (NOLOCK) ON
				SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND	SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
		INNER JOIN SMATRICPL (NOLOCK) ON
				SMATRICPL.CODCOLIGADA = SHISTHABILITACAOALUNO.CODCOLIGADA
			AND	SMATRICPL.RA = SALUNO.RA
			AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
		INNER JOIN SMODALIDADECURSO (NOLOCK) ON
				SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA
			AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO
		FULL OUTER JOIN SMATRICULA (NOLOCK) ON
				SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SMATRICULA.IDPERLET  = SMATRICPL.IDPERLET

WHERE SHISTHABILITACAOALUNO.CODSTATUS = 19 
AND SHABILITACAOFILIAL.CODFILIAL = 1
AND SHISTHABILITACAOALUNO.QTDPENDDISCOBR = 0
AND SHISTHABILITACAOALUNO.QTDPENDDISCOPT = 0


ORDER BY SCURSO.NOME, CONVERT(DECIMAL(10,2),SHISTHABILITACAOALUNO.CR) DESC

--AND (CASE WHEN SMATRICPL.IDPERLET = 168 AND SMATRICPL.CODSTATUS IN (12,111,101) THEN 1
--	ELSE 0 END ) = 1

