select DISTINCT

SMATRICPL.RA,
PPESSOA.NOME,
SHISTDISCPENDENTES.DISCIPLINA,
SCURSO.NOME,
SGRADE.DESCRICAO,
SPERIODO.DESCRICAO

FROM SPLETIVO (NOLOCK)

	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SMATRICULA (NOLOCK) ON
			SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
		AND SMATRICULA.RA  = SMATRICPL.RA
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL

	INNER JOIN SHABILITACAOALUNO (NOLOCK) ON
			SHABILITACAOALUNO.RA = SMATRICPL.RA
			AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STIPOCURSO (NOLOCK) ON
			STIPOCURSO.CODTIPOCURSO = SCURSO.CODTIPOCURSO
	INNER JOIN SMODALIDADECURSO (NOLOCK) ON
			SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA
		AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO

	INNER JOIN SGRADE (NOLOCK) ON
			SGRADE.CODCURSO = SCURSO.CODCURSO
			AND SHABILITACAOFILIAL.CODGRADE = SGRADE.CODGRADE

	INNER JOIN SALUNO (NOLOCK) ON
		SALUNO.RA = SMATRICPL.RA

	INNER JOIN PPESSOA (NOLOCK) ON
		PPESSOA.CODIGO = SALUNO.CODPESSOA

INNER JOIN SHISTDISCPENDENTES (NOLOCK) ON
		SMATRICPL.RA = SHISTDISCPENDENTES.RA
		AND SHISTDISCPENDENTES.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

			INNER JOIN SDISCGRADE (NOLOCK) ON
			SDISCGRADE.CODCURSO = SCURSO.CODCURSO
			AND SDISCGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
			AND SDISCGRADE.CODDISC = SHISTDISCPENDENTES.CODDISC

			INNER JOIN SPERIODO (NOLOCK) ON
				SPERIODO.CODPERIODO = SDISCGRADE.CODPERIODO
				AND SPERIODO.CODGRADE = SDISCGRADE.CODGRADE
				AND SPERIODO.CODCURSO = SCURSO.CODCURSO


where (SHISTDISCPENDENTES.CODSTATUS <> 19 OR SHISTDISCPENDENTES.CODSTATUS IS NULL)
	AND SMODALIDADECURSO.DESCRICAO NOT IN ('EAD','SEMIPRESENCIAL')
	AND SCURSO.CODCURSO IN ('2')
	AND SHABILITACAOALUNO.CODSTATUS = 19
	and SGRADE.CODGRADE = 1
	and speriodo.CODPERIODO < 6
	and SMATRICPL.CODSTATUS in (12,101,111) 
	and SPLETIVO.CODPERLET = '2021.2'

order by PPESSOA.NOME	