SELECT DISTINCT

  SMATRICULA.RA,
  PPESSOA.NOME AS 'NOMEALUNO'


FROM STURMADISC (NOLOCK) 

 INNER JOIN SMATRICULA (NOLOCK)
 	INNER JOIN SMATRICPL (NOLOCK)
		ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
		AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		AND SMATRICULA.RA = SMATRICPL.RA
  INNER JOIN SALUNO (NOLOCK)
  ON (SMATRICULA.CODCOLIGADA = SALUNO.CODCOLIGADA
  AND SMATRICULA.RA = SALUNO.RA)
    ON (STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
    AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC)
    
    INNER JOIN SSTATUS (NOLOCK)
    ON (SMATRICULA.CODCOLIGADA = SSTATUS.CODCOLIGADA
    AND SMATRICULA.CODSTATUS = SSTATUS.CODSTATUS)
    
    INNER JOIN SHABILITACAOFILIAL (NOLOCK)
  INNER JOIN SHABILITACAO (NOLOCK)
  ON (SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAO.CODCOLIGADA
  AND SHABILITACAOFILIAL.CODCURSO = SHABILITACAO.CODCURSO
  AND SHABILITACAOFILIAL.CODHABILITACAO = SHABILITACAO.CODHABILITACAO)
 ON (STURMADISC.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
 AND STURMADISC.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL)
    
    INNER JOIN SCURSO (NOLOCK)
    ON (SHABILITACAOFILIAL.CODCOLIGADA = SCURSO.CODCOLIGADA
    AND SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO)
 
 INNER JOIN STURNO (NOLOCK)
    ON (SHABILITACAOFILIAL.CODCOLIGADA = STURNO.CODCOLIGADA
    AND SHABILITACAOFILIAL.CODTURNO = STURNO.CODTURNO)
 
 INNER JOIN PPESSOA (NOLOCK)
    ON (SALUNO.CODPESSOA = PPESSOA.CODIGO)       
   
 INNER JOIN SPLETIVO (NOLOCK)
    ON (STURMADISC.CODCOLIGADA = SPLETIVO.CODCOLIGADA
    AND STURMADISC.IDPERLET = SPLETIVO.IDPERLET)
    
    INNER JOIN STIPOCURSO (NOLOCK)
    ON (STURMADISC.CODCOLIGADA = STIPOCURSO.CODCOLIGADA
    AND STURMADISC.CODTIPOCURSO = STIPOCURSO.CODTIPOCURSO)
   
 INNER JOIN GFILIAL (NOLOCK)
 ON (STURMADISC.CODCOLIGADA = GFILIAL.CODCOLIGADA
    AND STURMADISC.CODFILIAL = GFILIAL.CODFILIAL)
   
 INNER JOIN SDISCIPLINA (NOLOCK)
    ON (STURMADISC.CODCOLIGADA = SDISCIPLINA.CODCOLIGADA
    AND STURMADISC.CODDISC = SDISCIPLINA.CODDISC)

	INNER JOIN SHISTDISCEQUIVCONCLUIDAS (NOLOCK) ON
		SHISTDISCEQUIVCONCLUIDAS.IDPERLET = SPLETIVO.IDPERLET
		AND SHISTDISCEQUIVCONCLUIDAS.RA = SMATRICPL.RA

WHERE 

	STURMADISC.CODCOLIGADA = 1
  AND STURMADISC.CODFILIAL = 1
  and SCURSO.CODCURSO = '11'
  AND SHISTDISCEQUIVCONCLUIDAS.CODDISC <> 'NUT001'
  AND SMATRICPL.IDPERLET IN (152,144,143,141)
  AND SSTATUS.DESCRICAO = 'Aprovado'



ORDER BY NOMEALUNO