SELECT DISTINCT

	TMOVRELAC.IDMOVORIGEM AS 'MOVIMENTO ORIGEM',
	TMOV.RECCREATEDON AS 'DATA ORIGEM',
	TMOV.RECCREATEDBY AS 'USUARIO CRIAÇÃO',
	GCCUSTO.NOME AS 'CENTRO CUSTO',
	TMOV.CODFILIAL AS 'COD FILIAL',
	TCCOTACAO.DATCOTACAO AS 'DATA COTAÇÃO',
	TCCOTACAO.CODCOTACAO AS 'CODIGO COTAÇÃO',
	TCCOTACAO.DESCRICAO AS 'DESCRIÇÃO',
	TVEN.NOME AS 'COMPRADOR',
	MOVIMENTO_DESTINO.DATAEMISSAO AS 'DATA EMISSÃO OC/OCM',
	MOVIMENTO_DESTINO.IDMOV AS 'IDMOVIMENTO',
	MOVIMENTO_DESTINO.NUMEROMOV AS 'NUMERO MOVIMENTO',
	MOVIMENTO_DESTINO.SERIE AS 'TIPO MOVIMENTO',
	FCFO.NOMEFANTASIA AS 'NOME FANTASIA',
	FCFO.CGCCFO AS 'CNPJ/CPF',
	TCPG.NOME AS 'FORMA PAGAMENTO',
	TPRODUTO.NOMEFANTASIA AS 'PRODUTO',
	TCORCAMENTO.DESPESA AS 'DESPESA',
	TCORCAMENTO.VALORFRETE / (SELECT COUNT (*) FROM (SELECT DISTINCT IDMOV FROM TCITMORCAMENTO ITMORC WHERE ITMORC.CODCOTACAO = TCITMORCAMENTO.CODCOTACAO) ABC)AS 'FRETE',
	
	DATEDIFF(MONTH, TMOV.DATACRIACAO, MOVIMENTO_DESTINO.DATAEMISSAO) as 'MESES PARA ATENDIMENTO',
	
	'0' AS 'EM ABERTO',
	'0' AS 'OC/OCM GERADA SEM SC',
	
	CASE WHEN DATEDIFF(MONTH, TMOV.DATACRIACAO, MOVIMENTO_DESTINO.DATAEMISSAO) <> 0 THEN '0'
		ELSE '1' END AS 'ATENDIDAS MESMO MÊS',

		CONVERT(INTEGER, TCITMORCAMENTO.QUANTIDADEORC) as 'QUANTIDADE',

	/*CASE WHEN  (TCITMORCAMENTO.QTDEFETIVADA <> 0 AND ORIG.QUANTIDADETOTAL < TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
	THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QTDEFETIVADA) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  )
		 WHEN  (TCITMORCAMENTO.QTDEFETIVADA = 0 AND ORIG.QUANTIDADETOTAL < TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
		 THEN(SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QUANTIDADENEG) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  )
		WHEN (TCITMORCAMENTO.QTDEFETIVADA <> 0 AND ORIG.QUANTIDADETOTAL >= TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
		THEN TITMMOV.QUANTIDADE /*(SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QTDEFETIVADA) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  ) */
		WHEN (TCITMORCAMENTO.QTDEFETIVADA =	 0 AND ORIG.QUANTIDADETOTAL >= TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
		THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QUANTIDADENEG) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  ) END AS 'QUANTIDADE',
	*/
	/*(SELECT TOP 1 CONVERT(DECIMAL(10,4),A.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO A WHERE A.IDMOV = TMOV.IDMOV AND A.IDPRD = TITMMOV.IDPRD AND A.CFOVENCEDOR <> 0 AND A.VALHOMOGENEONEGOCIADO <> 0 AND TCCOTACAO.STSCOTACAO <> 7)  */
	TITMMOV.PRECOUNITARIO + CONVERT(DECIMAL(10,2), ROUND((MOVIMENTO_DESTINO.VALORFRETE/
	(SELECT COUNT (*) FROM (SELECT DISTINCT IDMOV FROM TCITMORCAMENTO ITMORC WHERE ITMORC.CODCOTACAO = TCITMORCAMENTO.CODCOTACAO) ABC))/CONVERT(INTEGER, SUM(QUANTIDADEORC)),2,0)) AS 'VALOR ITM COM FRETE',

	/*(SELECT TOP 1 CONVERT(DECIMAL(10,4),B.VALEQUALIZADONEG) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  )  */
	TITMMOV.PRECOUNITARIO AS 'VALOR ITM S/ FRETE',
		
	/*CASE 
		WHEN  (TCITMORCAMENTO.QTDEFETIVADA <> 0 AND ORIG.QUANTIDADETOTAL < TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
			THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QTDEFETIVADA) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7) * 
				(SELECT TOP 1 CONVERT(DECIMAL(10,4),C.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO C WHERE C.IDMOV = TMOV.IDMOV AND C.IDPRD = TITMMOV.IDPRD AND C.CFOVENCEDOR <> 0 AND C.VALHOMOGENEOCOTADO <> '0' AND TCCOTACAO.STSCOTACAO <> 7 )
		 WHEN  (TCITMORCAMENTO.QTDEFETIVADA = 0 AND ORIG.QUANTIDADETOTAL < TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
			THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QUANTIDADENEG) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7) * 
			(SELECT TOP 1 CONVERT(DECIMAL(10,4),C.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO C WHERE C.IDMOV = TMOV.IDMOV AND C.IDPRD = TITMMOV.IDPRD AND C.CFOVENCEDOR <> 0 AND C.VALHOMOGENEOCOTADO <> '0' AND TCCOTACAO.STSCOTACAO <> 7 )
		WHEN (TCITMORCAMENTO.QTDEFETIVADA <> 0 AND ORIG.QUANTIDADETOTAL >= TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
			THEN TITMMOV.VALORBRUTOITEMORIG /*(SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QTDEFETIVADA) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  ) * 
			(SELECT TOP 1 CONVERT(DECIMAL(10,4),C.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO C WHERE C.IDMOV = TMOV.IDMOV AND C.IDPRD = TITMMOV.IDPRD AND C.CFOVENCEDOR <> 0 AND C.VALHOMOGENEOCOTADO <> '0' AND TCCOTACAO.STSCOTACAO <> 7 ) */
		WHEN (TCITMORCAMENTO.QTDEFETIVADA = 0 AND ORIG.QUANTIDADETOTAL >= TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
			THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QUANTIDADENEG) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  )  * 
			(SELECT TOP 1 CONVERT(DECIMAL(10,4),C.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO C WHERE C.IDMOV = TMOV.IDMOV AND C.IDPRD = TITMMOV.IDPRD AND C.CFOVENCEDOR <> 0 AND C.VALHOMOGENEOCOTADO <> '0' AND TCCOTACAO.STSCOTACAO <> 7 )
		END*/
		TCITMORCAMENTO.QUANTIDADEORC * TITMMOV.PRECOUNITARIO + CONVERT(DECIMAL(10,2), ROUND((MOVIMENTO_DESTINO.VALORFRETE/
	(SELECT COUNT (*) FROM (SELECT DISTINCT IDMOV FROM TCITMORCAMENTO ITMORC WHERE ITMORC.CODCOTACAO = TCITMORCAMENTO.CODCOTACAO) ABC))/CONVERT(INTEGER, SUM(QUANTIDADEORC)),2,0))	AS 'VALOR TOTAL ITEM',


	'0' AS 'DESCONTO OBTIDO',
	'0' AS 'DESCONTO NEGOCIADO',
	'0' AS 'SOLICITAÇÕES GERADAS',
	'1' AS 'ATENDIDA DE MES ANTERIOR'
	
FROM TMOV (NOLOCK)
	
	INNER JOIN TITMMOV ORIG (NOLOCK) ON
			TMOV.IDMOV = ORIG.IDMOV

	INNER JOIN TMOVRELAC (NOLOCK) ON
			TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV

	INNER JOIN TMOV MOVIMENTO_DESTINO (NOLOCK) ON
			MOVIMENTO_DESTINO.IDMOV = TMOVRELAC.IDMOVDESTINO

	INNER JOIN TITMMOV (NOLOCK) ON
			MOVIMENTO_DESTINO.IDMOV = TITMMOV.IDMOV
		AND TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA

	INNER JOIN TPRODUTO (NOLOCK) ON
			TPRODUTO.IDPRD = TITMMOV.IDPRD

	INNER JOIN TCCOTACAOITMMOV (NOLOCK) ON
			TITMMOV.IDMOV = TCCOTACAOITMMOV.IDMOV 

	INNER JOIN TCCOTACAO (NOLOCK) ON
			TCCOTACAOITMMOV.CODCOTACAO = TCCOTACAO.CODCOTACAO

	INNER JOIN TCITMORCAMENTO (NOLOCK) ON
			TCCOTACAO.CODCOTACAO = TCITMORCAMENTO.CODCOTACAO

	INNER JOIN TCORCAMENTO (NOLOCK) ON
		TCORCAMENTO.CODCOTACAO = TCITMORCAMENTO.CODCOTACAO
		AND TCORCAMENTO.CODCFO = TCITMORCAMENTO.CODCFO
		AND TCORCAMENTO.CODCOLCFO = TCITMORCAMENTO.CODCOLCFO

	INNER JOIN GCCUSTO (NOLOCK) ON
		TITMMOV.CODCCUSTO = GCCUSTO.CODCCUSTO

	INNER JOIN TVEN (NOLOCK) ON
		TCCOTACAO.CODCOMPRADOR = TVEN.CODVEN

	INNER JOIN FCFO (NOLOCK) ON
		MOVIMENTO_DESTINO.CODCFO = FCFO.CODCFO

	FULL OUTER JOIN TCPG (NOLOCK) ON
		MOVIMENTO_DESTINO.CODCPG = TCPG.CODCPG


WHERE (
(SELECT TOP 1 CONVERT(DECIMAL(10,4),E.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO E WHERE E.IDMOV = TMOV.IDMOV AND E.IDPRD = TITMMOV.IDPRD AND E.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) * TITMMOV.QUANTIDADETOTAL) IS NOT NULL 
AND TMOV.SERIE IN ('SC') 
AND TCITMORCAMENTO.CFOVENCEDOR <> 0  
AND TMOV.DATACRIACAO BETWEEN '12/07/2021' AND '12/08/2021'
and TCORCAMENTO.CODCOTACAO = '2021.000603'
AND TCITMORCAMENTO.CFOVENCEDOR = 1
AND (SELECT F.PRECOUNITARIO FROM TITMMOV F WHERE F.CODCOLIGADA = MOVIMENTO_DESTINO.CODCOLIGADA AND F.IDMOV = MOVIMENTO_DESTINO.IDMOV AND F.IDPRD = TITMMOV.IDPRD and TCCOTACAO.STSCOTACAO <> 7) IS NOT NULL  
AND CASE 
		WHEN  (ORIG.QUANTIDADETOTAL < TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) THEN ORIG.QUANTIDADETOTAL 
		WHEN ( ORIG.QUANTIDADETOTAL >= TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) THEN TITMMOV.QUANTIDADETOTAL 
	END IS NOT NULL
AND TCCOTACAO.STSCOTACAO <> 7 

GROUP BY TMOV.IDMOV,TMOV.RECCREATEDON,TMOV.RECCREATEDBY,GCCUSTO.NOME,TMOV.CODFILIAL,TCCOTACAO.DATCOTACAO,TCCOTACAO.CODCOTACAO,
TCCOTACAO.DESCRICAO,TVEN.NOME,TMOV.DATAEMISSAO,MOVIMENTO_DESTINO.DATAEMISSAO,MOVIMENTO_DESTINO.IDMOV,MOVIMENTO_DESTINO.NUMEROMOV,
MOVIMENTO_DESTINO.SERIE,FCFO.NOMEFANTASIA,FCFO.CGCCFO,TCPG.NOME,TPRODUTO.NOMEFANTASIA,TCORCAMENTO.DESPESA,TCITMORCAMENTO.CODCOTACAO,
TCORCAMENTO.VALORFRETE,TMOV.DATACRIACAO,TITMMOV.QUANTIDADE,TITMMOV.QUANTIDADETOTAL,TITMMOV.PRECOUNITARIO,TMOV.VALORFRETE,TCITMORCAMENTO.QTDEFETIVADA,
TCCOTACAO.STSCOTACAO,TITMMOV.IDPRD,ORIG.QUANTIDADETOTAL,ORIG.IDPRD,TCITMORCAMENTO.CFOVENCEDOR,TITMMOV.VALORBRUTOITEMORIG,TCITMORCAMENTO.QUANTIDADEORC,
MOVIMENTO_DESTINO.VALORFRETE,TMOVRELAC.IDMOVORIGEM

/*
UNION

SELECT DISTINCT

	TMOV.IDMOV AS 'MOVIMENTO ORIGEM',
	TMOV.DATACRIACAO AS 'DATA ORIGEM',
	TMOV.RECCREATEDBY AS 'USUARIO CRIAÇÃO',
	GCCUSTO.NOME AS 'CENTRO CUSTO',
	TMOV.CODFILIAL AS 'COD FILIAL',
	NULL AS 'DATA COTAÇÃO',
	NULL AS 'CODIGO COTAÇÃO',
	NULL AS 'DESCRIÇÃO',
	NULL AS 'COMPRADOR',
	NULL AS 'DATA EMISSÃO OC/OCM',
	NULL AS 'IDMOVIMENTO',
	NULL AS 'NUMERO MOVIMENTO',
	NULL AS 'TIPO MOVIMENTO',
	NULL AS 'NOME FANTASIA',
	NULL AS 'CNPJ/CPF',
	NULL AS 'FORMA PAGAMENTO',
	TPRODUTO.NOMEFANTASIA AS 'PRODUTO',
	'0' AS 'DESPESA',
	'0' as 'FRETE',
	'0' as 'MESES PARA ATENDIMENTO',
	'1' AS 'EM ABERTO',
	'0' AS 'OC/OCM GERADA SEM SC',

	'0' AS 'ATENDIDAS MESMO MÊS',

	'0' AS 'QUANTIDADE',

	'0' AS 'VALOR ITM COM FRETE',

	'0' AS 'VALOR ITM S/ FRETE',

	'0' AS 'VALOR TOTAL ITEM',
	'0' AS 'DESCONTO OBTIDO',
	'0' AS 'DESCONTO NEGOCIADO',
	'1' as 'SOLICITAÇÕES GERADAS',
		'0' AS 'ATENDIDA DE MES ANTERIOR'

FROM TMOV

INNER JOIN TITMMOV (NOLOCK) ON
	TMOV.IDMOV = TITMMOV.IDMOV
	AND TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA

INNER JOIN TPRODUTO (NOLOCK) ON
			TPRODUTO.IDPRD = TITMMOV.IDPRD

FULL OUTER JOIN TMOVRELAC (NOLOCK) ON
			TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV

FULL OUTER JOIN TMOV MOVIMENTO_DESTINO ON
			MOVIMENTO_DESTINO.IDMOV = TMOVRELAC.IDMOVDESTINO

INNER JOIN GCCUSTO (NOLOCK) ON
	TITMMOV.CODCCUSTO = GCCUSTO.CODCCUSTO

WHERE TMOV.SERIE IN ('SC') AND TMOV.DATACRIACAO BETWEEN '12/07/2021' AND '12/08/2021' AND (MOVIMENTO_DESTINO.DATALANCAMENTO not BETWEEN '12/07/2021' AND '12/08/2021' OR MOVIMENTO_DESTINO.IDMOV IS NULL ) AND TMOV.STATUS <>'C'

UNION

SELECT DISTINCT

	NULL AS 'MOVIMENTO ORIGEM',
	NULL AS 'DATA ORIGEM',
	NULL AS 'USUARIO CRIAÇÃO',
	GCCUSTO.NOME AS 'CENTRO CUSTO',
	TMOV.CODFILIAL AS 'COD FILIAL',
	NULL AS 'DATA COTAÇÃO',
	NULL AS 'CODIGO COTAÇÃO',
	NULL AS 'DESCRIÇÃO',
	TMOV.RECCREATEDBY AS 'COMPRADOR',
	TMOV.DATAEMISSAO AS 'DATA EMISSÃO OC/OCM',
	TMOV.IDMOV AS 'IDMOVIMENTO',
	TMOV.NUMEROMOV AS 'NUMERO MOVIMENTO',
	TMOV.SERIE AS 'TIPO MOVIMENTO',
	FCFO.NOMEFANTASIA AS 'NOME FANTASIA',
	FCFO.CGCCFO AS 'CNPJ/CPF',
	TCPG.NOME AS 'FORMA PAGAMENTO',
	TPRODUTO.NOMEFANTASIA AS 'PRODUTO',
	'0' AS 'DESPESA',
	'0' AS 'FRETE',
	'0' as 'MESES PARA ATENDIMENTO',
	'0' AS 'EM ABERTO',
	'1' AS 'OC/OCM GERADA SEM SC',

	'0' AS 'ATENDIDAS MESMO MÊS',

	TITMMOV.QUANTIDADETOTAL AS 'QUANTIDADE',

	TITMMOV.PRECOUNITARIO AS 'VALOR ITM COM FRETE',

	TITMMOV.PRECOUNITARIO AS 'VALOR ITM S/ FRETE',

	TITMMOV.VALORBRUTOITEMORIG AS 'VALOR TOTAL ITEM',
	'0' AS 'DESCONTO OBTIDO',
	'0' AS 'DESCONTO NEGOCIADO',
	'0' as 'SOLICITAÇÕES GERADAS',
	'0' AS 'ATENDIDA DE MES ANTERIOR'


FROM TMOV

INNER JOIN TITMMOV (NOLOCK) ON
	TMOV.IDMOV = TITMMOV.IDMOV
	AND TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA

INNER JOIN TPRODUTO (NOLOCK) ON
			TPRODUTO.IDPRD = TITMMOV.IDPRD

FULL OUTER JOIN TMOVRELAC (NOLOCK) ON
			TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV

INNER JOIN FCFO (NOLOCK) ON
	TMOV.CODCFO = FCFO.CODCFO

FULL OUTER JOIN TCPG (NOLOCK) ON
	TMOV.CODCPG = TCPG.CODCPG

INNER JOIN GCCUSTO (NOLOCK) ON
	TITMMOV.CODCCUSTO = GCCUSTO.CODCCUSTO

WHERE TMOV.SERIE IN ('OC','OCM') AND TMOV.DATAEMISSAO BETWEEN '12/07/2021' AND '12/08/2021' AND TMOVRELAC.IDMOVORIGEM IS NULL AND TMOV.STATUS <> 'C'

UNION

SELECT 

DISTINCT

	NULL AS 'MOVIMENTO ORIGEM',
	NULL AS 'DATA ORIGEM',
	NULL AS 'USUARIO CRIAÇÃO',
	NULL AS 'CENTRO CUSTO',
	NULL AS 'COD FILIAL',
	NULL AS 'DATA COTAÇÃO',
	TABELA.[COD. COTAÇÃO] AS 'CODIGO COTAÇÃO',
	NULL AS 'DESCRIÇÃO',
	NULL AS 'COMPRADOR',
	NULL AS 'DATA EMISSÃO OC/OCM',
	TABELA.IDMOV AS 'IDMOVIMENTO',
	NULL AS 'NUMERO MOVIMENTO',
	NULL AS 'TIPO MOVIMENTO',
	TABELA.[NOME FANTASIA] AS 'NOME FANTASIA',
	TABELA.[CPF/CNPJ] AS 'CNPJ/CPF',
	TABELA.[TIPO DE PAGAMENTO] AS 'FORMA PAGAMENTO',
	TABELA.[NOME PRODUTO] AS 'PRODUTO',
	'0' AS 'DESPESA',
	'0' AS 'FRETE',
	'0' as 'MESES PARA ATENDIMENTO',
	'0' AS 'EM ABERTO',
	'0' AS 'OC/OCM GERADA SEM SC',
	'0' AS 'ATENDIDAS MESMO MÊS',
	'0' AS 'QUANTIDADE',
	'0' AS 'VALOR ITM COM FRETE',
	'0' AS 'VALOR ITM S/ FRETE',
	'0' AS 'VALOR TOTAL ITEM',

case when tabela.desconto < 0 then '0'
else tabela.desconto end as 'DESCONTO'
,
CASE 
	WHEN (TABELA.MAIORVALOR - TABELA.MENORVALOR) = 0 THEN (TABELA.[VAL COTADO] - TABELA.[VAL NEGOCIADO]) * QUANTIDADENEG
	ELSE '0'
END AS 'DESCONTO NEGOCIADO',

	'0' as 'SOLICITAÇÕES GERADAS',
	'0' AS 'ATENDIDA DE MES ANTERIOR'

FROM (

SELECT DISTINCT

TPRODUTO.NOMEFANTASIA AS 'NOME PRODUTO',
ORCAMENTO.IDPRD,
ORCAMENTO.IDMOV AS 'IDMOV',
CONVERT(NVARCHAR, MOVIMENTO_ORIGEM.RECCREATEDON, 103) as 'DATA CRIAÇÃO',
ORCAMENTO.CODCOTACAO AS 'COD. COTAÇÃO',
FCFO.NOME AS 'NOME FANTASIA',
FCFO.CGCCFO AS 'CPF/CNPJ',
TCPG.NOME AS 'TIPO DE PAGAMENTO',
ORCAMENTO.VALHOMOGENEOCOTADO AS 'VAL COTADO',
ORCAMENTO.VALHOMOGENEONEGOCIADO AS 'VAL NEGOCIADO',
VALNEGOCIADO AS 'VALOR UNITARIO',
ORCAMENTO.QTDEFETIVADA,

case
	WHEN ORCAMENTO.QTDEFETIVADA <> 0 AND ORCAMENTO.QTDEFETIVADA <> ORCAMENTO.QUANTIDADENEG THEN
		(ORCAMENTO.[QTDEFETIVADA] *
		(SELECT TOP(1)
			VALCOTACAO
		FROM TCITMORCAMENTO [ITEMORC] 
		WHERE ITEMORC.CODCOTACAO = ORCAMENTO.CODCOTACAO 
		AND CFOVENCEDOR = 0 
		ORDER BY VALCOTACAO DESC)
		- (CASE
			WHEN QTDEFETIVADA <> 0 THEN CONVERT(DECIMAL(10,2), QTDEFETIVADA * VALNEGOCIADO)
			ELSE CONVERT(DECIMAL(10,2), CASE
	WHEN ORCAMENTO.QTDEFETIVADA <> 0 THEN ORCAMENTO.QTDEFETIVADA
	ELSE ORCAMENTO.QUANTIDADENEG
END * VALNEGOCIADO)
		END)) 
ELSE (SELECT TOP(1) 
	CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC 

FROM TCORCAMENTO

	INNER JOIN TCITMORCAMENTO ON
		TCITMORCAMENTO.CODCOTACAO = TCORCAMENTO.CODCOTACAO
		AND TCITMORCAMENTO.CODCFO = TCORCAMENTO.CODCFO
		AND TCITMORCAMENTO.CODCOLCFO = TCORCAMENTO.CODCOLCFO

	INNER JOIN FCFO ON
		FCFO.CODCFO = TCITMORCAMENTO.CODCFO

	INNER JOIN TCPG ON
		TCPG.CODCPG = TCORCAMENTO.CODCPGNEGOCIADA

	INNER JOIN TPRODUTO ON
		TPRODUTO.IDPRD = TCITMORCAMENTO.IDPRD

	INNER JOIN TCCOTACAO ON
		TCCOTACAO.CODCOTACAO = ORCAMENTO.CODCOTACAO
		
	WHERE TCORCAMENTO.CODCOTACAO = ORCAMENTO.CODCOTACAO  AND TCITMORCAMENTO.IDMOV = ORCAMENTO.IDMOV AND TCITMORCAMENTO.IDPRD = ORCAMENTO.IDPRD
	ORDER BY CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC DESC
	) -  (SELECT TOP(1) 
		CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC 

	FROM TCORCAMENTO

	INNER JOIN TCITMORCAMENTO ON
		TCITMORCAMENTO.CODCOTACAO = TCORCAMENTO.CODCOTACAO
		AND TCITMORCAMENTO.CODCFO = TCORCAMENTO.CODCFO
		AND TCITMORCAMENTO.CODCOLCFO = TCORCAMENTO.CODCOLCFO
			
	INNER JOIN FCFO ON
		FCFO.CODCFO = TCITMORCAMENTO.CODCFO

	INNER JOIN TCPG ON
		TCPG.CODCPG = TCORCAMENTO.CODCPGNEGOCIADA

	INNER JOIN TPRODUTO ON
		TPRODUTO.IDPRD = TCITMORCAMENTO.IDPRD

	INNER JOIN TCCOTACAO ON
		TCCOTACAO.CODCOTACAO = ORCAMENTO.CODCOTACAO
	
	WHERE TCORCAMENTO.CODCOTACAO = ORCAMENTO.CODCOTACAO		AND TCITMORCAMENTO.IDMOV = ORCAMENTO.IDMOV AND TCITMORCAMENTO.IDPRD = ORCAMENTO.IDPRD AND VALCOTACAO * TCITMORCAMENTO.QUANTIDADEORC > 0 
	AND TCITMORCAMENTO.CFOVENCEDOR = 1
	ORDER BY CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC ASC
	) end as 'desconto',

CASE
	WHEN ORCAMENTO.QTDEFETIVADA <> 0 THEN ORCAMENTO.QTDEFETIVADA
	ELSE ORCAMENTO.QUANTIDADENEG
END AS 'QTD',

CASE
	WHEN QTDEFETIVADA <> 0 THEN QTDEFETIVADA * ORCAMENTO.VALHOMOGENEONEGOCIADO
	ELSE QUANTIDADENEG * ORCAMENTO.VALHOMOGENEONEGOCIADO
END 'VALOR TOTAL',

MOVIMENTO_ORIGEM.CODFILIAL,
TCCOTACAO.DATCOTACAO AS 'DATA COTACAO',
TCORCAMENTO.DESPESA AS 'DESPESA',
TCORCAMENTO.VALORFRETE AS 'FRETE',
TCCOTACAO.STSCOTACAO AS 'STATUS',
ORCAMENTO.CFOVENCEDOR AS 'VENCEDOR',
ORCAMENTO.QUANTIDADENEG,



(SELECT TOP(1) 
	CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC 

FROM TCORCAMENTO

	INNER JOIN TCITMORCAMENTO ON
		TCITMORCAMENTO.CODCOTACAO = TCORCAMENTO.CODCOTACAO
		AND TCITMORCAMENTO.CODCFO = TCORCAMENTO.CODCFO
		AND TCITMORCAMENTO.CODCOLCFO = TCORCAMENTO.CODCOLCFO

	INNER JOIN FCFO ON
		FCFO.CODCFO = TCITMORCAMENTO.CODCFO

	INNER JOIN TCPG ON
		TCPG.CODCPG = TCORCAMENTO.CODCPGNEGOCIADA

	INNER JOIN TPRODUTO ON
		TPRODUTO.IDPRD = TCITMORCAMENTO.IDPRD

	INNER JOIN TCCOTACAO ON
		TCCOTACAO.CODCOTACAO = ORCAMENTO.CODCOTACAO
		
	WHERE TCORCAMENTO.CODCOTACAO = ORCAMENTO.CODCOTACAO  AND TCITMORCAMENTO.IDMOV = ORCAMENTO.IDMOV AND TCITMORCAMENTO.IDPRD = ORCAMENTO.IDPRD
	ORDER BY CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC DESC
	) AS 'MAIORVALOR',

 (SELECT TOP(1) 
		CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC 

	FROM TCORCAMENTO

	INNER JOIN TCITMORCAMENTO ON
		TCITMORCAMENTO.CODCOTACAO = TCORCAMENTO.CODCOTACAO
		AND TCITMORCAMENTO.CODCFO = TCORCAMENTO.CODCFO
		AND TCITMORCAMENTO.CODCOLCFO = TCORCAMENTO.CODCOLCFO
			
	INNER JOIN FCFO ON
		FCFO.CODCFO = TCITMORCAMENTO.CODCFO

	INNER JOIN TCPG ON
		TCPG.CODCPG = TCORCAMENTO.CODCPGNEGOCIADA

	INNER JOIN TPRODUTO ON
		TPRODUTO.IDPRD = TCITMORCAMENTO.IDPRD

	INNER JOIN TCCOTACAO ON
		TCCOTACAO.CODCOTACAO = ORCAMENTO.CODCOTACAO
	
	WHERE TCORCAMENTO.CODCOTACAO = ORCAMENTO.CODCOTACAO		AND TCITMORCAMENTO.IDMOV = ORCAMENTO.IDMOV AND TCITMORCAMENTO.IDPRD = ORCAMENTO.IDPRD AND VALCOTACAO * TCITMORCAMENTO.QUANTIDADEORC > 0 
	AND TCITMORCAMENTO.CFOVENCEDOR = 1
	ORDER BY CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC ASC
	) AS 'MENORVALOR'


FROM TCITMORCAMENTO AS ORCAMENTO

	INNER JOIN TCORCAMENTO ON
		TCORCAMENTO.CODCOTACAO = ORCAMENTO.CODCOTACAO
		AND TCORCAMENTO.CODCFO = ORCAMENTO.CODCFO
		AND TCORCAMENTO.CODCOLCFO = ORCAMENTO.CODCOLCFO

	INNER JOIN FCFO ON
		FCFO.CODCFO = ORCAMENTO.CODCFO

	INNER JOIN TCPG ON
		TCPG.CODCPG = ORCAMENTO.CODCPGNEGOCIADA 

	INNER JOIN TPRODUTO ON
		TPRODUTO.IDPRD = ORCAMENTO.IDPRD

	INNER JOIN TCCOTACAO ON
		TCCOTACAO.CODCOTACAO = ORCAMENTO.CODCOTACAO

	INNER JOIN TMOVRELAC ON
			TMOVRELAC.IDMOVORIGEM = ORCAMENTO.IDMOV

	INNER JOIN TMOV MOVIMENTO_ORIGEM ON
			MOVIMENTO_ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM

	) TABELA

WHERE TABELA.[VENCEDOR] = 1 AND TABELA.[STATUS] <> 7 AND TABELA.[DATA COTACAO] BETWEEN '12/07/2021' AND '12/08/2021'
UNION

SELECT DISTINCT

	TMOV.IDMOV AS 'MOVIMENTO ORIGEM',
	TMOV.DATACRIACAO AS 'DATA ORIGEM',
	TMOV.RECCREATEDBY AS 'USUARIO CRIAÇÃO',
	GCCUSTO.NOME AS 'CENTRO CUSTO',
	TMOV.CODFILIAL AS 'COD FILIAL',
	TCCOTACAO.DATCOTACAO AS 'DATA COTAÇÃO',
	TCCOTACAO.CODCOTACAO AS 'CODIGO COTAÇÃO',
	TCCOTACAO.DESCRICAO AS 'DESCRIÇÃO',
	TVEN.NOME AS 'COMPRADOR',
	MOVIMENTO_DESTINO.DATAEMISSAO AS 'DATA EMISSÃO OC/OCM',
	MOVIMENTO_DESTINO.IDMOV AS 'IDMOVIMENTO',
	MOVIMENTO_DESTINO.NUMEROMOV AS 'NUMERO MOVIMENTO',
	MOVIMENTO_DESTINO.SERIE AS 'TIPO MOVIMENTO',
	FCFO.NOMEFANTASIA AS 'NOME FANTASIA',
	FCFO.CGCCFO AS 'CNPJ/CPF',
	TCPG.NOME AS 'FORMA PAGAMENTO',
	TPRODUTO.NOMEFANTASIA AS 'PRODUTO',
	TCORCAMENTO.DESPESA AS 'DESPESA',
	TCORCAMENTO.VALORFRETE AS 'FRETE',
	DATEDIFF(MONTH, TMOV.DATACRIACAO, MOVIMENTO_DESTINO.DATAEMISSAO) as 'MESES PARA ATENDIMENTO',
	'0' AS 'EM ABERTO',
	'0' AS 'OC/OCM GERADA SEM SC',
	
CASE WHEN DATEDIFF(MONTH, TMOV.DATACRIACAO, MOVIMENTO_DESTINO.DATAEMISSAO) <> 0 THEN '0'
		ELSE '1' END AS 'ATENDIDAS MESMO MÊS',

	CASE WHEN  (TCITMORCAMENTO.QTDEFETIVADA <> 0 AND ORIG.QUANTIDADETOTAL < TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QTDEFETIVADA) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  )
		 WHEN  (TCITMORCAMENTO.QTDEFETIVADA = 0 AND ORIG.QUANTIDADETOTAL < TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QUANTIDADENEG) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  )
		WHEN (TCITMORCAMENTO.QTDEFETIVADA <> 0 AND ORIG.QUANTIDADETOTAL >= TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QTDEFETIVADA) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  ) 
		WHEN (TCITMORCAMENTO.QTDEFETIVADA = 0 AND ORIG.QUANTIDADETOTAL >= TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QUANTIDADENEG) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  ) END AS 'QUANTIDADE',
		

	(SELECT TOP 1 CONVERT(DECIMAL(10,4),A.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO A WHERE A.IDMOV = TMOV.IDMOV AND A.IDPRD = TITMMOV.IDPRD AND A.CFOVENCEDOR <> 0 AND A.VALHOMOGENEONEGOCIADO <> 0 AND TCCOTACAO.STSCOTACAO <> 7)  AS 'VALOR ITM COM FRETE',

	(SELECT TOP 1 CONVERT(DECIMAL(10,4),B.VALEQUALIZADONEG) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  )  AS 'VALOR ITM S/ FRETE',
		
	CASE 
		WHEN  (TCITMORCAMENTO.QTDEFETIVADA <> 0 AND ORIG.QUANTIDADETOTAL < TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
			THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QTDEFETIVADA) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7) * 
				(SELECT TOP 1 CONVERT(DECIMAL(10,4),C.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO C WHERE C.IDMOV = TMOV.IDMOV AND C.IDPRD = TITMMOV.IDPRD AND C.CFOVENCEDOR <> 0 AND C.VALHOMOGENEOCOTADO <> '0' AND TCCOTACAO.STSCOTACAO <> 7 )
		 WHEN  (TCITMORCAMENTO.QTDEFETIVADA = 0 AND ORIG.QUANTIDADETOTAL < TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
			THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QUANTIDADENEG) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7) * 
			(SELECT TOP 1 CONVERT(DECIMAL(10,4),C.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO C WHERE C.IDMOV = TMOV.IDMOV AND C.IDPRD = TITMMOV.IDPRD AND C.CFOVENCEDOR <> 0 AND C.VALHOMOGENEOCOTADO <> '0' AND TCCOTACAO.STSCOTACAO <> 7 )
		WHEN (TCITMORCAMENTO.QTDEFETIVADA <> 0 AND ORIG.QUANTIDADETOTAL >= TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
			THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QTDEFETIVADA) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  ) * 
			(SELECT TOP 1 CONVERT(DECIMAL(10,4),C.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO C WHERE C.IDMOV = TMOV.IDMOV AND C.IDPRD = TITMMOV.IDPRD AND C.CFOVENCEDOR <> 0 AND C.VALHOMOGENEOCOTADO <> '0' AND TCCOTACAO.STSCOTACAO <> 7 ) 
		WHEN (TCITMORCAMENTO.QTDEFETIVADA = 0 AND ORIG.QUANTIDADETOTAL >= TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) 
			THEN (SELECT TOP 1 CONVERT(DECIMAL(10,4),B.QUANTIDADENEG) FROM TCITMORCAMENTO B WHERE B.IDMOV = TMOV.IDMOV AND B.IDPRD = TITMMOV.IDPRD AND B.CFOVENCEDOR = 1  AND B.VALEQUALIZADONEG <> 0 AND TCCOTACAO.STSCOTACAO <> 7  )  * 
			(SELECT TOP 1 CONVERT(DECIMAL(10,4),C.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO C WHERE C.IDMOV = TMOV.IDMOV AND C.IDPRD = TITMMOV.IDPRD AND C.CFOVENCEDOR <> 0 AND C.VALHOMOGENEOCOTADO <> '0' AND TCCOTACAO.STSCOTACAO <> 7 )
		END	AS 'VALOR TOTAL ITEM',
	
	'0' AS 'DESCONTO OBTIDO',
	'0' AS 'DESCONTO NEGOCIADO',

	'0' AS 'SOLICITAÇÕES GERADAS',

	'1' AS 'ATENDIDA DE MES ANTERIOR'
	

FROM TMOV
	
	INNER JOIN TITMMOV ORIG ON
			TMOV.IDMOV = ORIG.IDMOV

	INNER JOIN TMOVRELAC ON
			TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV

	INNER JOIN TMOV MOVIMENTO_DESTINO ON
			MOVIMENTO_DESTINO.IDMOV = TMOVRELAC.IDMOVDESTINO

	INNER JOIN TITMMOV (NOLOCK) ON
			MOVIMENTO_DESTINO.IDMOV = TITMMOV.IDMOV
		AND TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA

	INNER JOIN TPRODUTO (NOLOCK) ON
			TPRODUTO.IDPRD = TITMMOV.IDPRD

	INNER JOIN TCCOTACAOITMMOV (NOLOCK) ON
			TITMMOV.IDMOV = TCCOTACAOITMMOV.IDMOV 

	INNER JOIN TCCOTACAO (NOLOCK) ON
			TCCOTACAOITMMOV.CODCOTACAO = TCCOTACAO.CODCOTACAO

	INNER JOIN TCITMORCAMENTO (NOLOCK) ON
			TCCOTACAO.CODCOTACAO = TCITMORCAMENTO.CODCOTACAO

INNER JOIN TCORCAMENTO ON
	TCORCAMENTO.CODCOTACAO = TCITMORCAMENTO.CODCOTACAO
	AND TCORCAMENTO.CODCFO = TCITMORCAMENTO.CODCFO
	AND TCORCAMENTO.CODCOLCFO = TCITMORCAMENTO.CODCOLCFO

INNER JOIN GCCUSTO (NOLOCK) ON
	TITMMOV.CODCCUSTO = GCCUSTO.CODCCUSTO

INNER JOIN TVEN (NOLOCK) ON
	TCCOTACAO.CODCOMPRADOR = TVEN.CODVEN



INNER JOIN FCFO (NOLOCK) ON
	MOVIMENTO_DESTINO.CODCFO = FCFO.CODCFO

FULL OUTER JOIN TCPG (NOLOCK) ON
	MOVIMENTO_DESTINO.CODCPG = TCPG.CODCPG

/*WHERE TMOV.SERIE IN ('SC') AND TCITMORCAMENTO.CFOITEMVENCEDORCOT <> 0 AND TMOV.RECCREATEDON NOT BETWEEN :DATA_INICIAL AND :DATA_FINAL  AND MOVIMENTO_DESTINO.RECCREATEDON BETWEEN :DATA_INICIAL AND :DATA_FINAL AND (SELECT P.PRECOUNITARIO FROM TITMMOV P WHERE P.CODCOLIGADA = MOVIMENTO_DESTINO.CODCOLIGADA AND P.IDMOV = MOVIMENTO_DESTINO.IDMOV AND P.IDPRD = TITMMOV.IDPRD) IS NOT NULL*/

WHERE ((SELECT TOP 1 CONVERT(DECIMAL(10,4),E.VALHOMOGENEONEGOCIADO) FROM TCITMORCAMENTO E WHERE E.IDMOV = TMOV.IDMOV AND E.IDPRD = TITMMOV.IDPRD AND E.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) * TITMMOV.QUANTIDADETOTAL) IS NOT NULL 
AND TMOV.SERIE IN ('SC') AND TCITMORCAMENTO.CFOVENCEDOR <> 0 AND TMOV.DATACRIACAO not BETWEEN '12/07/2021' AND '12/08/2021' AND MOVIMENTO_DESTINO.DATACRIACAO BETWEEN '12/07/2021' AND '12/08/2021' AND TCITMORCAMENTO.CFOVENCEDOR = 1
AND (SELECT F.PRECOUNITARIO FROM TITMMOV F WHERE F.CODCOLIGADA = MOVIMENTO_DESTINO.CODCOLIGADA AND F.IDMOV = MOVIMENTO_DESTINO.IDMOV AND F.IDPRD = TITMMOV.IDPRD and TCCOTACAO.STSCOTACAO <> 7) IS NOT NULL  
AND CASE WHEN  (ORIG.QUANTIDADETOTAL < TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) THEN ORIG.QUANTIDADETOTAL 
		WHEN ( ORIG.QUANTIDADETOTAL >= TITMMOV.QUANTIDADETOTAL AND ORIG.IDPRD = TITMMOV.IDPRD AND TCITMORCAMENTO.CFOVENCEDOR <> 0 and TCCOTACAO.STSCOTACAO <> 7 ) THEN TITMMOV.QUANTIDADETOTAL END IS NOT NULL
AND TCCOTACAO.STSCOTACAO <> 7*/