SELECT DISTINCT

SHABILITACAOALUNO.LIVROREGISTRO AS 'LIVRO',
SHABILITACAOALUNO.REGISTROCONCLUSAO AS 'REGISTRO',
SHABILITACAOALUNO.PROCESSOREGISTRO AS 'PROCESSO',
SHABILITACAOALUNO.PAGINAREGISTRO AS 'FOLHA',
SHABILITACAOALUNO.CODINSTDIPLOMA,
PPESSOA.NOME AS 'NOME DO CONCLUINTE',
CONVERT(NVARCHAR, PPESSOA.DTNASCIMENTO, 103) AS 'DATA DE NASCIMENTO',
PPESSOA.CIDADE AS 'CIDADE/UF',
PCODNACAO.DESCRICAO AS 'NACIONALIDADE',
PPESSOA.CARTIDENTIDADE AS 'IDENTIDADE',
CONVERT(NVARCHAR,PPESSOA.DTEXPCML, 103) AS 'DATA DE EXPEDIÇÃO',
PPESSOA.ORGEMISSORIDENT AS 'ORGÃO EMISSOR',
PPESSOA.UFCARTIDENT AS 'UF',
SCURSO.NOME AS 'CURSO',
SCAMPUS.DESCRICAO AS 'CAMPUS',
GFILIAL.NOMEFANTASIA AS 'INSTITUIÇÃO',
SMODALIDADECURSO.DESCRICAO AS 'MODALIDADE',
CONVERT(NVARCHAR, SHABILITACAOALUNO.DTCONCLUSAOCURSO, 103) AS 'DATA DA CONCLUSÃO',
CONVERT(NVARCHAR, SHABILITACAOALUNO.DTCOLACAOGRAU, 103) AS 'DATA COLAÇÃO DE GRAU',
CONVERT(NVARCHAR, SHABILITACAOALUNO.DTEMISDIPLOMA, 103) AS 'DATA DA EXPEDIÇÃO DO DIPLOMA',
KELLY.NOME AS 'RESPONSÁVEL PELO REGISTRO',
'Responsável pelo setor de registros' AS ' CARGO/FUNÇÃO',
APARECIDA.CPF AS 'CPF SECRETÁROA ACADÊMICA',
CONVERT(NVARCHAR, SAUTORIZACAOCURSO.DTAUTORIZACAO, 103) AS 'DTAUTORIZACAO',
CONVERT(NVARCHAR, SAUTORIZACAOCURSO.DTDOUAUTORIZACAO, 103) AS 'DTDOUAUTORIZACAO',
CONVERT(NVARCHAR, SAUTORIZACAOCURSO.DTRECONHECIMENTO, 103) AS 'DTRECONHECIMENTO',
CONVERT(NVARCHAR, SAUTORIZACAOCURSO.DTDOURECONHECIMENTO, 103) AS 'DTDOURECONHECIMENTO',
SAUTORIZACAOCURSO.PORTAUTORIZACAO,
SAUTORIZACAOCURSO.PORTRECONHECIMENTO



FROM  SALUNO 

		INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA

		INNER JOIN PPESSOA KELLY (NOLOCK) ON
			KELLY.CODIGO = 35987

		INNER JOIN PPESSOA APARECIDA (NOLOCK) ON
			APARECIDA.CODIGO = 37595

		INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.RA = SALUNO.RA

		INNER JOIN SMATRICULA (NOLOCK) ON
			SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SMATRICULA.IDPERLET  = SMATRICPL.IDPERLET

		INNER JOIN SHABILITACAOALUNO (NOLOCK) ON
			SHABILITACAOALUNO.RA = SALUNO.RA

		INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAOALUNO.CODCOLIGADA
			AND	SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL

		INNER JOIN SHABILITACAOFILIALCAMPUS (NOLOCK) ON
			SHABILITACAOFILIALCAMPUS.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

		INNER JOIN SAUTORIZACAOCURSO (NOLOCK) ON
			SAUTORIZACAOCURSO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

		INNER JOIN SCAMPUS (NOLOCK) ON
			SHABILITACAOFILIALCAMPUS.CODCAMPUS = SCAMPUS.CODCAMPUS

		INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO

		INNER JOIN SMODALIDADECURSO (NOLOCK) ON
			SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA
			AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO

		INNER JOIN GFILIAL (NOLOCK) ON	
			GFILIAL.CODFILIAL = SMATRICPL.CODFILIAL

		INNER JOIN PCODNACAO (NOLOCK) ON
			PPESSOA.NACIONALIDADE = PCODNACAO.CODCLIENTE

WHERE SCURSO.CODCURSO = '1'
AND SALUNO.RA = 200610263


