select DISTINCT

CASE
	WHEN SMATRICPL.CODFILIAL = 1 THEN 'MATRIZ - JUAZEIRO'
	WHEN SMATRICPL.CODFILIAL = 4 THEN 'FILIAL - ARARIPINA'
END	[FILIAL],
SALUNO.RA,
PPESSOA.NOME [ALUNO],
SSTATUS.DESCRICAO as 'Status do Curso',
SCONTRATO.CODCONTRATO,
CONVERT(varchar, SCONTRATO.DTASSINATURA, 103) AS 'DATA ASSINATURA',
SSERVICO.NOME [Servico],

CASE WHEN SSERVICO.CODSERVICO IN ('302','326','350','374','398','436','437','438','440','446','447','448') then 'Mensalidade'
 else 'Taxa' end as 'Tipo Serviço',

SPARCELA.PARCELA,
SPLETIVO.CODPERLET,

case when SPLETIVO.CODPERLET like '%pos%' then 'Pós'
	else 'GRADUAÇÃO' END 'TIPO',

FLAN.IDLAN,
CONVERT(varchar, flan.DATAVENCIMENTO, 103) as 'DATA VENCIMENTO',
CONVERT(varchar, FLAN.RECCREATEDON, 103) AS 'DATA CRIAÇÃO boleto',
CONVERT(varchar, FLAN.RECMODIFIEDON, 103) AS 'DATA ALTERAÇÃO boleto',

case when FLAN.STATUSLAN = 0 then 'ABERTO' 
	 when FLAN.STATUSLAN = 1 then 'BAIXADO'
	when FLAN.STATUSLAN = 2 then 'CANCELADO'
	when FLAN.STATUSLAN = 3 then 'BAIXADOS POR ACORDO'
	when FLAN.STATUSLAN = 4 then 'BAIXADO PARCIALMENTE'
END 'STATUS BOLETO',

CAST(YEAR(FLAN.MESDECOMPETENCIA) AS VARCHAR(4)) + '/' + RIGHT('0' + CAST(MONTH(FLAN.MESDECOMPETENCIA) AS VARCHAR(2)),2) AS COMPETENCIA,

SCURSO.NOME [Curso],
SMODALIDADECURSO.DESCRICAO AS 'MODALIDADE',
(SELECT TOP 1 CONVERT(varchar,slogpletivo.DTALTERACAO , 103)
		FROM slogpletivo 
					INNER JOIN SMATRICPL (NOLOCK) ON 
					SMATRICPL.RA = slogpletivo.RA
			where SMATRICPL.RA = SCONTRATO.RA
				AND SMATRICPL.IDPERLET = SCONTRATO.IDPERLET
		ORDER BY slogpletivo.DTALTERACAO DESC) 'ÚLTIMA DATA ALTERAÇÃO',

(SELECT FLOOR(SUM(SMATRICULA.NUMCREDITOSCOB) / 6)
          FROM SMATRICULA (NOLOCK)
               INNER JOIN STURMADISC  (NOLOCK)
         	           ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA 
			          AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
         WHERE SMATRICULA.CODCOLIGADA = SCONTRATO.CODCOLIGADA
           AND SMATRICULA.RA          = SCONTRATO.RA
           AND SMATRICULA.IDPERLET    = SCONTRATO.IDPERLET
		   AND SMATRICULA.CODSTATUS in ('19','2')) as 'TOTALCREDITOS_FIN',

(SELECT top 1 CONVERT(DECIMAL(10,2),SDISCGRADE.VALORCREDITO) FROM SMATRICPL
	INNER JOIN SMATRICULA ON
			SMATRICULA.RA = SMATRICPL.RA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
	INNER JOIN STURMADISC ON
			STURMADISC.IDPERLET = SMATRICULA.IDPERLET
		AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SDISCIPLINA (NOLOCK) ON
			SDISCIPLINA.CODDISC = STURMADISC.CODDISC	
	INNER JOIN SDISCGRADE (NOLOCK) ON
			SDISCGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO	
		AND SDISCGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
		AND SDISCGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
WHERE SMATRICULA.CODCOLIGADA = SCONTRATO.CODCOLIGADA
  AND SMATRICULA.RA          = SCONTRATO.RA
  AND SMATRICULA.IDPERLET    = SCONTRATO.IDPERLET
  AND SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
  AND SMATRICPL.CODSTATUS IN (12,101,111)
  AND SMATRICULA.CODSTATUS = 19) 'Valor Credito',

CONVERT(DECIMAL(10,2),FLAN.VALORORIGINAL) AS 'VALOR ORIGINAL',

CASE WHEN (FLAN.VALORORIGINAL - FLAN.VALOROP1 - FLAN.VALORDESCONTO - FLAN.VALOROP2) = 0 AND FCFO.NOMEFANTASIA NOT IN ('FIES - FINANCIAMENTO ESTUDANTIL','PROUNI - PROGRAMA UNIVERSIDADE PARA TODOS', 'CAIXA ECONOMICA FEDERAL', 'PREFEITURA DE JUAZEIRO DO NORTE','FACULDADE PARAÍSO DO CEARÁ') or SBOLSAALUNO.CODBOLSA = '224' THEN '0'
	when FCFO.NOMEFANTASIA in ('FIES - FINANCIAMENTO ESTUDANTIL','PROUNI - PROGRAMA UNIVERSIDADE PARA TODOS', 'CAIXA ECONOMICA FEDERAL', 'PREFEITURA DE JUAZEIRO DO NORTE','FACULDADE PARAÍSO DO CEARÁ') then '0'
	ELSE CONVERT(DECIMAL(10,2),FLAN.VALORORIGINAL - FLAN.VALOROP1 - FLAN.VALORDESCONTO - FLAN.VALOROP2) END AS 'VALOR ORIGINAL REAL',
	

CASE WHEN (SBOLSAALUNO.CODBOLSA in ('220','213')and SSERVICO.CODSERVICO IN ('302','326','350','374','398','436','437','438','440','446','447','448') and fcfo.NOMEFANTASIA NOT IN ( 'FIES - FINANCIAMENTO ESTUDANTIL','PROUNI - PROGRAMA UNIVERSIDADE PARA TODOS', 'CAIXA ECONOMICA FEDERAL', 'PREFEITURA DE JUAZEIRO DO NORTE','FACULDADE PARAÍSO DO CEARÁ')) THEN CONVERT(DECIMAL(10,2),((FLAN.VALORORIGINAL - FLAN.VALOROP1 - FLAN.VALORDESCONTO - FLAN.VALOROP2)*'0.05'))
     else '0' END AS 'BOLSA5+5',

CASE WHEN EXISTS (SELECT 1
	                       FROM SBOLSAALUNO S (NOLOCK)
	                       WHERE S.CODCOLIGADA = SCONTRATO.CODCOLIGADA
						    AND S.RA          = SCONTRATO.RA 
							AND S.IDPERLET    = SCONTRATO.IDPERLET
							AND S.DESCONTO    <> 0
							AND ((SPARCELA.PARCELA BETWEEN S.PARCELAINICIAL AND S.PARCELAFINAL) OR SBOLSAALUNO.DTFIM >= '26-08-2021')
							AND FCFO.NOMEFANTASIA  = 'PROUNI - PROGRAMA UNIVERSIDADE PARA TODOS' )
            THEN CONVERT(DECIMAL(10,2),FLAN.VALORORIGINAL) else '0' END AS 'PROUNI',

CASE WHEN EXISTS (SELECT 1
	                       FROM SBOLSAALUNO S (NOLOCK)
	                       WHERE S.CODCOLIGADA = SCONTRATO.CODCOLIGADA
						    AND S.RA          = SCONTRATO.RA 
							AND S.IDPERLET    = SCONTRATO.IDPERLET
							AND S.DESCONTO    <> 0
							AND ((SPARCELA.PARCELA BETWEEN S.PARCELAINICIAL AND S.PARCELAFINAL) OR SBOLSAALUNO.DTFIM >= '26-08-2021')
							/*AND S.CODBOLSA <> '224'AND S.CODBOLSA <> '211'*/
							AND (S.CODBOLSA = '286' OR S.CODBOLSA = '213')
							AND FCFO.NOMEFANTASIA = 'FIES - FINANCIAMENTO ESTUDANTIL' )
            THEN CONVERT(DECIMAL(10,2),FLAN.VALORORIGINAL) else '0' END AS 'FIES',

CASE WHEN EXISTS (SELECT 1
	                       FROM SBOLSAALUNO S (NOLOCK)
	                       WHERE S.CODCOLIGADA = SCONTRATO.CODCOLIGADA
						    AND S.RA          = SCONTRATO.RA 
							AND S.IDPERLET    = SCONTRATO.IDPERLET
							AND S.DESCONTO    <> 0
							AND ((SPARCELA.PARCELA BETWEEN S.PARCELAINICIAL AND S.PARCELAFINAL) OR SBOLSAALUNO.DTFIM >= '26-08-2021')
							AND FCFO.NOMEFANTASIA = 'CAIXA ECONOMICA FEDERAL' 
							AND S.CODBOLSA = 231)
            THEN CONVERT(DECIMAL(10,2),FLAN.VALORORIGINAL) else '0' END AS 'CAIXA',

CASE WHEN EXISTS (SELECT 1
	                       FROM SBOLSAALUNO S (NOLOCK)
	                       WHERE S.CODCOLIGADA = SCONTRATO.CODCOLIGADA
						    AND S.RA          = SCONTRATO.RA 
							AND S.IDPERLET    = SCONTRATO.IDPERLET
							AND S.DESCONTO    <> 0
							AND ((SPARCELA.PARCELA BETWEEN S.PARCELAINICIAL AND S.PARCELAFINAL) OR SBOLSAALUNO.DTFIM >= '26-08-2021')
							AND FCFO.NOMEFANTASIA = 'PREFEITURA DE JUAZEIRO DO NORTE' )
            THEN CONVERT(DECIMAL(10,2),FLAN.VALORORIGINAL) else '0' END AS 'PREFEITURA JUA',

CASE WHEN EXISTS (SELECT 1
	                       FROM SBOLSAALUNO S (NOLOCK)
	                       WHERE S.CODCOLIGADA = SCONTRATO.CODCOLIGADA
						    AND S.RA          = SCONTRATO.RA 
							AND S.IDPERLET    = SCONTRATO.IDPERLET
							AND S.DESCONTO    <> 0
							AND ((SPARCELA.PARCELA BETWEEN S.PARCELAINICIAL AND S.PARCELAFINAL) OR SBOLSAALUNO.DTFIM >= '26-08-2021')
							AND (FCFO.NOMEFANTASIA = 'FACULDADE PARAÍSO DO CEARÁ' OR FCFO.NOMEFANTASIA = 'PREFEITURA DE JUAZEIRO DO NORTE') )
            THEN CONVERT(DECIMAL(10,2),FLAN.VALORORIGINAL) else '0' END AS 'FAP',

CASE WHEN EXISTS (SELECT 1
	                       FROM SBOLSAALUNO S (NOLOCK)
	                       WHERE S.CODCOLIGADA = SCONTRATO.CODCOLIGADA
						    AND S.RA          = SCONTRATO.RA 
							AND S.IDPERLET    = SCONTRATO.IDPERLET
							AND S.DESCONTO    <> 0
							AND FCFO.NOMEFANTASIA IN('FIES - FINANCIAMENTO ESTUDANTIL')
							AND ((SPARCELA.PARCELA BETWEEN S.PARCELAINICIAL AND S.PARCELAFINAL) OR SBOLSAALUNO.DTFIM >= '26-08-2021')
							AND S.CODBOLSA = '224')
            THEN CONVERT(DECIMAL(10,2),FLAN.VALORORIGINAL)
            else '0' END AS 'PFIES',
CASE 
	WHEN FLAN.VALOROP2 = FLAN.VALORORIGINAL 
	AND FCFO.NOMEFANTASIA IN('FIES - FINANCIAMENTO ESTUDANTIL','PROUNI - PROGRAMA UNIVERSIDADE PARA TODOS', 'CAIXA ECONOMICA FEDERAL', 'PREFEITURA DE JUAZEIRO DO NORTE','FACULDADE PARAÍSO DO CEARÁ') 
	OR SBOLSAALUNO.CODBOLSA = '224' 
	OR SBOLSAALUNO.CODBOLSA = '211' THEN '0'
	WHEN FLAN.VALORDESCONTO = FLAN.VALORORIGINAL AND SBOLSAALUNO.CODBOLSA = 315 THEN CONVERT(DECIMAL(10,2),FLAN.VALORDESCONTO)
	ELSE CONVERT(DECIMAL(10,2),FLAN.VALOROP2) END AS 'BOLSA',
	
CASE 
	WHEN NOT EXISTS (SELECT 1
	                       FROM SBOLSAALUNO S (NOLOCK)
	                       WHERE S.CODCOLIGADA = SCONTRATO.CODCOLIGADA
						    AND S.RA          = SCONTRATO.RA 
							AND S.IDPERLET    = SCONTRATO.IDPERLET
							AND S.DESCONTO    <> 0
							AND ((SPARCELA.PARCELA BETWEEN S.PARCELAINICIAL AND S.PARCELAFINAL) OR SBOLSAALUNO.DTFIM >= '26-08-2021')
							AND S.CODBOLSA = '315')
            THEN CONVERT(DECIMAL(10,2),FLAN.VALORDESCONTO)
    END AS 'Desconto'

/*CONVERT(DECIMAL(10,2),FLAN.VALORDESCONTO) as 'Desconto'*/

from FLAN (nolock) 
	
		inner join SLAN (nolock) on
				   slan.CODCOLIGADA = flan.CODCOLIGADA
			   and slan.IDLAN       = flan.IDLAN
			   
		inner join SPARCELA (nolock) on
		           SPARCELA.CODCOLIGADA = slan.CODCOLIGADA and
		           SPARCELA.IDPARCELA   = slan.IDPARCELA
		           
		           
		inner join SALUNO (nolock) on
			       SALUNO.CODCOLIGADA = SPARCELA.CODCOLIGADA
			   and SALUNO.RA          = SPARCELA.RA
			   
		inner join PPESSOA (nolock) on
		           PPESSOA.CODIGO = SALUNO.CODPESSOA
		           
		inner join FCFO (nolock) on
			       fcfo.CODCOLIGADA = flan.CODCOLCFO
			   and FCFO.CODCFO      = flan.CODCFO
			   
		inner join SSERVICO (nolock) on
				   SSERVICO.CODCOLIGADA = SPARCELA.CODCOLIGADA
			   and SSERVICO.CODSERVICO  = SPARCELA.CODSERVICO
			   
		inner join SCONTRATO (nolock) on
				   SCONTRATO.CODCOLIGADA = SPARCELA.CODCOLIGADA
			   and SCONTRATO.RA          = SPARCELA.RA
			   and SCONTRATO.CODCONTRATO = SPARCELA.CODCONTRATO
			   and SCONTRATO.IDPERLET    = SPARCELA.IDPERLET
				
		INNER JOIN SPLETIVO (NOLOCK)
				ON SCONTRATO.CODCOLIGADA = SPLETIVO.CODCOLIGADA
				AND SCONTRATO.IDPERLET = SPLETIVO.IDPERLET
   
		inner join SHABILITACAOFILIAL (nolock)
			INNER JOIN STURNO (NOLOCK)
				ON SHABILITACAOFILIAL.CODCOLIGADA = STURNO.CODCOLIGADA
				AND SHABILITACAOFILIAL.CODTURNO = STURNO.CODTURNO
			    on  SHABILITACAOFILIAL.CODCOLIGADA = SCONTRATO.CODCOLIGADA 
			   and SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
			   
		inner join SCURSO (nolock) on
		           SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		       and SCURSO.CODCURSO    = SHABILITACAOFILIAL.CODCURSO

		INNER JOIN SMODALIDADECURSO (NOLOCK) ON
				SCURSO.CODMODALIDADECURSO = SMODALIDADECURSO.CODMODALIDADECURSO
		
		INNER JOIN SMATRICPL (NOLOCK) ON
		           SMATRICPL.CODCOLIGADA = SCONTRATO.CODCOLIGADA
		       AND SMATRICPL.RA          = SCONTRATO.RA
		       AND SMATRICPL.IDPERLET    = SCONTRATO.IDPERLET
		       AND SMATRICPL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
		
		INNER JOIN SSTATUS (NOLOCK) ON
		           SSTATUS.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		       AND SSTATUS.CODSTATUS   = SMATRICPL.CODSTATUS
		
		inner join FLANCOMPL (nolock) on           
		        FLANCOMPL.CODCOLIGADA = FLAN.CODCOLIGADA
		    AND FLANCOMPL.IDLAN = FLAN.IDLAN

		left JOIN SBOLSAALUNO (NOLOCK) ON
				SCONTRATO.IDPERLET = SBOLSAALUNO.IDPERLET AND
				SALUNO.RA = SBOLSAALUNO.RA



WHERE SSERVICO.NOME <> 'ACORDO' and flan.STATUSLAN <> 2  AND FLAN.MESDECOMPETENCIA >= '01-08-2021' AND FLAN.MESDECOMPETENCIA <= '26-08-2021'
and SMATRICPL.CODSTATUS <> '125'  

/* UNICA ALTERAÇÃO 09/08 */
/*AND SCONTRATO.DTASSINATURA BETWEEN :Data_Inicial AND :Data_Final*/
/* FIM DA UNICA ALTER~ÇÃO*/
and SCURSO.CODCURSO in ('1','10','101','102','103','104','105','106','107','108','11','12','13','14','15','16','17','18','19','2','20','201','2011','2013113','2013211',
'2013212','2013222','2015100','2015101','2015102','2015103','2017101','2017102','21','212011','22','23','24','25','26','27','28','29','3','30','31','32','33','34',
'35','36','37','38','39','4','40','41','42','43','44','45','46','47','48','5','6','7','8','9','EAD-01','EAD-02','EAD-03','EAD-04')
