SELECT

SDISCIPLINA.CODDISC,
SDISCIPLINA.NOME,
CASE WHEN SLOGMATRICULA.OPERACAO = 'I' THEN 'INCLUSÃO'
	WHEN SLOGMATRICULA.OPERACAO = 'E' THEN 'EXCLUSÃO'
	WHEN SLOGMATRICULA.OPERACAO = 'A' THEN 'ALTERAÇÃO'
	END AS 'OPERAÇÃO',
CONVERT(varchar, SLOGMATRICULA.DTALTERACAO, 103) AS 'DATA ALTERAÇÃO',
CONVERT(varchar, SMATRICPL.DTMATRICULA, 103) AS 'DATA MATRICULA NO PL'

FROM SLOGMATRICULA 

INNER JOIN SALUNO (NOLOCK) ON
	SALUNO.RA = SLOGMATRICULA.RA

INNER JOIN PPESSOA (NOLOCK) ON
	PPESSOA.CODIGO = SALUNO.CODPESSOA

INNER JOIN STURMADISC (NOLOCK) ON
	STURMADISC.IDTURMADISC = SLOGMATRICULA.IDTURMADISC

INNER JOIN SPLETIVO (NOLOCK) ON
	SPLETIVO.IDPERLET = STURMADISC.IDPERLET

INNER JOIN SDISCIPLINA (NOLOCK) ON
	SDISCIPLINA.CODDISC = STURMADISC.CODDISC

INNER JOIN SMATRICPL (NOLOCK) ON
	SMATRICPL.RA = SALUNO.RA
	AND SMATRICPL.RA = SLOGMATRICULA.RA
	AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	AND SMATRICPL.IDPERLET = STURMADISC.IDPERLET


WHERE 

SLOGMATRICULA.RA = '201220187'
AND SPLETIVO.CODPERLET = '2017.1'
AND CONVERT(varchar, SLOGMATRICULA.DTALTERACAO, 103) <> CONVERT(varchar, SMATRICPL.DTMATRICULA, 103)
AND SLOGMATRICULA.OPERACAO <> 'A'
