SELECT DISTINCT

	SCURSO.NOME + ' - ' + SMODALIDADECURSO.DESCRICAO AS 'CURSO',
	COUNT(SCURSO.NOME + ' - ' + SMODALIDADECURSO.DESCRICAO) AS 'QTD'

FROM SHABILITACAOALUNO (NOLOCK)

	FULL OUTER JOIN STIPOINGRESSO (NOLOCK) ON
			STIPOINGRESSO.CODTIPOINGRESSO = SHABILITACAOALUNO.CODTIPOINGRESSO

	INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.RA = SHABILITACAOALUNO.RA

	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA

	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.RA = SHABILITACAOALUNO.RA
		AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL

	FULL OUTER JOIN SPSPROCESSOSELETIVO (NOLOCK) ON
			SPSPROCESSOSELETIVO.IDPS = SMATRICPL.IDPS

	INNER JOIN SSTATUS (NOLOCK) ON
			SSTATUS.CODSTATUS = SHABILITACAOALUNO.CODSTATUS

	INNER JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.IDPERLET = SMATRICPL.IDPERLET

	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL

	INNER JOIN SCURSO(NOLOCK) ON
	        SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO

	INNER JOIN SMODALIDADECURSO (NOLOCK) ON
			SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO

WHERE 

	SMATRICPL.CODSTATUS = 101
	AND SPLETIVO.CODPERLET = '2021.2'
	AND SMATRICPL.CODFILIAL = 1
	AND SHABILITACAOALUNO.CODSTATUS = 19
	AND SMATRICPL.RA <> '2020110397'

GROUP BY SCURSO.NOME + ' - ' + SMODALIDADECURSO.DESCRICAO,SSTATUS.DESCRICAO,SCURSO.NOME,SMODALIDADECURSO.DESCRICAO

ORDER BY COUNT(SCURSO.NOME + ' - ' + SMODALIDADECURSO.DESCRICAO) DESC