--select * from SHISTHABILITACAOALUNO where SHISTHABILITACAOALUNO.ra = 2017101960
SELECT DISTINCT

      SMATRICULA.RA,
	  PPESSOA.NOME,
	  CONVERT(DECIMAL(10,2),SHISTHABILITACAOALUNO.CR) AS 'CR',
	  SCURSO.NOME


FROM SMATRICULA (NOLOCK)

	INNER JOIN STURMADISC (NOLOCK)
	    INNER JOIN SDISCIPLINA (NOLOCK) ON
	        SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
	        AND SDISCIPLINA.CODDISC     = STURMADISC.CODDISC
	   ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
	   AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SPLETIVO (NOLOCK)
	    ON SPLETIVO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
	   AND SPLETIVO.IDPERLET    = SMATRICULA.IDPERLET
	INNER  JOIN SSTATUS (NOLOCK)
	    ON SSTATUS.CODCOLIGADA = SMATRICULA.CODCOLIGADA
	   AND SSTATUS.CODSTATUS   = SMATRICULA.CODSTATUS
	INNER JOIN SALUNO (NOLOCK)
		ON SALUNO.RA = SMATRICULA.RA
	INNER JOIN SHISTHABILITACAOALUNO (NOLOCK) ON
		SHISTHABILITACAOALUNO.RA = SALUNO.RA
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
		SHABILITACAOFILIAL.CODCOLIGADA = SHISTHABILITACAOALUNO.CODCOLIGADA
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
	INNER JOIN PPESSOA (NOLOCK)
		ON PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO

WHERE
    SPLETIVO.IDPERLET in (168)
AND SSTATUS.CODSTATUS IN (19,104)
AND SHISTHABILITACAOALUNO.CODSTATUS = 19 
AND SHABILITACAOFILIAL.CODFILIAL = 1

GROUP BY SMATRICULA.RA, SSTATUS.DESCRICAO,SHISTHABILITACAOALUNO.QTDPENDDISCOBR, PPESSOA.NOME, SHISTHABILITACAOALUNO.CR,scurso.nome,SHISTHABILITACAOALUNO.QTDPENDDISCOPT

HAVING SHISTHABILITACAOALUNO.QTDPENDDISCOBR <= (COUNT(PPESSOA.NOME)+1)

ORDER BY scurso.nome,PPESSOA.NOME