SELECT DISTINCT
	SCURSO.NOME													[CURSO],
	STURNO.NOME													[TURNO],
	SCURSO.NOME + ' ' + STURNO.NOME								[CABECALHO],
	STURMA.CODTURMA,
	STURMADISC.CODDISC,
	STURMADISC.CODTURNO
FROM STURMA (NOLOCK)
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = STURMA.CODCOLIGADA
		AND SHABILITACAOFILIAL.CODFILIAL = STURMA.CODFILIAL
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMA.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SMODALIDADECURSO (NOLOCK) ON
			SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO
	INNER JOIN STURNO (NOLOCK) ON
			STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND STURNO.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL
		AND STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO
	INNER JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.CODCOLIGADA = STURMA.CODCOLIGADA
		AND SPLETIVO.CODFILIAL = STURMA.CODFILIAL
		AND SPLETIVO.IDPERLET = STURMA.IDPERLET
	INNER JOIN STURMADISC (NOLOCK) ON
			STURMADISC.CODCOLIGADA = STURMA.CODCOLIGADA
		AND STURMADISC.CODTURMA = STURMA.CODTURMA
		AND STURMADISC.IDPERLET = STURMA.IDPERLET
WHERE SPLETIVO.CODPERLET = '2021.2'
AND STURMADISC.ATIVA = 'S'
and STURMADISC.GERENCIAL = 'N'
AND SMODALIDADECURSO.CODMODALIDADECURSO = 1
ORDER BY SCURSO.NOME, STURMADISC.CODDISC