SELECT DISTINCT
	SPSUSUARIO.NOME				[CANDIDATO],
	SPSPROCESSOSELETIVO.NOME	[PROCESSO_SELETIVO],
	SPSUSUARIO.EMAIL,
	SPSUSUARIO.TELEFONE2		[TELEFONE],
	SPSSTATUSOPCAO.DESCRICAO     [STATUS],
	SPSAREAINTERESSE.NOME

FROM SPSINSCRICAOAREAOFERTADA
	INNER JOIN SPSPROCESSOSELETIVO ON
			SPSPROCESSOSELETIVO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
	INNER JOIN SPSUSUARIO ON
			SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
	INNER JOIN SPSOPCAOINSCRITO ON
			SPSOPCAOINSCRITO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
		AND SPSOPCAOINSCRITO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
	INNER JOIN SPSSTATUSOPCAO ON
			SPSSTATUSOPCAO.CODIGO = SPSOPCAOINSCRITO.STATUS
	INNER JOIN SPSAREAINTERESSE ON
			SPSAREAINTERESSE.IDAREAINTERESSE = SPSOPCAOINSCRITO.IDAREAINTERESSE


WHERE
		SPSINSCRICAOAREAOFERTADA.IDPS > 100
	AND DATAINSCRICAO BETWEEN CONVERT(DATETIME, '2018-10-01') AND GETDATE()
	AND SPSOPCAOINSCRITO.STATUS in (0,5)

ORDER BY
	[CANDIDATO]
