
SELECT 
	
	PPESSOA.NOME	[NOMEDESTINATARIO],
	PPESSOA.TELEFONE2,
	'UNIFAP: Voc� assinou o contrato educacional 2021.2. Realize agora o ajuste de disciplinas. D�vidas: atendimento@fapce.edu.br' AS 'TEXTO'

FROM SPLETIVO (NOLOCK)
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	FULL OUTER JOIN SMATRICULA (NOLOCK) ON
			SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SMATRICULA.IDPERLET  = SMATRICPL.IDPERLET
		AND SMATRICULA.RA = SMATRICPL.RA
	INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
			
WHERE 
SPLETIVO.IDPERLET = 168
AND SMATRICPL.CODSTATUS IN (12,101,111)
AND SMATRICPL.CODTIPOMAT NOT IN (34)
GROUP BY PPESSOA.NOME, PPESSOA.TELEFONE2
HAVING COUNT(SMATRICULA.IDTURMADISC) = 0
