SELECT DISTINCT

      SMATRICULA.RA,
	  PPESSOA.NOME AS 'NOME DO ALUNO',
	  SPLETIVO.CODPERLET AS 'PERIODO LETIVO',
	  SDISCIPLINA.NOME AS 'DISCIPLINA', 
	  SSTATUS.DESCRICAO AS 'STATUS',
	  SCURSO.NOME AS 'CURSO'

FROM SMATRICULA (NOLOCK)

	LEFT JOIN SNOTAETAPA (NOLOCK)
	    ON SNOTAETAPA.CODCOLIGADA = SMATRICULA.CODCOLIGADA
	   AND SNOTAETAPA.IDTURMADISC = SMATRICULA.IDTURMADISC
	   AND SNOTAETAPA.RA          = SMATRICULA.RA 
	INNER JOIN STURMADISC (NOLOCK)
	    INNER JOIN SDISCIPLINA (NOLOCK) ON
	        SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
	        AND SDISCIPLINA.CODDISC     = STURMADISC.CODDISC
	   ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
	   AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
	INNER JOIN SPLETIVO (NOLOCK)
	    ON SPLETIVO.CODCOLIGADA = SMATRICULA.CODCOLIGADA
	   AND SPLETIVO.IDPERLET    = SMATRICULA.IDPERLET
	INNER  JOIN SSTATUS (NOLOCK)
	    ON SSTATUS.CODCOLIGADA = SMATRICULA.CODCOLIGADA
	   AND SSTATUS.CODSTATUS   = SMATRICULA.CODSTATUS
	INNER JOIN SALUNO (NOLOCK)
		ON SALUNO.RA = SMATRICULA.RA
	INNER JOIN PPESSOA (NOLOCK)
		ON PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO

WHERE
      SPLETIVO.IDPERLET in (152,155,161,167)
  AND SSTATUS.CODSTATUS IN (19,104)
  AND SNOTAETAPA.TIPOETAPA = 'N'


ORDER BY SCURSO.NOME