
SELECT DISTINCT

	SMATRICPL.RA,
	PPESSOA.NOME,
	SHISTDISCPENDENTES.DISCIPLINA,
	SHISTDISCPENDENTES.PLETIVO AS 'PERIODO',
	SCURSO.NOME AS 'CURSO'

FROM SPLETIVO (NOLOCK)

	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET

	INNER JOIN SMATRICULA (NOLOCK) ON
			SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
		AND SMATRICULA.RA  = SMATRICPL.RA

	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL

	INNER JOIN SHABILITACAOALUNO (NOLOCK) ON
			SHABILITACAOALUNO.RA = SMATRICPL.RA
		AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STIPOCURSO (NOLOCK) ON
			STIPOCURSO.CODTIPOCURSO = SCURSO.CODTIPOCURSO
	INNER JOIN SMODALIDADECURSO (NOLOCK) ON
			SMODALIDADECURSO.CODCOLIGADA = SCURSO.CODCOLIGADA
		AND SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO

	INNER JOIN SALUNO (NOLOCK) ON
		SALUNO.RA = SMATRICPL.RA

	INNER JOIN PPESSOA (NOLOCK) ON
		PPESSOA.CODIGO = SALUNO.CODPESSOA

	INNER JOIN SHISTDISCPENDENTES (NOLOCK) ON
		SMATRICPL.RA = SHISTDISCPENDENTES.RA
		AND SHISTDISCPENDENTES.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

WHERE

	SHISTDISCPENDENTES.PLETIVO NOT IN ('2021.1','2021.2','2020.2','2020.1','POS-2017','2019.1-B','2019.2-B')
	AND STIPOCURSO.CODTIPOCURSO = 1
	AND (CASE WHEN SMATRICPL.IDPERLET = 168 AND SMATRICPL.CODSTATUS IN (12,111,101) THEN 1
   ELSE 0 END ) = 1
	AND SPLETIVO.CODPERLET IN ('2021.2')
	AND SMODALIDADECURSO.DESCRICAO NOT IN ('EAD','SEMIPRESENCIAL')
	AND SCURSO.CODCURSO NOT IN (10,11,12,13,4,9)
	AND SHABILITACAOALUNO.CODSTATUS = 19
	