SELECT  DISTINCT
	
	SCONTRATO.RA, 
	SCURSO.NOME AS 'CURSO', 
	PPESSOA.NOME,
	PPESSOA.EMAIL,
	PPESSOA.TELEFONE2,
	1 AS QTD  
	
	
FROM SCONTRATO (NOLOCK)
	
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
	           SHABILITACAOFILIAL.CODCOLIGADA = SCONTRATO.CODCOLIGADA AND
			   SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
	
	INNER JOIN SCURSO(NOLOCK) ON
	           SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND
			   SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	
	INNER JOIN SALUNO(NOLOCK) ON 
	  SALUNO.CODCOLIGADA = SCONTRATO.CODCOLIGADA AND 
	  SALUNO.RA = SCONTRATO.RA
    
	INNER JOIN SMATRICPL(NOLOCK) ON
	   SMATRICPL.CODCOLIGADA = SCONTRATO.CODCOLIGADA AND
	   SMATRICPL.IDPERLET = SCONTRATO.IDPERLET AND
	   SMATRICPL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL AND
	   SMATRICPL.RA = SCONTRATO.RA

	INNER JOIN PPESSOA (NOLOCK) ON
		SALUNO.CODPESSOA = PPESSOA.CODIGO

 WHERE SCONTRATO.CODCOLIGADA = 1 AND
	   SCONTRATO.CODPLANOPGTO NOT LIKE '%TAXA%' 
    AND SCONTRATO.STATUS = 'N'
	AND SMATRICPL.CODSTATUS IN (12,101,111)
  GROUP BY SCONTRATO.RA, SCURSO.NOME, PPESSOA.NOME,PPESSOA.EMAIL, PPESSOA.TELEFONE2
  HAVING MAX(SCONTRATO.IDPERLET)=168 AND COUNT(SCONTRATO.CODCONTRATO)=1