SELECT 

DISTINCT

TABELA.[COD. COTA플O],	
TABELA.[IDMOV],
TABELA.[NOME PRODUTO],
TABELA.[NOME FANTASIA],
TABELA.[CPF/CNPJ],
TABELA.[TIPO DE PAGAMENTO],
TABELA.[VALOR UNITARIO],
TABELA.[VALOR UNITARIO] + CONVERT(DECIMAL(10,2), ROUND((TABELA.[FRETE]/
(SELECT COUNT (*) FROM (SELECT DISTINCT IDMOV FROM TCITMORCAMENTO ITMORC WHERE ITMORC.CODCOTACAO = TABELA.[COD. COTA플O]) ABC))/
CONVERT(INTEGER, SUM(TABELA.QUANTIDADENEG)),2,0)) AS 'VALOR U. C/ FRETE',
CONVERT(DECIMAL(10,2), TABELA.[QTD]) as 'QTD',
TABELA.[VALOR TOTAL] AS 'VALOR TOTAL ITEM',
TABELA.[DATA COTACAO],

CASE
	WHEN(
			CASE
				WHEN TABELA.QTDEFETIVADA <> 0 AND TABELA.QTDEFETIVADA <> TABELA.QUANTIDADENEG THEN
					(TABELA.[QTDEFETIVADA] *

					(SELECT TOP(1)
						VALCOTACAO
					FROM TCITMORCAMENTO [ITEMORC] 
					WHERE ITEMORC.CODCOTACAO = TABELA.[COD. COTA플O] 
					AND CFOVENCEDOR = 0 
					ORDER BY VALCOTACAO DESC)

					- (CASE
						WHEN QTDEFETIVADA <> 0 THEN CONVERT(DECIMAL(10,2), QTDEFETIVADA * TABELA.[VALOR UNITARIO])
						ELSE CONVERT(DECIMAL(10,2), TABELA.QTD * TABELA.[VALOR UNITARIO])
					END))
			ELSE TABELA.MAIORVALOR - TABELA.MENORVALOR
			END) < 0 THEN '0'
		ELSE (CASE
				WHEN TABELA.QTDEFETIVADA <> 0 AND TABELA.QTDEFETIVADA <> TABELA.QUANTIDADENEG THEN
					(TABELA.[QTDEFETIVADA] *

					(SELECT TOP(1)
						VALCOTACAO
					FROM TCITMORCAMENTO [ITEMORC] 
					WHERE ITEMORC.CODCOTACAO = TABELA.[COD. COTA플O] 
					AND CFOVENCEDOR = 0 
					ORDER BY VALCOTACAO DESC)

					- (CASE
						WHEN QTDEFETIVADA <> 0 THEN CONVERT(DECIMAL(10,2), QTDEFETIVADA * TABELA.[VALOR UNITARIO])
						ELSE CONVERT(DECIMAL(10,2), TABELA.QTD * TABELA.[VALOR UNITARIO])
					END))
			ELSE TABELA.MAIORVALOR - TABELA.MENORVALOR
			END)
END AS 'DESCONTO OBTIDO',

CASE 
	WHEN (TABELA.MAIORVALOR - TABELA.MENORVALOR) = 0 THEN (TABELA.[VAL COTADO] - TABELA.[VAL NEGOCIADO]) * QUANTIDADENEG
	ELSE '0'
END AS 'DESCONTO NEGOCIADO',

TABELA.[DESPESA],
CONVERT(DECIMAL(10,2), ROUND((TABELA.[FRETE]/
(SELECT COUNT (*) FROM (SELECT DISTINCT IDMOV FROM TCITMORCAMENTO ITMORC WHERE ITMORC.CODCOTACAO = TABELA.[COD. COTA플O]) ABC))/
CONVERT(INTEGER, SUM(TABELA.QUANTIDADENEG)),2,0)) as 'FRETE POR ITEM',

CONVERT(DECIMAL(10,2),TABELA.[FRETE]/(SELECT COUNT (*) FROM (SELECT DISTINCT IDMOV FROM TCITMORCAMENTO ITMORC WHERE ITMORC.CODCOTACAO = TABELA.[COD. COTA플O]) ABC)) AS 'FRETE',

TABELA.[DATA CRIA플O],
TABELA.[CODFILIAL]



FROM (

SELECT DISTINCT

TPRODUTO.NOMEFANTASIA AS 'NOME PRODUTO',
ORCAMENTO.IDPRD,
ORCAMENTO.IDMOV AS 'IDMOV',
CONVERT(NVARCHAR, MOVIMENTO_ORIGEM.RECCREATEDON, 103) as 'DATA CRIA플O',
ORCAMENTO.CODCOTACAO AS 'COD. COTA플O',
FCFO.NOME AS 'NOME FANTASIA',
FCFO.CGCCFO AS 'CPF/CNPJ',
TCPG.NOME AS 'TIPO DE PAGAMENTO',
ORCAMENTO.VALHOMOGENEOCOTADO AS 'VAL COTADO',
ORCAMENTO.VALHOMOGENEONEGOCIADO AS 'VAL NEGOCIADO',
VALNEGOCIADO AS 'VALOR UNITARIO',
ORCAMENTO.QTDEFETIVADA,

CASE
	WHEN ORCAMENTO.QTDEFETIVADA <> 0 THEN ORCAMENTO.QTDEFETIVADA
	ELSE ORCAMENTO.QUANTIDADENEG
END AS 'QTD',

CASE
	WHEN QTDEFETIVADA <> 0 THEN QTDEFETIVADA * ORCAMENTO.VALHOMOGENEONEGOCIADO
	ELSE QUANTIDADENEG * ORCAMENTO.VALHOMOGENEONEGOCIADO
END 'VALOR TOTAL',

MOVIMENTO_ORIGEM.CODFILIAL,
TCCOTACAO.DATCOTACAO AS 'DATA COTACAO',
TCORCAMENTO.DESPESA AS 'DESPESA',
TCORCAMENTO.VALORFRETE AS 'FRETE',
TCCOTACAO.STSCOTACAO AS 'STATUS',
ORCAMENTO.CFOVENCEDOR AS 'VENCEDOR',
ORCAMENTO.QUANTIDADENEG,



(SELECT TOP(1) 
	CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC 

FROM TCORCAMENTO

	INNER JOIN TCITMORCAMENTO ON
		TCITMORCAMENTO.CODCOTACAO = TCORCAMENTO.CODCOTACAO
		AND TCITMORCAMENTO.CODCFO = TCORCAMENTO.CODCFO
		AND TCITMORCAMENTO.CODCOLCFO = TCORCAMENTO.CODCOLCFO

	INNER JOIN FCFO ON
		FCFO.CODCFO = TCITMORCAMENTO.CODCFO

	INNER JOIN TCPG ON
		TCPG.CODCPG = TCORCAMENTO.CODCPGNEGOCIADA

	INNER JOIN TPRODUTO ON
		TPRODUTO.IDPRD = TCITMORCAMENTO.IDPRD

	INNER JOIN TCCOTACAO ON
		TCCOTACAO.CODCOTACAO = ORCAMENTO.CODCOTACAO
		
	WHERE TCORCAMENTO.CODCOTACAO = ORCAMENTO.CODCOTACAO  AND TCITMORCAMENTO.IDMOV = ORCAMENTO.IDMOV AND TCITMORCAMENTO.IDPRD = ORCAMENTO.IDPRD
	ORDER BY CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC DESC
	) AS 'MAIORVALOR',

 (SELECT TOP(1) 
		CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC 

	FROM TCORCAMENTO

	INNER JOIN TCITMORCAMENTO ON
		TCITMORCAMENTO.CODCOTACAO = TCORCAMENTO.CODCOTACAO
		AND TCITMORCAMENTO.CODCFO = TCORCAMENTO.CODCFO
		AND TCITMORCAMENTO.CODCOLCFO = TCORCAMENTO.CODCOLCFO
			
	INNER JOIN FCFO ON
		FCFO.CODCFO = TCITMORCAMENTO.CODCFO

	INNER JOIN TCPG ON
		TCPG.CODCPG = TCORCAMENTO.CODCPGNEGOCIADA

	INNER JOIN TPRODUTO ON
		TPRODUTO.IDPRD = TCITMORCAMENTO.IDPRD

	INNER JOIN TCCOTACAO ON
		TCCOTACAO.CODCOTACAO = ORCAMENTO.CODCOTACAO
	
	WHERE TCORCAMENTO.CODCOTACAO = ORCAMENTO.CODCOTACAO		AND TCITMORCAMENTO.IDMOV = ORCAMENTO.IDMOV AND TCITMORCAMENTO.IDPRD = ORCAMENTO.IDPRD AND VALCOTACAO * TCITMORCAMENTO.QUANTIDADEORC > 0 
	AND TCITMORCAMENTO.CFOVENCEDOR = 1
	ORDER BY CONVERT(DECIMAL(10,2), VALHOMOGENEONEGOCIADO) * TCITMORCAMENTO.QUANTIDADEORC ASC
	) AS 'MENORVALOR'


FROM TCITMORCAMENTO AS ORCAMENTO

	INNER JOIN TCORCAMENTO ON
		TCORCAMENTO.CODCOTACAO = ORCAMENTO.CODCOTACAO
		AND TCORCAMENTO.CODCFO = ORCAMENTO.CODCFO
		AND TCORCAMENTO.CODCOLCFO = ORCAMENTO.CODCOLCFO

	INNER JOIN FCFO ON
		FCFO.CODCFO = ORCAMENTO.CODCFO

	INNER JOIN TCPG ON
		TCPG.CODCPG = ORCAMENTO.CODCPGNEGOCIADA 

	INNER JOIN TPRODUTO ON
		TPRODUTO.IDPRD = ORCAMENTO.IDPRD

	INNER JOIN TCCOTACAO ON
		TCCOTACAO.CODCOTACAO = ORCAMENTO.CODCOTACAO

	INNER JOIN TMOVRELAC ON
			TMOVRELAC.IDMOVORIGEM = ORCAMENTO.IDMOV

	INNER JOIN TMOV MOVIMENTO_ORIGEM ON
			MOVIMENTO_ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM

	) TABELA

WHERE TABELA.[VENCEDOR] = 1 AND TABELA.[STATUS] <> 7 
AND TABELA.[DATA COTACAO] >= '12/07/2021' AND TABELA.[DATA COTACAO] <= '12/08/2021'
GROUP BY TABELA.[COD. COTA플O],TABELA.IDMOV,TABELA.[NOME PRODUTO],TABELA.CODFILIAL,TABELA.[NOME FANTASIA],TABELA.[CPF/CNPJ],
TABELA.[DATA COTACAO],TABELA.[DATA CRIA플O],TABELA.[TIPO DE PAGAMENTO],TABELA.[VALOR UNITARIO],
TABELA.IDPRD,TABELA.QTD,TABELA.QTDEFETIVADA,TABELA.QUANTIDADENEG,TABELA.[VALOR TOTAL],TABELA.MAIORVALOR,
TABELA.MENORVALOR,TABELA.[VAL COTADO],TABELA.[VAL NEGOCIADO],TABELA.DESPESA,TABELA.FRETE

