SELECT
	UPPER(SPSUSUARIO.NOME)									[CANDIDATO],
	LOWER(SPSUSUARIO.EMAIL)									[EMAIL],
	SPSUSUARIO.TELEFONE2									[TELEFONE],
	REPLACE(CONVERT(VARCHAR, SPSUSUARIO.DTNASCIMENTO, 103), '/', '')	[DTNASCIMENTO],
	SPSUSUARIO.CPF

FROM
	SPSUSUARIO
	INNER JOIN BEXECPROVA ON
			BEXECPROVA.CODUSUARIOPS = SPSUSUARIO.CODUSUARIOPS
	LEFT JOIN PPESSOA ON
			PPESSOA.CPF = SPSUSUARIO.CPF
	LEFT JOIN SALUNO ON
			SALUNO.CODPESSOA = PPESSOA.CODIGO

WHERE 
		BEXECPROVA.CODPROVA IN (259)
	AND SPSUSUARIO.NOME NOT LIKE 'TESTE%'

ORDER BY
	[CANDIDATO]

