SELECT
	SPSUSUARIO.NOME				[CANDIDATO],
	SPSPROCESSOSELETIVO.NOME	[PROCESSO_SELETIVO],
	SPSUSUARIO.EMAIL,
	SPSUSUARIO.TELEFONE2		[TELEFONE]

FROM SPSINSCRICAOAREAOFERTADA
	INNER JOIN SPSPROCESSOSELETIVO ON
			SPSPROCESSOSELETIVO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
	INNER JOIN SPSUSUARIO ON
			SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
	INNER JOIN SPSOPCAOINSCRITO ON
			SPSOPCAOINSCRITO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
		AND SPSOPCAOINSCRITO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS

WHERE
		SPSINSCRICAOAREAOFERTADA.IDPS IN (189, 191, 193, 195, 198, 199, 200, 201)
	AND DATAINSCRICAO BETWEEN CONVERT(DATETIME, '2021-12-07') AND GETDATE()
	AND SPSOPCAOINSCRITO.STATUS = 5

ORDER BY
	[CANDIDATO]
