SELECT
	SPSINSCRICAOAREAOFERTADA.NUMEROINSCRICAO,
	SPSUSUARIO.NOME,
	SPSUSUARIO.CPF,
	SPSUSUARIO.TELEFONE2		[TELEFONE],
	CONVERT(VARCHAR(12), SPSINSCRICAOAREAOFERTADA.DATAINSCRICAO, 103)		[DATA_INSCRICAO],
	CASE
		WHEN SPSINSCRICAOAREAOFERTADA.STATUS = 0 THEN 'Inscrito (pendente de confirmação do pagamento)'
		WHEN SPSINSCRICAOAREAOFERTADA.STATUS = 8 THEN 'Inscrição cancelada'
		WHEN SPSINSCRICAOAREAOFERTADA.STATUS = 1 THEN 'Candidato (inscrição confirmada)'
	END AS STATUS,
	CASE
		WHEN FLAN.STATUSLAN = 0 THEN 'Em aberto'
		WHEN FLAN.STATUSLAN = 1 THEN 'Quitado'
		WHEN FLAN.STATUSLAN = 2 THEN 'Cancelado'
	END AS STATUSLAN,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTAHUMANAS,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTALINGUAGEM,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTAMATEMATICA,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTANATUREZA,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTAREDACAO,
	SPSINSCRICAOAREAOFERTADA.ENEMNOTAOBJETIVA

FROM
	SPSINSCRICAOAREAOFERTADA
	INNER JOIN SPSUSUARIO ON
			SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
	INNER JOIN FLAN ON 
			FLAN.IDLAN = SPSINSCRICAOAREAOFERTADA.IDLAN

WHERE 
		SPSINSCRICAOAREAOFERTADA.IDPS = 185
	AND FLAN.STATUSLAN IN (0, 1)
