-- RA, ALUNO, CURSO, EMAIL, DTMATRICULA, CODPERLET, TELEFONE1, TELEFONE2
-- Apenas EAD (Turno Integral)

SELECT DISTINCT 
	COUNT(SALUNO.RA)									[QTD], 
	SALUNO.RA,
	UPPER(PPESSOA.NOME)									[ALUNO], 
	SCURSO.NOME											[CURSO],
	STURNO.NOME											[TURNO],
	SPLETIVO.CODPERLET									[PERIODO_LETIVO],
	CONVERT(VARCHAR(12), SMATRICPL.DTMATRICULA, 103)	[DATA_MATRICULA],
	LOWER(PPESSOA.EMAIL)								[EMAIL],
	PPESSOA.TELEFONE1,
	PPESSOA.TELEFONE2

FROM SPLETIVO (NOLOCK)
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN STURNO (NOLOCK) ON
			STURNO.CODTURNO=SHABILITACAOFILIAL.CODTURNO

WHERE
		SMATRICPL.PERIODO = 1			-- Alunos Ingressantes 
	AND SMATRICPL.CODTIPOMAT NOT IN (35, 43)
	and SPLETIVO.CODPERLET = '2021.1' 
	--AND SMATRICPL.DTMATRICULA = CONVERT(VARCHAR(12), '2008-09-24 09:50:11.470', 103)
	
GROUP BY 
	SALUNO.RA,
	PPESSOA.NOME,
	SCURSO.NOME,
	STURNO.NOME,
	SPLETIVO.CODPERLET,
	SMATRICPL.DTMATRICULA,
	PPESSOA.EMAIL,
	PPESSOA.TELEFONE1,
	PPESSOA.TELEFONE2
	