/*
Dados do Aluno:
	- Nome
		SALUNO(CODPESSOA) -> PPESSOA(CODIGO) - PPESSOA(NOME)
	- Curso
		SMATRICPL(IDHABILITACAOFILIAL) -> SHABILITACAOFILIAL(CODCURSO) -> SCURSO(NOME)
	- Endereço, Telefone
		PPESSOA
*/

SELECT 
	P_ALUNO.NOME	[ALUNO],
	SCURSO.NOME		[CURSO],
	P_ALUNO.RUA,
	P_ALUNO.NUMERO,
	P_ALUNO.BAIRRO,
	P_ALUNO.CIDADE	[MUNICIPIO],
	P_ALUNO.ESTADO	[ESTADO],
	P_ALUNO.TELEFONE2	[TELEFONE],
	P_ALUNO.CPF,
	STURNO.NOME [TURNO],
	SMATRICPL.PERIODO

FROM 
	SESTAGIOCONTRATO
	INNER JOIN SPLETIVO ON
			SPLETIVO.IDPERLET = SESTAGIOCONTRATO.IDPERLET
	INNER JOIN SALUNO ON
			SALUNO.RA = SESTAGIOCONTRATO.RA
	INNER JOIN PPESSOA P_ORIENTADOR ON
			P_ORIENTADOR.CODIGO = SESTAGIOCONTRATO.CODPESSOAORIENTADOR
	INNER JOIN PPESSOA P_ALUNO ON
			P_ALUNO.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SESTAGIOCONTRATO.IDHABILITACAOFILIAL
	INNER JOIN SCURSO ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SMATRICPL ON
			SMATRICPL.IDPERLET = SESTAGIOCONTRATO.IDPERLET
		AND SMATRICPL.IDHABILITACAOFILIAL = SESTAGIOCONTRATO.IDHABILITACAOFILIAL
		AND SMATRICPL.RA = SESTAGIOCONTRATO.RA
	INNER JOIN STURNO ON
			STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO

