-- A, F, E, C

select DISTINCT 
	PFUNC.NOME,
	PPESSOA.CPF, 
	CONVERT(VARCHAR, PPESSOA.DTNASCIMENTO, 103) [DTNASCIMENTO],
	CASE
		WHEN PFUNCAO.NOME LIKE 'Professor%' THEN 'S'
		WHEN PFUNCAO.NOME NOT LIKE 'Professor%' THEN 'N'
		ELSE NULL
	END AS [PROFESSOR?],
	PFUNCAO.NOME,
	GUSUARIO.CODUSUARIO,
	PPESSOA.EMAIL
from PFUNC
	INNER JOIN PFUNCAO ON
			PFUNCAO.CODIGO = PFUNC.CODFUNCAO
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = PFUNC.CODPESSOA
	LEFT JOIN GUSUARIO ON
			GUSUARIO.CODUSUARIO = PPESSOA.CODUSUARIO
where 
	GUSUARIO.STATUS = 1 OR GUSUARIO.STATUS IS NULL
order by pfunc.nome

