SELECT DISTINCT SALUNO.CODCOLIGADA, SALUNO.RA, SMATRICPL.IDHABILITACAOFILIAL, SMATRICPL.IDPERLET, PPESSOA.NOME FROM SPLETIVO (NOLOCK)
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
	INNER JOIN SCONTRATO (NOLOCK) ON
			SCONTRATO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SCONTRATO.IDPERLET = SMATRICPL.IDPERLET
		AND SCONTRATO.RA = SMATRICPL.RA
		AND SCONTRATO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SPARCELA (NOLOCK) ON
			SPARCELA.IDPERLET = SCONTRATO.IDPERLET
		AND SPARCELA.RA = SCONTRATO.RA
		AND SPARCELA.CODCONTRATO = SCONTRATO.CODCONTRATO
	INNER JOIN SLAN (NOLOCK) ON
			SLAN.IDPARCELA = SPARCELA.IDPARCELA
	INNER JOIN FLAN (NOLOCK) ON
			FLAN.IDLAN = SLAN.IDLAN
WHERE SMATRICPL.CODSTATUS = 125
AND FLAN.STATUSLAN = 1;