SELECT DISTINCT
	UPPER(PPESSOA.NOME) [NOME],
	PPESSOA.TELEFONE2	[TELEFONE],
	LOWER(PPESSOA.EMAIL)		[EMAIL]

FROM SMATRICPL
	INNER JOIN SSTATUS ON
			SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
	INNER JOIN SPLETIVO ON
			SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA

WHERE
		SPLETIVO.CODPERLET IN ('2019.1', '2019.2', '2020.1', '2020.2', '2021.1', '2021.2')
	AND SMATRICPL.CODSTATUS IN (5, 7, 101, 111, 124, 125)

ORDER BY
	[NOME]
