-- 1: CANDIDATO
-- 0: INSCRITO (PENDENTE DE CONFIRMAÇÃO DO PAGAMENTO)
-- 8: INSCRIÇÃO CANCELADA

SELECT DISTINCT
	SPSUSUARIO.CODUSUARIOPS,
	SPSINSCRICAOAREAOFERTADA.STATUS,
	SPSPROCESSOSELETIVO.IDPS,
	SPSPROCESSOSELETIVO.NOME AS PS,
	SPSUSUARIO.ESTADO,
	SPSUSUARIO.CIDADE,
	SPSUSUARIO.SEXO,
	SPSUSUARIO.DTNASCIMENTO,
	YEAR(GETDATE()) - YEAR(SPSUSUARIO.DTNASCIMENTO) AS IDADE,
	SPSAREAINTERESSE.IDAREAINTERESSE,
	SPSAREAINTERESSE.NOME

FROM
	SPSINSCRICAOAREAOFERTADA
	INNER JOIN SPSPROCESSOSELETIVO ON
			SPSPROCESSOSELETIVO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
	INNER JOIN SPSUSUARIO ON
			SPSUSUARIO.CODUSUARIOPS = SPSINSCRICAOAREAOFERTADA.CODUSUARIOPS
	INNER JOIN SPSOPCAOINSCRITO ON
			SPSOPCAOINSCRITO.IDPS = SPSINSCRICAOAREAOFERTADA.IDPS
		AND SPSOPCAOINSCRITO.CODUSUARIOPS = SPSUSUARIO.CODUSUARIOPS
	INNER JOIN SPSAREAINTERESSE ON
			SPSAREAINTERESSE.IDAREAINTERESSE = SPSOPCAOINSCRITO.IDAREAINTERESSE