-- 1: integral exclusivo
-- 2: integral não exclusivo
-- 3: parcial
-- 4: horista

select 
	SPLETIVO.CODPERLET,
	SPROFESSORMEC.REGIMETRABALHO,
	COUNT(DISTINCT SPROFESSORTURMA.CODPROF) TOTAL
from
	STURMADISC
	INNER JOIN SPROFESSORTURMA ON
			SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
	INNER JOIN SPLETIVO ON
			SPLETIVO.IDPERLET = STURMADISC.IDPERLET
	INNER JOIN SPROFESSORMEC ON
			SPROFESSORMEC.CODPROF = SPROFESSORTURMA.CODPROF

WHERE
	SPLETIVO.CODPERLET IN ('2019.1', '2019.2', '2020.1', '2020.2')

GROUP BY
	SPLETIVO.CODPERLET, SPROFESSORMEC.REGIMETRABALHO

ORDER BY
	SPLETIVO.CODPERLET, SPROFESSORMEC.REGIMETRABALHO