SELECT DISTINCT
	SPLETIVO.CODPERLET		[PERIODO_LETIVO],
	STITULACAO.NOME			[TITULACAO],
	COUNT(DISTINCT(SPROFESSORTURMA.CODPROF)) AS TOTAL

FROM
	STURMADISC
	INNER JOIN SPLETIVO ON
			SPLETIVO.IDPERLET = STURMADISC.IDPERLET
	INNER JOIN SPROFESSORTURMA ON
			SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN SPROFESSOR ON
			SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN STITULACAO ON
			STITULACAO.CODTITULACAO = SPROFESSOR.CODTITULACAO 
WHERE 
	SPLETIVO.CODPERLET IN ('2019.2', '2020.2')

GROUP BY
	spletivo.codperlet, STITULACAO.NOME
ORDER BY
	SPLETIVO.CODPERLET, STITULACAO.NOME
