-- Informações de Alunos matriculados em 2021.1
-- RA, NOME, PERIODO LETIVO, CURSO, CODIGO DA TURMA, TURNO, CODIGO DA DISCIPLINA, DISCIPLINA

SELECT
	SALUNO.RA,
	PPESSOA.NOME,
	SMATRICPL.IDPERLET,
	SPLETIVO.CODPERLET,
	SCURSO.NOME AS 'CURSO',
	STURMADISC.CODTURMA,
	STURMADISC.CODTURNO AS 'TURNO',
	STURMADISC.CODDISC,
	SDISCIPLINA.NOME AS 'DISCIPLINA'

FROM
	SALUNO
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO=SALUNO.CODPESSOA -- PPESSOA para pegar o NOME
	INNER JOIN SMATRICPL ON
			SMATRICPL.RA=SALUNO.RA -- SMATRICPL para pegar o IDPERLET
	INNER JOIN SPLETIVO ON
			SMATRICPL.IDPERLET=SPLETIVO.IDPERLET -- SPLETIVO para pegar o CODPERLET
	INNER JOIN SHABILITACAOFILIAL ON
			SMATRICPL.IDHABILITACAOFILIAL=SHABILITACAOFILIAL.IDHABILITACAOFILIAL -- SHABILITACAOFILIAL para pegar o CODTURNO
	INNER JOIN SCURSO ON
			SHABILITACAOFILIAL.CODCURSO=SCURSO.CODCURSO -- SCURSO para pegar o NOMECURSO
	INNER JOIN STURMADISC ON
			SMATRICPL.CODTURMA=STURMADISC.CODTURMA
		AND SMATRICPL.IDPERLET=STURMADISC.IDPERLET -- STURMADISC para pegar CODDISC
	INNER JOIN SDISCIPLINA ON
			STURMADISC.CODDISC=SDISCIPLINA.CODDISC -- SDISCIPLINA para pegar NOMEDISC

WHERE
	SMATRICPL.IDPERLET=167

ORDER BY
	saluno.RA;


