select distinct smatricpl.codstatus, sstatus.DESCRICAO
from smatricpl 
	inner join sstatus on
			sstatus.CODSTATUS = smatricpl.CODSTATUS
where idperlet = 167

select * from smatricpl where ra = '201110170'


select
	--spletivo.codperlet  [PERIODO_LETIVO],
	CONVERT(VARCHAR(12), SMATRICPL.DTMATRICULA, 103) [DATA_MATRICULA],
	COUNT(SMATRICPL.DTMATRICULA) [TOTAL]
from smatricpl
	inner join spletivo on
			spletivo.idperlet = smatricpl.idperlet
where smatricpl.PERIODO = 1 AND YEAR(SMATRICPL.DTMATRICULA) >= 2012
GROUP BY SMATRICPL.DTMATRICULA
ORDER BY SMATRICPL.DTMATRICULA

-- 8, 22, 3
select distinct
	saluno.ra				[MATRICULA],
	UPPER(ppessoa.nome)		[ALUNO],
	scurso.NOME				[CURSO],
	smatricpl.PERIODO		[PERIODO],
	sstatus.DESCRICAO		[STATUS],
	LOWER(ppessoa.email)	[EMAIL],
	ppessoa.TELEFONE2		[TELEFONE]
FROM
	SPLETIVO
	INNER JOIN SMATRICPL ON
			SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SMATRICULA ON
			SMATRICULA.RA = SMATRICPL.RA
		AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SSTATUS ON
			SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
	INNER JOIN SALUNO ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
where shabilitacaofilial.codcurso in ('8', '22', '3') and SSTATUS.CODSTATUS IN (12, 101, 111) and spletivo.idperlet=167