-- RA, NOME, PERIODO LETIVO, CURSO, CODIGO DA TURMA, TURNO, CODIGO DA DISCIPLINA, DISCIPLINA

-- RA, CODPESSOA (FK)
select *
from saluno;

-- CODIGO, NOME
select top 5 *
from ppessoa;

-- IDPERLET (FK), 
select top 25 *
from SMATRICPL
where idperlet=167
order by ra;

select top 5*
from smatricpl

-- 
select top 5 *
from SMATRICULA;

-- IDPERLET, CODPERLET, DESCRICAO
select top 5 *
from SPLETIVO;

-- IDHABILITACAOFILIAL, CODTURNO (FK), CODCURSO (FK)
select top 5 *
from SHABILITACAOFILIAL;

-- CODCURSO, NOME
select top 5 *
from SCURSO;

-- CODTURNO, CODTIPOCURSO (FK)
select top 5 *
from STURNO;

-- CODMODALIDADECURSO, DESCRICAO
select top 5 *
from SMODALIDADECURSO;

-- IDTURMADISC, CODTURMA, IDPERLET (FK), CODDISC (FK)
select top 25 *
from STURMADISC;

-- CODDISC, NOME
select top 5 *
from SDISCIPLINA;


select top 5 *
from STURMA;

select *
from GLINKSREL
WHERE MASTERtable='sturma';

-- antigo cubo de ingressantes
SELECT DISTINCT 
	COUNT(SALUNO.RA)	[QTD], 
	SALUNO.RA, 
	PPESSOA.NOME		[ALUNO], 
	SCURSO.NOME			[CURSO],
	SPLETIVO.CODPERLET	[PERIODO_LETIVO],
	PPESSOA.EMAIL,
	PPESSOA.TELEFONE1,
	PPESSOA.TELEFONE2
FROM SPLETIVO (NOLOCK)
	INNER JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.CODFILIAL = SPLETIVO.CODFILIAL
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SALUNO (NOLOCK) ON
			SALUNO.RA = SMATRICPL.RA
	INNER JOIN PPESSOA (NOLOCK) ON
			PPESSOA.CODIGO = SALUNO.CODPESSOA
WHERE SMATRICPL.PERIODO = 1
AND SMATRICPL.CODTIPOMAT NOT IN (35, 43)
GROUP BY SALUNO.RA, PPESSOA.NOME, SCURSO.NOME, SPLETIVO.CODPERLET, PPESSOA.EMAIL, PPESSOA.TELEFONE1, PPESSOA.TELEFONE2



SELECT 
	COUNT(SMATRICPL.RA)		[QTD_EVASAO], 
	SMATRICPL.PERIODO,
	SPLETIVO.CODPERLET		[PERIODO_LETIVO],
	SCURSO.NOME				[CURSO]
FROM SPLETIVO (NOLOCK)
	JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SPLETIVO.CODCOLIGADA
		AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	JOIN SCURSO (NOLOCK) ON
			SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
		AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
WHERE CODSTATUS NOT IN (5,12,101,111,7,13) AND SPLETIVO.CODTIPOCURSO = 1
GROUP BY SCURSO.NOME, SMATRICPL.PERIODO, SPLETIVO.CODPERLET
