SELECT DISTINCT
	SCURSO.NOME,
	SMODALIDADECURSO.DESCRICAO,
	--STURMADISC.CODTURMA
	COUNT(DISTINCT STURMADISC.CODTURMA) AS TOTAL
	
FROM
	STURMADISC
	INNER JOIN SHABILITACAOFILIAL ON
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
	INNER JOIN SCURSO ON
			SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	INNER JOIN SMODALIDADECURSO ON
			SMODALIDADECURSO.CODMODALIDADECURSO = SCURSO.CODMODALIDADECURSO

WHERE
		STURMADISC.ATIVA = 'S'
	AND STURMADISC.GERENCIAL = 'N'
	AND STURMADISC.IDPERLET = 167
	AND SMODALIDADECURSO.CODMODALIDADECURSO = 1

GROUP BY
		SCURSO.NOME,
		SMODALIDADECURSO.DESCRICAO

ORDER BY
	SCURSO.NOME
